--코멘트 수정
SELECT 'COMMENT ON COLUMN ' || TABLE_NAME || '.' || COLUMN_NAME || ' IS '''';' 
FROM COLS
WHERE TABLE_NAME = 'SCORE_INDEPTH'
AND NOT COLUMN_NAME = 'APPLY_SN'
AND NOT INSTR(COLUMN_NAME, 'TOTAL') > 0
AND NOT INSTR(COLUMN_NAME, 'SCORE_DATE') > 0
AND NOT INSTR(COLUMN_NAME, 'MEM_ID') > 0;

SELECT *
FROM ITEM_CODE 
--INNER JOIN PROCESS_CODE B ON (A.PROCESS_CODE_ID = B.PROCESS_CODE_ID);
WHERE PROCESS_CODE_ID = 'PRC08';

SELECT *
FROM ALL_COL_COMMENTS
WHERE TABLE_NAME = 'SCORE_INDEPTH';

COMMENT ON COLUMN SCORE_RESUME.RESUME_CAREER IS '경력' ;
COMMENT ON COLUMN SCORE_RESUME.RESUME_EDU IS '학력' ;
COMMENT ON COLUMN SCORE_RESUME.RESUME_CERT IS '자격증' ;
COMMENT ON COLUMN SCORE_RESUME.RESUME_FACILITY IS '기능' ;
COMMENT ON COLUMN SCORE_RESUME.RESUME_ACTIVITY IS '주요활동' ;
COMMENT ON COLUMN SCORE_RESUME.RESUME_SOCIAL IS '사회경험' ;
COMMENT ON COLUMN SCORE_RESUME.RESUME_AWARD IS '수상내역' ;
COMMENT ON COLUMN SCORE_RESUME.RESUME_COURSE IS '교육이수' ;
COMMENT ON COLUMN SCORE_RESUME.RESUME_DUTY IS '병역사항' ;
COMMENT ON COLUMN SCORE_RESUME.RESUME_ADD1 IS '추가항목1' ;
COMMENT ON COLUMN SCORE_RESUME.RESUME_ADD2 IS '추가항목2' ;
COMMENT ON COLUMN SCORE_RESUME.RESUME_ADD3 IS '추가항목3' ;

COMMENT ON COLUMN SCORE_INTRODUCTION.INTRO_GROWTH IS '성장과정';
COMMENT ON COLUMN SCORE_INTRODUCTION.INTRO_PERSONALITY IS '성격장단점';
COMMENT ON COLUMN SCORE_INTRODUCTION.INTRO_SCHOOLDAY IS '학창시절';
COMMENT ON COLUMN SCORE_INTRODUCTION.INTRO_JOB IS '직무경험';
COMMENT ON COLUMN SCORE_INTRODUCTION.INTRO_MOTIVE IS '지원동기';
COMMENT ON COLUMN SCORE_INTRODUCTION.INTRO_ASPIRATION IS '입사후포부';
COMMENT ON COLUMN SCORE_INTRODUCTION.INTRO_FAMILY IS '가족소개';
COMMENT ON COLUMN SCORE_INTRODUCTION.INTRO_SUBACTIVITY IS '교외활동';
COMMENT ON COLUMN SCORE_INTRODUCTION.INTRO_MAJOR IS '전공선택';
COMMENT ON COLUMN SCORE_INTRODUCTION.INTRO_COURSE IS '생활진로';
COMMENT ON COLUMN SCORE_INTRODUCTION.INTRO_OBJECTIVE IS '희망업무';
COMMENT ON COLUMN SCORE_INTRODUCTION.INTRO_CLUB IS '동아리';
COMMENT ON COLUMN SCORE_INTRODUCTION.INTRO_VOLUNTEER IS '봉사활동';
COMMENT ON COLUMN SCORE_INTRODUCTION.INTRO_ADD1 IS '추가항목1';
COMMENT ON COLUMN SCORE_INTRODUCTION.INTRO_ADD2 IS '추가항목2';
COMMENT ON COLUMN SCORE_INTRODUCTION.INTRO_ADD3 IS '추가항목3';

COMMENT ON COLUMN SCORE_TEST.TEST_SUBJECT1 IS '과목1';
COMMENT ON COLUMN SCORE_TEST.TEST_SUBJECT2 IS '과목2';
COMMENT ON COLUMN SCORE_TEST.TEST_SUBJECT3 IS '과목3';
COMMENT ON COLUMN SCORE_TEST.TEST_SUBJECT4 IS '과목4';
COMMENT ON COLUMN SCORE_TEST.TEST_SUBJECT5 IS '과목5';
COMMENT ON COLUMN SCORE_TEST.TEST_ADD1 IS '추가과목1';
COMMENT ON COLUMN SCORE_TEST.TEST_ADD2 IS '추가과목2';
COMMENT ON COLUMN SCORE_TEST.TEST_ADD3 IS '추가과목3';

COMMENT ON COLUMN SCORE_COMPETENCY.COMPETE_FACIAL IS '시선과표정';
COMMENT ON COLUMN SCORE_COMPETENCY.COMPETE_POSTURE IS '대면자세및행동';
COMMENT ON COLUMN SCORE_COMPETENCY.COMPETE_SPEAKING IS '언어와표현';
COMMENT ON COLUMN SCORE_COMPETENCY.COMPETE_QUERY IS '질의파악능력';
COMMENT ON COLUMN SCORE_COMPETENCY.COMPETE_META_COG IS '메타인지';
COMMENT ON COLUMN SCORE_COMPETENCY.COMPETE_RECOG IS '상황인식능력';
COMMENT ON COLUMN SCORE_COMPETENCY.COMPETE_RESOLVE IS '문제해결능력';
COMMENT ON COLUMN SCORE_COMPETENCY.COMPETE_EXPRESSION IS '자기표현력';
COMMENT ON COLUMN SCORE_COMPETENCY.COMPETE_LOGIC IS '논리력';
COMMENT ON COLUMN SCORE_COMPETENCY.COMPETE_LEADER IS '리더십';
COMMENT ON COLUMN SCORE_COMPETENCY.COMPETE_RELATION IS '인간관계';
COMMENT ON COLUMN SCORE_COMPETENCY.COMPETE_ADD1 IS '추가항목1';
COMMENT ON COLUMN SCORE_COMPETENCY.COMPETE_ADD2 IS '추가항목2';
COMMENT ON COLUMN SCORE_COMPETENCY.COMPETE_ADD3 IS '추가항목3';

COMMENT ON COLUMN SCORE_DISCUSS.DISCUSS_POSTURE IS '토론자세';
COMMENT ON COLUMN SCORE_DISCUSS.DISCUSS_SUBJECT IS '주제파악';
COMMENT ON COLUMN SCORE_DISCUSS.DISCUSS_PROBLEM IS '문제파악';
COMMENT ON COLUMN SCORE_DISCUSS.DISCUSS_RESOLVE IS '해결방안';
COMMENT ON COLUMN SCORE_DISCUSS.DISCUSS_QUERY IS '질의파악능력';
COMMENT ON COLUMN SCORE_DISCUSS.DISCUSS_PROGRESS IS '토론진행';
COMMENT ON COLUMN SCORE_DISCUSS.DISCUSS_ADD1 IS '추가항목1';
COMMENT ON COLUMN SCORE_DISCUSS.DISCUSS_ADD2 IS '추가항목2';
COMMENT ON COLUMN SCORE_DISCUSS.DISCUSS_ADD3 IS '추가항목3';

COMMENT ON COLUMN SCORE_PRACTICE.PRACTICE_UNDERSTAND IS '직무이해도';
COMMENT ON COLUMN SCORE_PRACTICE.PRACTICE_APPROPRIATE IS '직무적합성';
COMMENT ON COLUMN SCORE_PRACTICE.PRACTICE_KNOWLEDGE IS '실무관련지식';
COMMENT ON COLUMN SCORE_PRACTICE.PRACTICE_EXPERIENCE IS '실무경험';
COMMENT ON COLUMN SCORE_PRACTICE.PRACTICE_ADD1 IS '추가항목1';
COMMENT ON COLUMN SCORE_PRACTICE.PRACTICE_ADD2 IS '추가항목2';
COMMENT ON COLUMN SCORE_PRACTICE.PRACTICE_ADD3 IS '추가항목3';
COMMENT ON COLUMN SCORE_PRACTICE.PRACTICE_ADD4 IS '추가항목4';
COMMENT ON COLUMN SCORE_PRACTICE.PRACTICE_ADD5 IS '추가항목5';

COMMENT ON COLUMN SCORE_INTERNSHIP.INTERN_ACHIVE IS '업무달성도';
COMMENT ON COLUMN SCORE_INTERNSHIP.INTERN_TRUST IS '업무신뢰도';
COMMENT ON COLUMN SCORE_INTERNSHIP.INTERN_CREATIVITY IS '창의력';
COMMENT ON COLUMN SCORE_INTERNSHIP.INTERN_KNOW IS '직무지식';
COMMENT ON COLUMN SCORE_INTERNSHIP.INTERN_DETERMINE IS '판단력';
COMMENT ON COLUMN SCORE_INTERNSHIP.INTERN_COOPERATE IS '협조성';
COMMENT ON COLUMN SCORE_INTERNSHIP.INTERN_OBSERVATE IS '규율성';
COMMENT ON COLUMN SCORE_INTERNSHIP.INTERN_ACTIVE IS '적극성';
COMMENT ON COLUMN SCORE_INTERNSHIP.INTERN_RESPONSE IS '책임감';
COMMENT ON COLUMN SCORE_INTERNSHIP.INTERN_EFFICIENCY IS '효율성';
COMMENT ON COLUMN SCORE_INTERNSHIP.INTERN_CHALLENGE IS '도전의식';
COMMENT ON COLUMN SCORE_INTERNSHIP.INTERN_COMMUNITY IS '공동체';
COMMENT ON COLUMN SCORE_INTERNSHIP.INTERN_ATTITUDE IS '태도';
COMMENT ON COLUMN SCORE_INTERNSHIP.INTERN_DELIGENCY IS '성실성';
COMMENT ON COLUMN SCORE_INTERNSHIP.INTERN_ADD1 IS '추가항목1';
COMMENT ON COLUMN SCORE_INTERNSHIP.INTERN_ADD2 IS '추가항목2';
COMMENT ON COLUMN SCORE_INTERNSHIP.INTERN_ADD3 IS '추가항목3';

COMMENT ON COLUMN SCORE_INDEPTH.INDPETH_INTRO IS '자기소개';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_MOTIVE IS '지원동기';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_PROSCONS IS '장단점';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_HOBBY IS '취미';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_SPECIALTY IS '특기';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_RELIEVE IS '스트레스해소';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_ROLEMODEL IS '존경인물';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_ORG IS '조직생활';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_AGGRESS IS '공격형';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_LEADER IS '리더십';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_TEAMWORK IS '팀워크';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_CONFLICT IS '갈등해결';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_SACRIFICE IS '희생';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_ACHIVE IS '성취경험';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_WLB IS '워라벨';
COMMENT ON COLUMN SCORE_INDEPTH.INPEPTH_NIGHTSHIFT IS '야근';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_UNION IS '노조';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_STRIKE IS '파업';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_SENIOR IS '상사갈등';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_ADD1 IS '추가항목1';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_ADD2 IS '추가항목2';
COMMENT ON COLUMN SCORE_INDEPTH.INDEPTH_ADD3 IS '추가항목3';