CREATE TABLE "SEEKER" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_NICKNAME"	VARCHAR2(30)		NULL,
	"MEM_BIRTH"	DATE		NULL,
	"MEM_GENDER"	VARCHAR2(5)		NULL,
	"MEM_ZIP"	VARCHAR(20)		NULL,
	"MEM_ADDR1"	VARCHAR2(200)		NULL,
	"MEM_ADDR2"	VARCHAR2(200)		NULL,
	"MEM_EMAIL"	VARCHAR2(60)		NULL,
	"MEM_TEL"	VARCHAR2(20)		NULL,
	"MEM_CERTIFICATION"	VARCHAR2(15)		NULL,
	"MEM_CARTTOTAL"	NUMBER		NULL,
	"ATT_ID"	NUMBER		NULL,
	"MEM_SCORE"	NUMBER		NULL,
	"MEM_DATE"	DATE		NULL,
	"MEM_DELETE"	DATE		NULL,
	"SEEKER_AUTH"	VARCHAR2(10)		NULL
);

COMMENT ON COLUMN "SEEKER"."MEM_ID" IS '구직자아이디';

COMMENT ON COLUMN "SEEKER"."MEM_NICKNAME" IS '닉네임';

COMMENT ON COLUMN "SEEKER"."MEM_BIRTH" IS '생년월일';

COMMENT ON COLUMN "SEEKER"."MEM_GENDER" IS '성별';

COMMENT ON COLUMN "SEEKER"."MEM_ZIP" IS '우편번호';

COMMENT ON COLUMN "SEEKER"."MEM_ADDR1" IS '기본주소';

COMMENT ON COLUMN "SEEKER"."MEM_ADDR2" IS '상세주소';

COMMENT ON COLUMN "SEEKER"."MEM_EMAIL" IS '이메일';

COMMENT ON COLUMN "SEEKER"."MEM_TEL" IS '전화번호';

COMMENT ON COLUMN "SEEKER"."MEM_CERTIFICATION" IS '인증방식';

COMMENT ON COLUMN "SEEKER"."MEM_CARTTOTAL" IS '상품구매금액합계';

COMMENT ON COLUMN "SEEKER"."ATT_ID" IS '프로필첨부파일ID';

COMMENT ON COLUMN "SEEKER"."MEM_SCORE" IS '다면평가 점수';

COMMENT ON COLUMN "SEEKER"."MEM_DATE" IS '가입일';

COMMENT ON COLUMN "SEEKER"."MEM_DELETE" IS '탈퇴날짜';

COMMENT ON COLUMN "SEEKER"."SEEKER_AUTH" IS '권한';

CREATE TABLE "INCRUITER" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"CMP_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_EMAIL"	VARCHAR2(60)		NULL,
	"MEM_TEL"	VARCHAR2(20)		NULL,
	"MEM_ AUTH_CD"	VARCHAR2(10)		NULL,
	"MEM_APPROVAL"	VARCHAR2(10)		NULL,
	"MEM_DATE"	DATE		NULL,
	"MEM_DELETE"	DATE		NULL
);

COMMENT ON COLUMN "INCRUITER"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "INCRUITER"."CMP_ID" IS '회사아이디';

COMMENT ON COLUMN "INCRUITER"."MEM_EMAIL" IS '이메일';

COMMENT ON COLUMN "INCRUITER"."MEM_TEL" IS '전화번호';

COMMENT ON COLUMN "INCRUITER"."MEM_ AUTH_CD" IS '권한';

COMMENT ON COLUMN "INCRUITER"."MEM_APPROVAL" IS '승인여부';

COMMENT ON COLUMN "INCRUITER"."MEM_DATE" IS '가입일';

COMMENT ON COLUMN "INCRUITER"."MEM_DELETE" IS '탈퇴날짜';

CREATE TABLE "MEMBER" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_PASS"	VARCHAR2(200)		NULL,
	"MEM_NAME"	VARCHAR2(20)		NULL,
	"MEM_DELETE"	DATE		NULL,
	"MEM_USE"	VARCHAR2(3)		NULL
);

COMMENT ON COLUMN "MEMBER"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "MEMBER"."MEM_PASS" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."MEM_NAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."MEM_DELETE" IS '탈퇴날짜';

COMMENT ON COLUMN "MEMBER"."MEM_USE" IS '사용여부';

CREATE TABLE "ANNO" (
	"ANNO_ID"	VARCHAR2(20)		NOT NULL,
	"CMP_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"ANNO_TITLE"	VARCHAR2(50)		NOT NULL,
	"ANNO_CONTENT"	CLOB		NULL,
	"ANNO_STARTDATE"	DATE		NOT NULL,
	"ANNO_ENDDATE"	DATE		NOT NULL,
	"ANNO_HIT"	NUMBER	DEFAULT 0	NOT NULL,
	"ANNO_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ANNO_STATE_CD"	VARCHAR(10)	DEFAULT 0	NULL,
	"ANNO_TYPE_CD"	VARCHAR2(10)		NULL,
	"ANNO_WORKENV"	VARCHAR2(600)		NULL,
	"ANNO_PROBATION"	VARCHAR2(20)		NULL,
	"AANNO_SALARY"	VARCHAR(50)		NULL,
	"ATT_ID"	NUMBER		NULL,
	"INDUSTRY_CODE"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "ANNO"."ANNO_ID" IS '공고아이디';

COMMENT ON COLUMN "ANNO"."CMP_ID" IS '회사아이디';

COMMENT ON COLUMN "ANNO"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "ANNO"."ANNO_TITLE" IS '제목';

COMMENT ON COLUMN "ANNO"."ANNO_CONTENT" IS '내용';

COMMENT ON COLUMN "ANNO"."ANNO_STARTDATE" IS '공고시작날짜';

COMMENT ON COLUMN "ANNO"."ANNO_ENDDATE" IS '공고종료날짜';

COMMENT ON COLUMN "ANNO"."ANNO_HIT" IS '조회수';

COMMENT ON COLUMN "ANNO"."ANNO_DATE" IS '작성일';

COMMENT ON COLUMN "ANNO"."ANNO_STATE_CD" IS '공고글상태';

COMMENT ON COLUMN "ANNO"."ANNO_TYPE_CD" IS '공고타입,N: 일반채용,B: 블라인드채용';

COMMENT ON COLUMN "ANNO"."ANNO_WORKENV" IS '근무환경';

COMMENT ON COLUMN "ANNO"."ANNO_PROBATION" IS '수습기간';

COMMENT ON COLUMN "ANNO"."AANNO_SALARY" IS '연봉급여';

COMMENT ON COLUMN "ANNO"."ATT_ID" IS '공고첨부파일아이디';

COMMENT ON COLUMN "ANNO"."INDUSTRY_CODE" IS '업종코드';

CREATE TABLE "APPLY" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"DA_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"MYRESUME_ID"	VARCHAR2(20)		NOT NULL,
	"MYINTRO_ID"	VARCHAR2(20)		NOT NULL,
	"APPLY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"APPLY_UPDATE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"APPLY_DELETE_DATE"	DATE		NOT NULL,
	"APPLY_TOTAL"	NUMBER	DEFAULT 0	NULL,
	"APPLY_RESULT"	VARCHAR2(20)	DEFAULT '진행중'	NOT NULL,
	"APPLY_RESULT_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "APPLY"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "APPLY"."DA_ID" IS '세부공고아이디';

COMMENT ON COLUMN "APPLY"."MEM_ID" IS '구직자아이디';

COMMENT ON COLUMN "APPLY"."MYRESUME_ID" IS '이력서 아이디';

COMMENT ON COLUMN "APPLY"."MYINTRO_ID" IS '내 자기소개서 아이디';

COMMENT ON COLUMN "APPLY"."APPLY_DATE" IS '지원날짜';

COMMENT ON COLUMN "APPLY"."APPLY_UPDATE_DATE" IS '지원수정날짜';

COMMENT ON COLUMN "APPLY"."APPLY_DELETE_DATE" IS '지원 삭제날짜';

COMMENT ON COLUMN "APPLY"."APPLY_TOTAL" IS '지원자총점평균';

COMMENT ON COLUMN "APPLY"."APPLY_RESULT" IS '지원결과';

COMMENT ON COLUMN "APPLY"."APPLY_RESULT_DATE" IS '지원결과날짜';

CREATE TABLE "RESUME_SCORE" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"RESUME_CAREER"	NUMBER	DEFAULT 0	NULL,
	"RESUME_EDU"	NUMBER	DEFAULT 0	NULL,
	"RESUME_CERT"	NUMBER	DEFAULT 0	NULL,
	"RESUME_FACILITY"	NUMBER	DEFAULT 0	NULL,
	"RESUME_ACTIVITY"	NUMBER	DEFAULT 0	NULL,
	"RESUME_SOCIAL"	NUMBER	DEFAULT 0	NULL,
	"RESUME_AWARD"	NUMBER	DEFAULT 0	NULL,
	"RESUME_COURSE"	NUMBER	DEFAULT 0	NULL,
	"RESUME_DUTY"	NUMBER	DEFAULT 0	NULL,
	"RESUME_ADD1"	NUMBER	DEFAULT 0	NULL,
	"RESUME_ADD2"	NUMBER	DEFAULT 0	NULL,
	"RESUME_ADD3"	NUMBER	DEFAULT 0	NULL,
	"RESUME_TOTAL"	NUMBER	DEFAULT 0	NULL,
	"RESUME_SCORE_DATE"	DATE		NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "RESUME_SCORE"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_CAREER" IS '경력 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_EDU" IS '학력 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_CERT" IS '자격증 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_FACILITY" IS '기능';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_ACTIVITY" IS '주요활동 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_SOCIAL" IS '사회경험 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_AWARD" IS '수상내역 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_COURSE" IS '교육이수 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_DUTY" IS '병역사항 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_ADD1" IS '추가 입사지원 항목1 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_ADD2" IS '추가 입사지원 항목2 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_ADD3" IS '추가 입사지원 항목3 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_TOTAL" IS '입사지원서 총점';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_SCORE_DATE" IS '입사지원서 점수부여 날짜';

COMMENT ON COLUMN "RESUME_SCORE"."MEM_ID" IS '점수 부여하는 기업회원 아이디(누가 점수부여 했는지)';

CREATE TABLE "INTRODUCTION_SCORE" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"INTRO_GROWTH"	NUMBER	DEFAULT 0	NULL,
	"INTRO_PERSONALITY"	NUMBER	DEFAULT 0	NULL,
	"INTRO_SCHOOLDAY"	NUMBER	DEFAULT 0	NULL,
	"INTRO_JOB"	NUMBER	DEFAULT 0	NULL,
	"INTRO_MOTIVE"	NUMBER	DEFAULT 0	NULL,
	"INTRO_ASPIRATION"	NUMBER	DEFAULT 0	NULL,
	"INTRO_FAMILY"	NUMBER	DEFAULT 0	NULL,
	"INTRO_SUBACTIVITY"	NUMBER	DEFAULT 0	NULL,
	"INTRO_MAJOR"	NUMBER	DEFAULT 0	NULL,
	"INTRO_COURSE"	NUMBER	DEFAULT 0	NULL,
	"INTRO_OBJECTIVE"	NUMBER	DEFAULT 0	NULL,
	"INTRO_CLUB"	NUMBER	DEFAULT 0	NULL,
	"INTRO_VOLUNTEER"	NUMBER	DEFAULT 0	NULL,
	"INTRO_ADD1"	NUMBER	DEFAULT 0	NULL,
	"INTRO_ADD2"	NUMBER	DEFAULT 0	NULL,
	"INTRO_ADD3"	NUMBER	DEFAULT 0	NULL,
	"INTRO_TOTAL"	NUMBER	DEFAULT 0	NULL,
	"INTRO_SCORE_DATE"	DATE		NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "INTRODUCTION_SCORE"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_GROWTH" IS '성장과정 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_PERSONALITY" IS '성격 장단점 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_SCHOOLDAY" IS '학창시절 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_JOB" IS '직무경험';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_MOTIVE" IS '지원동기 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_ASPIRATION" IS '입사 후 포부 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_FAMILY" IS '가족소개 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_SUBACTIVITY" IS '교외활동 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_MAJOR" IS '전공선택 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_COURSE" IS '생활진로 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_OBJECTIVE" IS '희망업무 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_CLUB" IS '동아리 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_VOLUNTEER" IS '봉사활동 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_ADD1" IS '추가 자기소개 항목1 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_ADD2" IS '추가 자기소개 항목2 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_ADD3" IS '추가 자기소개 항목3 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_TOTAL" IS '자기소개서 총점';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_SCORE_DATE" IS '자기소개서 점수부여날짜';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."MEM_ID" IS '점수를 부여한 기업회원 ID';

CREATE TABLE "TEST_SCORE" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"TEST_SUBJECT1"	NUMBER	DEFAULT 0	NULL,
	"TEST_SUBJECT2"	NUMBER	DEFAULT 0	NULL,
	"TEST_SUBJECT3"	NUMBER	DEFAULT 0	NULL,
	"TEST_SUBJECT4"	NUMBER	DEFAULT 0	NULL,
	"TEST_SUBJECT5"	NUMBER	DEFAULT 0	NULL,
	"TEST_ADD1"	NUMBER	DEFAULT 0	NULL,
	"TEST_ADD2"	NUMBER	DEFAULT 0	NULL,
	"TEST_ADD3"	NUMBER	DEFAULT 0	NULL,
	"TEST_TOTAL"	NUMBER	DEFAULT 0	NULL,
	"TEST_SCORE_DATE"	DATE		NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "TEST_SCORE"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "TEST_SCORE"."TEST_SUBJECT1" IS '과목1 점수';

COMMENT ON COLUMN "TEST_SCORE"."TEST_SUBJECT2" IS '과목2 점수';

COMMENT ON COLUMN "TEST_SCORE"."TEST_SUBJECT3" IS '과목3 점수';

COMMENT ON COLUMN "TEST_SCORE"."TEST_SUBJECT4" IS '과목4 점수';

COMMENT ON COLUMN "TEST_SCORE"."TEST_SUBJECT5" IS '과목5 점수';

COMMENT ON COLUMN "TEST_SCORE"."TEST_ADD1" IS '추가 필기시험 과목1 점수';

COMMENT ON COLUMN "TEST_SCORE"."TEST_ADD2" IS '추가 필기시험 과목2 점수';

COMMENT ON COLUMN "TEST_SCORE"."TEST_ADD3" IS '추가 필기시험 과목3 점수';

COMMENT ON COLUMN "TEST_SCORE"."TEST_TOTAL" IS '필기시험 총점';

COMMENT ON COLUMN "TEST_SCORE"."TEST_SCORE_DATE" IS '필기시험 점수부여날짜';

COMMENT ON COLUMN "TEST_SCORE"."MEM_ID" IS '점수를 부여한 기업회원ID';

CREATE TABLE "COMPETENCY_SCORE" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"COMPETE_FACIAL"	NUMBER	DEFAULT 0	NULL,
	"COMPETE_POSTURE"	NUMBER	DEFAULT 0	NULL,
	"COMPETE_SPEAKING"	NUMBER	DEFAULT 0	NULL,
	"COMPETE_QUERY"	NUMBER	DEFAULT 0	NULL,
	"COMPETE_META_COG"	NUMBER	DEFAULT 0	NULL,
	"COMPETE_RECOG"	NUMBER	DEFAULT 0	NULL,
	"COMPETE_RESOLVE"	NUMBER	DEFAULT 0	NULL,
	"COMPETE_EXPRESSION"	NUMBER	DEFAULT 0	NULL,
	"COMPETE_LOGIC"	NUMBER	DEFAULT 0	NULL,
	"COMPETE_LEADER"	NUMBER	DEFAULT 0	NULL,
	"COMPETE_RELATION"	NUMBER	DEFAULT 0	NULL,
	"COMPETE_ADD1"	NUMBER	DEFAULT 0	NULL,
	"COMPETE_ADD2"	NUMBER	DEFAULT 0	NULL,
	"COMPETE_ADD3"	NUMBER	DEFAULT 0	NULL,
	"COMPETE_TOTAL"	NUMBER	DEFAULT 0	NULL,
	"COMPETE_SCORE_DATE"	DATE		NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "COMPETENCY_SCORE"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETE_FACIAL" IS '시선과 표정 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETE_POSTURE" IS '대면자세 및 행동 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETE_SPEAKING" IS '언어와 표현 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETE_QUERY" IS '질의파악능력 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETE_META_COG" IS '메타인지 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETE_RECOG" IS '상황인식능력 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETE_RESOLVE" IS '문제해경능력';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETE_EXPRESSION" IS '자기표현력 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETE_LOGIC" IS '논리력 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETE_LEADER" IS '리더십 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETE_RELATION" IS '인간관계 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETE_ADD1" IS '추가 역량평가 항목1 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETE_ADD2" IS '추가 역량평가 항목2 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETE_ADD3" IS '추가 역량평가 항목3 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETE_TOTAL" IS '역량평가 총점';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETE_SCORE_DATE" IS '역량평가 점수부여날짜';

COMMENT ON COLUMN "COMPETENCY_SCORE"."MEM_ID" IS '점수를 부여한 기업회원ID';

CREATE TABLE "PRACTICE_SCORE" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"PRACTICE_UNDERSTAND"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_APPROPRIATE"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_KNOWLEDGE"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_EXPERIENCE"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_ADD1"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_ADD2"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_ADD3"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_ADD4"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_ADD5"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_TOTAL"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_SCORE_DATE"	DATE		NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "PRACTICE_SCORE"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_UNDERSTAND" IS '직무이해도 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_APPROPRIATE" IS '직무접학성 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_KNOWLEDGE" IS '실무관련지식 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_EXPERIENCE" IS '실무경험 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_ADD1" IS '추가 실무면접 항목1 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_ADD2" IS '추가 실무면접 항목2 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_ADD3" IS '추가 실무면접 항목3 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_ADD4" IS '추가 실무면접 항목4 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_ADD5" IS '추가 실무면접 항목5 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_TOTAL" IS '실무면접 총점';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_SCORE_DATE" IS '실무면접 점수부여날짜';

COMMENT ON COLUMN "PRACTICE_SCORE"."MEM_ID" IS '점수를 부여한 기업회원ID';

CREATE TABLE "DISCUSS_SCORE" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"DISCUSS_POSTURE"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_SUBJECT"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_PROBLEM"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_RESOLVE"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_QUERY"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_PROGRESS"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_ADD1"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_ADD2"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_ADD3"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_TOTAL"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_SCORE_DATE"	DATE		NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "DISCUSS_SCORE"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_POSTURE" IS '토론자세 점수';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_SUBJECT" IS '주제파악 점수';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_PROBLEM" IS '문제파악 점수';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_RESOLVE" IS '해결방안 점수';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_QUERY" IS '질의파악능력';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_PROGRESS" IS '토론진행 점수';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_ADD1" IS '토론 추가항목1 점수';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_ADD2" IS '토론 추가항목2 점수';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_ADD3" IS '토론 추가항목3 점수';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_TOTAL" IS '토론면접 총점';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_SCORE_DATE" IS '토론면접 점수부여날짜';

COMMENT ON COLUMN "DISCUSS_SCORE"."MEM_ID" IS '점수를 부여한 기업회원ID';

CREATE TABLE "INTERNSHIP_SCORE" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"INTERN_ACHIVE"	NUMBER	DEFAULT 0	NULL,
	"INTERN_TRUST"	NUMBER	DEFAULT 0	NULL,
	"INTERN_CREATIVITY"	NUMBER	DEFAULT 0	NULL,
	"INTERN_KNOW"	NUMBER	DEFAULT 0	NULL,
	"INTERN_DETERMINE"	NUMBER	DEFAULT 0	NULL,
	"INTERN_COOPERATE"	NUMBER	DEFAULT 0	NULL,
	"INTERN_OBSERVATE"	NUMBER	DEFAULT 0	NULL,
	"INTERN_ACTIVE"	NUMBER	DEFAULT 0	NULL,
	"INTERN_RESPONSE"	NUMBER	DEFAULT 0	NULL,
	"INTERN_EFFICIENCY"	NUMBER	DEFAULT 0	NULL,
	"INTERN_CHALLENGE"	NUMBER	DEFAULT 0	NULL,
	"INTERN_COMMUNITY"	NUMBER	DEFAULT 0	NULL,
	"INTERN_ATTITUDE"	NUMBER	DEFAULT 0	NULL,
	"INTERN_DELIGENCY"	NUMBER	DEFAULT 0	NULL,
	"INTERN_ADD1"	NUMBER	DEFAULT 0	NULL,
	"INTERN_ADD2"	NUMBER	DEFAULT 0	NULL,
	"INTERN_ADD3"	NUMBER	DEFAULT 0	NULL,
	"INTERN_TOTAL"	NUMBER	DEFAULT 0	NULL,
	"INTERN_SCORE_DATE"	DATE		NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "INTERNSHIP_SCORE"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_ACHIVE" IS '업무달성도';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_TRUST" IS '업무신뢰도 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_CREATIVITY" IS '창의력 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_KNOW" IS '직무지식';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_DETERMINE" IS '판단력';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_COOPERATE" IS '협조성 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_OBSERVATE" IS '규율성';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_ACTIVE" IS '적극성 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_RESPONSE" IS '책임감 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_EFFICIENCY" IS '효율성 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_CHALLENGE" IS '도전의식';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_COMMUNITY" IS '공동체 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_ATTITUDE" IS '태도 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_DELIGENCY" IS '성실성 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_ADD1" IS '추가 인턴십 항목1 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_ADD2" IS '추가 인턴십 항목2 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_ADD3" IS '추가 인턴십 항목3 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_TOTAL" IS '인턴십 총점';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_SCORE_DATE" IS '인턴십 점수부여날짜';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."MEM_ID" IS '점수를 부여한 기업회원ID';

CREATE TABLE "INDEPTH_INTERVIEW_SCORE" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"INDPETH_INTRO"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_MOTIVE"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_PROSCONS"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_HOBBY"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_SPECIALTY"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_RELIEVE"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_ROLEMODEL"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_ORG"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_AGGRESS"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_LEADER"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_TEAMWORK"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_CONFLICT"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_SACRIFICE"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_ACHIVE"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_WLB"	NUMBER	DEFAULT 0	NULL,
	"INPEPTH_NIGHTSHIFT"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_UNION"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_STRIKE"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_SENIOR"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_ADD1"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_ADD2"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_ADD3"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_TOTAL"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_SCORE_DATE"	DATE		NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDPETH_INTRO" IS '자기소개 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_MOTIVE" IS '회사지원동기 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_PROSCONS" IS '장단점';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_HOBBY" IS '취미 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_SPECIALTY" IS '특기 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_RELIEVE" IS '스트레스해소 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_ROLEMODEL" IS '존경인물 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_ORG" IS '조직생활 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_AGGRESS" IS '공격형 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_LEADER" IS '리더십 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_TEAMWORK" IS '팀워크 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_CONFLICT" IS '갈등해결 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_SACRIFICE" IS '희생';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_ACHIVE" IS '성취경험 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_WLB" IS '워라밸 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INPEPTH_NIGHTSHIFT" IS '야근 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_UNION" IS '노조 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_STRIKE" IS '파업 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_SENIOR" IS '상사갈등 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_ADD1" IS '추가 임원면접 항목1 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_ADD2" IS '추가 임원면접 항목2 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_ADD3" IS '추가 임원면접 항목3 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_TOTAL" IS '임원면접 총점';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_SCORE_DATE" IS '임원면접 점수부여날짜';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."MEM_ID" IS '점수를 부여한 기업회원ID';

CREATE TABLE "ITEM" (
	"DA_ID"	VARCHAR2(20)		NOT NULL,
	"ITEM_CODE_ID2"	VARCHAR2(20)		NOT NULL,
	"ITEM_ASK"	VARCHAR2(200)		NOT NULL
);

COMMENT ON COLUMN "ITEM"."DA_ID" IS '세부공고아이디';

COMMENT ON COLUMN "ITEM"."ITEM_CODE_ID2" IS '항목코드';

COMMENT ON COLUMN "ITEM"."ITEM_ASK" IS '질문';

CREATE TABLE "PROCESS_CODE" (
	"PROCESS_CODE_ID"	VARCHAR2(20)		NOT NULL,
	"PROCESS_CODE_NAME"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "PROCESS_CODE"."PROCESS_CODE_ID" IS '분류코드';

COMMENT ON COLUMN "PROCESS_CODE"."PROCESS_CODE_NAME" IS '채용과정명';

CREATE TABLE "CAREER" (
	"CAREER_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"CAREER_CATEGORY"	VARCHAR2(30)	DEFAULT '자유분야'	NULL,
	"CARRER_COMPANY"	VARCHAR2(50)	DEFAULT '프리랜서'	NOT NULL,
	"CARRER_TASK"	VARCHAR2(50)		NULL,
	"CAREER_CLASS"	VARCHAR2(20)		NULL,
	"CAREER_JOIN"	DATE		NULL,
	"CAREER_RESIGN"	DATE		NULL,
	"CAREER_SALARY"	NUMBER	DEFAULT 0	NULL,
	"CAREER_ANNUAL"	NUMBER	DEFAULT 0	NULL,
	"CAREER_INSERT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CAREER_DELETE_DATE"	DATE		NULL,
	"ATT_ID"	NUMBER		NULL
);

COMMENT ON COLUMN "CAREER"."CAREER_ID" IS '경력아이디';

COMMENT ON COLUMN "CAREER"."MEM_ID" IS '구직자아이디';

COMMENT ON COLUMN "CAREER"."CAREER_CATEGORY" IS '업종';

COMMENT ON COLUMN "CAREER"."CARRER_COMPANY" IS '직장명';

COMMENT ON COLUMN "CAREER"."CARRER_TASK" IS '직무';

COMMENT ON COLUMN "CAREER"."CAREER_CLASS" IS '직급';

COMMENT ON COLUMN "CAREER"."CAREER_JOIN" IS '입사일';

COMMENT ON COLUMN "CAREER"."CAREER_RESIGN" IS '퇴사일';

COMMENT ON COLUMN "CAREER"."CAREER_SALARY" IS '연봉';

COMMENT ON COLUMN "CAREER"."CAREER_ANNUAL" IS '연차';

COMMENT ON COLUMN "CAREER"."CAREER_INSERT_DATE" IS '경력 작성날짜';

COMMENT ON COLUMN "CAREER"."CAREER_DELETE_DATE" IS '경력 삭제날짜';

COMMENT ON COLUMN "CAREER"."ATT_ID" IS '첨부파일아이디';

CREATE TABLE "EDUCATION" (
	"EDU_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"EDU_NAME"	VARCHAR2(50)		NULL,
	"EDU_DEPARTMENT"	VARCHAR2(50)		NOT NULL,
	"EDU_MAJOR"	VARCHAR2(50)		NOT NULL,
	"EDU_ENTERED"	DATE		NULL,
	"EDU_GRADUATE"	DATE		NOT NULL,
	"EDU_STATUS"	VARCHAR2(20)	DEFAULT '재학중'	NULL,
	"EDU_SCORE"	NUMBER	DEFAULT 0	NOT NULL,
	"EDU_STANDARD"	NUMBER	DEFAULT 0	NOT NULL,
	"EDU_INSERT_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"EDU_DELETE_DATE"	DATE		NULL,
	"ATT_ID"	NUMBER		NULL
);

COMMENT ON COLUMN "EDUCATION"."EDU_ID" IS '학력아이디';

COMMENT ON COLUMN "EDUCATION"."MEM_ID" IS '구직자아이디';

COMMENT ON COLUMN "EDUCATION"."EDU_NAME" IS '학교명';

COMMENT ON COLUMN "EDUCATION"."EDU_DEPARTMENT" IS '학과명';

COMMENT ON COLUMN "EDUCATION"."EDU_MAJOR" IS '전공';

COMMENT ON COLUMN "EDUCATION"."EDU_ENTERED" IS '입학일';

COMMENT ON COLUMN "EDUCATION"."EDU_GRADUATE" IS '졸업일,중퇴일,자퇴일';

COMMENT ON COLUMN "EDUCATION"."EDU_STATUS" IS '상태';

COMMENT ON COLUMN "EDUCATION"."EDU_SCORE" IS '학점';

COMMENT ON COLUMN "EDUCATION"."EDU_STANDARD" IS '기준학점';

COMMENT ON COLUMN "EDUCATION"."EDU_INSERT_DATE" IS '작성날짜';

COMMENT ON COLUMN "EDUCATION"."EDU_DELETE_DATE" IS '학력  삭제날짜';

COMMENT ON COLUMN "EDUCATION"."ATT_ID" IS '첨부파일아이디';

CREATE TABLE "CERTIFICATION" (
	"CERT_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"CERT_NO"	VARCHAR2(30)		NOT NULL,
	"CERT_NAME"	VARCHAR2(50)		NOT NULL,
	"CERT_DATE"	DATE		NOT NULL,
	"CERT_INSTITUTION"	VARCHAR2(50)		NOT NULL,
	"CERT_INSERT_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"CERT_DELETE_DATE"	DATE		NULL,
	"ATT_ID"	NUMBER		NULL
);

COMMENT ON COLUMN "CERTIFICATION"."CERT_ID" IS '자격증아이디';

COMMENT ON COLUMN "CERTIFICATION"."MEM_ID" IS '구직자아이디';

COMMENT ON COLUMN "CERTIFICATION"."CERT_NO" IS '자격번호';

COMMENT ON COLUMN "CERTIFICATION"."CERT_NAME" IS '자격증명';

COMMENT ON COLUMN "CERTIFICATION"."CERT_DATE" IS '발급일';

COMMENT ON COLUMN "CERTIFICATION"."CERT_INSTITUTION" IS '시행부처';

COMMENT ON COLUMN "CERTIFICATION"."CERT_INSERT_DATE" IS '자격증 작성날짜';

COMMENT ON COLUMN "CERTIFICATION"."CERT_DELETE_DATE" IS '자격증 삭제날짜';

COMMENT ON COLUMN "CERTIFICATION"."ATT_ID" IS '첨부파일아이디';

CREATE TABLE "MYINTRODUCTION" (
	"MYINTRO_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"MYINTRO_GROWTH"	VARCHAR2(2000)		NULL,
	"MYINTRO_PERSONALITY"	VARCHAR2(2000)		NULL,
	"MYINTRO_SCHOOLDAY"	VARCHAR2(2000)		NULL,
	"MYINTRO_JOB"	VARCHAR2(2000)		NULL,
	"MYINTRO_MOTIVE"	VARCHAR2(2000)		NULL,
	"MYINTRO_ASPIRATION"	VARCHAR2(2000)		NULL,
	"MYINTRO_FAMILY"	VARCHAR2(2000)		NULL,
	"MYINTRO_SUBACTIVITY"	VARCHAR2(2000)		NULL,
	"MYINTRO_MAJOR"	VARCHAR2(2000)		NULL,
	"MYINTRO_COURSE"	VARCHAR2(2000)		NULL,
	"MYINTRO_OBJECTIVE"	VARCHAR2(2000)		NULL,
	"MYINTRO_CLUB"	VARCHAR2(2000)		NULL,
	"MYINTRO_VOLUNTEER"	VARCHAR2(2000)		NULL,
	"MYINTRO_ADD1"	VARCHAR2(2000)		NULL,
	"MYINTRO_ADD2"	VARCHAR2(2000)		NULL,
	"MYINTRO_ADD3"	VARCHAR2(2000)		NULL,
	"MYINTRO_INSERT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MYINTRO_DELETE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_ID" IS '내 자기소개서 아이디';

COMMENT ON COLUMN "MYINTRODUCTION"."MEM_ID" IS '내 아이디';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_GROWTH" IS '내 성장과정';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_PERSONALITY" IS '내 성격 장단점';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_SCHOOLDAY" IS '내 학창시절';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_JOB" IS '내 직무경험';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_MOTIVE" IS '내 지원동기';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_ASPIRATION" IS '내 입사 후 포부';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_FAMILY" IS '내 가족소개';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_SUBACTIVITY" IS '내 교외활동';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_MAJOR" IS '내 전공선택';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_COURSE" IS '생활진로';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_OBJECTIVE" IS '내 희망업무';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_CLUB" IS '내 동아리';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_VOLUNTEER" IS '내 봉사활동';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_ADD1" IS '내 추가항목1';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_ADD2" IS '내 추가항목2';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_ADD3" IS '내 추가항목3';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_INSERT_DATE" IS '내 자기소개서 작성날짜';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_DELETE_DATE" IS '내 자기소개서 삭제날짜';

CREATE TABLE "FACILITY" (
	"FACILITY_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"FACILITY_NAME"	VARCHAR2(50)		NOT NULL,
	"FACILITY_CATEGORY"	VARCHAR2(50)		NOT NULL,
	"FACILITY_LEVEL"	VARCHAR2(30)	DEFAULT '초급'	NOT NULL,
	"FACILITY_GETDATE"	DATE		NOT NULL,
	"FACILITY_PERIOD"	NUMBER	DEFAULT 0	NOT NULL,
	"FACILITY_INSERT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"FACILITY_DELETE_DATE"	DATE		NULL,
	"ATT_ID"	NUMBER		NULL
);

COMMENT ON COLUMN "FACILITY"."FACILITY_ID" IS '기능아이디';

COMMENT ON COLUMN "FACILITY"."MEM_ID" IS '구직자아이디';

COMMENT ON COLUMN "FACILITY"."FACILITY_NAME" IS '기능명';

COMMENT ON COLUMN "FACILITY"."FACILITY_CATEGORY" IS '기능종류';

COMMENT ON COLUMN "FACILITY"."FACILITY_LEVEL" IS '수준';

COMMENT ON COLUMN "FACILITY"."FACILITY_GETDATE" IS '취득일';

COMMENT ON COLUMN "FACILITY"."FACILITY_PERIOD" IS '훈련기간';

COMMENT ON COLUMN "FACILITY"."FACILITY_INSERT_DATE" IS '기능 작성날짜';

COMMENT ON COLUMN "FACILITY"."FACILITY_DELETE_DATE" IS '기능 삭제 날짜';

COMMENT ON COLUMN "FACILITY"."ATT_ID" IS '첨부파일아이디';

CREATE TABLE "ACTIVITY" (
	"ACT_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"ACT_NAME"	VARCHAR2(50)		NOT NULL,
	"ACT_CATEGORY"	VARCHAR2(50)		NOT NULL,
	"ACT_INSTITUTION"	VARCHAR2(50)		NULL,
	"ACT_PERIOD"	NUMBER	DEFAULT 0	NOT NULL,
	"ACT_INSERT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ACT_DELETE_DATE"	DATE		NULL,
	"ATT_ID"	NUMBER		NULL
);

COMMENT ON COLUMN "ACTIVITY"."ACT_ID" IS '주요활동아이디';

COMMENT ON COLUMN "ACTIVITY"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "ACTIVITY"."ACT_NAME" IS '주요활동명';

COMMENT ON COLUMN "ACTIVITY"."ACT_CATEGORY" IS '주요활동종류';

COMMENT ON COLUMN "ACTIVITY"."ACT_INSTITUTION" IS '주요활동기관';

COMMENT ON COLUMN "ACTIVITY"."ACT_PERIOD" IS '주요활동기간';

COMMENT ON COLUMN "ACTIVITY"."ACT_INSERT_DATE" IS '주요활동 작성날짜';

COMMENT ON COLUMN "ACTIVITY"."ACT_DELETE_DATE" IS '주요활동 삭제날짜';

COMMENT ON COLUMN "ACTIVITY"."ATT_ID" IS '첨부파일아이디';

CREATE TABLE "AWARD" (
	"AWARD_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"AWARD_COMPETITION"	VARCHAR2(50)		NOT NULL,
	"AWARD_NAME"	VARCHAR2(50)		NOT NULL,
	"AWARD_CATEGORY"	VARCHAR2(50)		NOT NULL,
	"AWARD_DATE"	DATE		NOT NULL,
	"AWARD_INSTITUTION"	VARCHAR2(50)		NOT NULL,
	"AWARD_INSERT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"AWARD_DELETE_DATE"	DATE		NULL,
	"ATT_ID"	NUMBER		NULL
);

COMMENT ON COLUMN "AWARD"."AWARD_ID" IS '수상내역아이디';

COMMENT ON COLUMN "AWARD"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "AWARD"."AWARD_COMPETITION" IS '수상대회명';

COMMENT ON COLUMN "AWARD"."AWARD_NAME" IS '수상명';

COMMENT ON COLUMN "AWARD"."AWARD_CATEGORY" IS '수상대회종류';

COMMENT ON COLUMN "AWARD"."AWARD_DATE" IS '수상날짜';

COMMENT ON COLUMN "AWARD"."AWARD_INSTITUTION" IS '수상기관';

COMMENT ON COLUMN "AWARD"."AWARD_INSERT_DATE" IS '수상내역 작성날짜';

COMMENT ON COLUMN "AWARD"."AWARD_DELETE_DATE" IS '수상내역 삭제날짜';

COMMENT ON COLUMN "AWARD"."ATT_ID" IS '첨부파일아이디';

CREATE TABLE "COURSE" (
	"COURSE_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"COURSE_NAME"	VARCHAR2(50)		NOT NULL,
	"COURSE_CATEGORY"	VARCHAR2(30)		NOT NULL,
	"COURSE_INSTITUTION"	VARCHAR2(50)		NOT NULL,
	"COURSE_PERIOD"	NUMBER	DEFAULT 0	NOT NULL,
	"COURSE_INSERT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COURSE_DELETE_DATE"	DATE		NULL,
	"ATT_ID"	NUMBER		NULL
);

COMMENT ON COLUMN "COURSE"."COURSE_ID" IS '교육이수아이디';

COMMENT ON COLUMN "COURSE"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "COURSE"."COURSE_NAME" IS '교육명';

COMMENT ON COLUMN "COURSE"."COURSE_CATEGORY" IS '교육종류';

COMMENT ON COLUMN "COURSE"."COURSE_INSTITUTION" IS '교육기관';

COMMENT ON COLUMN "COURSE"."COURSE_PERIOD" IS '교육기간';

COMMENT ON COLUMN "COURSE"."COURSE_INSERT_DATE" IS '교육이수 작성날짜';

COMMENT ON COLUMN "COURSE"."COURSE_DELETE_DATE" IS '교육이수 삭제날짜';

COMMENT ON COLUMN "COURSE"."ATT_ID" IS '첨부파일아이디';

CREATE TABLE "REVIEW" (
	"REVIEW_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"REVIEW_TITLE"	VARCHAR2(50)		NOT NULL,
	"REVIEW_CONTENT"	VARCHAR2(1000)		NULL,
	"REVIEW_DATE"	DATE		NULL,
	"ATT_ID"	NUMBER		NULL,
	"REVIEW_SCORE"	NUMBER(1)	DEFAULT 1	NULL,
	"COMPANY_ID"	VARCHAR2(20)		NOT NULL,
	"REVIEW_CHECK"	VARCHAR(1)	DEFAULT 0	NULL
);

COMMENT ON COLUMN "REVIEW"."REVIEW_ID" IS '리뷰아이디';

COMMENT ON COLUMN "REVIEW"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "REVIEW"."REVIEW_TITLE" IS '리뷰제목';

COMMENT ON COLUMN "REVIEW"."REVIEW_CONTENT" IS '리뷰내용';

COMMENT ON COLUMN "REVIEW"."REVIEW_DATE" IS '리뷰날짜';

COMMENT ON COLUMN "REVIEW"."ATT_ID" IS '리뷰첨부파일';

COMMENT ON COLUMN "REVIEW"."REVIEW_SCORE" IS '리뷰별점';

COMMENT ON COLUMN "REVIEW"."REVIEW_CHECK" IS '리뷰승인여부';

CREATE TABLE "CUT" (
	"CUT_ID"	VARCHAR2(20)		NOT NULL,
	"CUT_DATE"	DATE		NULL,
	"CUT_CONTENT"	VARCHAR2(1000)		NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"CUT_CHECK"	VARCHAR(1)	DEFAULT 0	NULL
);

COMMENT ON COLUMN "CUT"."CUT_ID" IS '차단아이디';

COMMENT ON COLUMN "CUT"."CUT_DATE" IS '차단일자';

COMMENT ON COLUMN "CUT"."CUT_CONTENT" IS '차단사유';

COMMENT ON COLUMN "CUT"."MEM_ID" IS '차단당한회원아이디';

COMMENT ON COLUMN "CUT"."CUT_CHECK" IS '차단만료여부';

CREATE TABLE "BLACKLIST" (
	"BLACKLIST_ID"	VARCHAR2(20)		NOT NULL,
	"BLACKLIST_DATE"	DATE		NULL,
	"BLACKLIST_CONTENT"	VARCHAR2(1000)		NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"BLACKLIST_CHECK"	VARCHAR(1)	DEFAULT 0	NULL
);

COMMENT ON COLUMN "BLACKLIST"."BLACKLIST_ID" IS '블랙리스트아이디';

COMMENT ON COLUMN "BLACKLIST"."BLACKLIST_DATE" IS '블랙리스트된 날짜';

COMMENT ON COLUMN "BLACKLIST"."BLACKLIST_CONTENT" IS '블랙리스트 사유';

COMMENT ON COLUMN "BLACKLIST"."MEM_ID" IS '블랙당한회원아이디';

COMMENT ON COLUMN "BLACKLIST"."BLACKLIST_CHECK" IS '블랙만료여부';

CREATE TABLE "COMPANY" (
	"CMP_ID"	VARCHAR2(20)		NOT NULL,
	"CMP_NO"	VARCHAR2(20)		NOT NULL,
	"CMP_NAME"	VARCHAR2(100)		NOT NULL,
	"CMP_REP_NAME"	VARCHAR2(20)		NOT NULL,
	"CMP_BSNS_NO"	VARCHAR2(20)		NOT NULL,
	"CMP_ADDR1"	VARCHAR2(100)		NOT NULL,
	"CMP_ADDR2"	VARCHAR2(100)		NOT NULL,
	"CMP_ZIP"	VARCHAR2(20)		NOT NULL,
	"CMP_PHONE"	VARCHAR2(20)		NOT NULL,
	"CMP_EMAIL"	VARCHAR2(200)		NULL,
	"CMP_URL"	VARCHAR2(200)		NULL,
	"CMP_ESTBL_DATE"	DATE		NOT NULL,
	"CMP_SMENP"	VARCHAR2(20)		NOT NULL,
	"CMP_EMP_NO"	VARCHAR2(100)		NULL,
	"CMP_AVR_WORK"	VARCHAR2(100)		NULL,
	"CMP_AVR_SALARY"	VARCHAR2(100)		NULL,
	"CMP_MB_NAME"	VARCHAR2(100)		NOT NULL,
	"CMP_CHECK"	NUMBER(1)	DEFAULT 0	NULL,
	"CMP_CONTENT"	CLOB		NULL,
	"CMP_LOGO"	NUMBER		NULL,
	"ATT_ID"	NUMBER		NULL
);

COMMENT ON COLUMN "COMPANY"."CMP_ID" IS '회사아이디';

COMMENT ON COLUMN "COMPANY"."CMP_NO" IS '법인등록번호';

COMMENT ON COLUMN "COMPANY"."CMP_NAME" IS '법인명';

COMMENT ON COLUMN "COMPANY"."CMP_REP_NAME" IS '회사대표자성명';

COMMENT ON COLUMN "COMPANY"."CMP_BSNS_NO" IS '사업자등록번호';

COMMENT ON COLUMN "COMPANY"."CMP_ADDR1" IS '회사기본주소';

COMMENT ON COLUMN "COMPANY"."CMP_ADDR2" IS '회사상세주소';

COMMENT ON COLUMN "COMPANY"."CMP_ZIP" IS '회사우편번호';

COMMENT ON COLUMN "COMPANY"."CMP_PHONE" IS '회사전화번호';

COMMENT ON COLUMN "COMPANY"."CMP_ESTBL_DATE" IS '회사설립일자';

COMMENT ON COLUMN "COMPANY"."CMP_SMENP" IS '회사형태';

COMMENT ON COLUMN "COMPANY"."CMP_EMP_NO" IS '회사종업원수';

COMMENT ON COLUMN "COMPANY"."CMP_AVR_WORK" IS '종업원평균근속기간내용';

COMMENT ON COLUMN "COMPANY"."CMP_AVR_SALARY" IS '회사1인평균급여금액';

COMMENT ON COLUMN "COMPANY"."CMP_MB_NAME" IS '회사주요사업명';

COMMENT ON COLUMN "COMPANY"."CMP_CHECK" IS '승인여부';

COMMENT ON COLUMN "COMPANY"."CMP_CONTENT" IS '기업소개';

COMMENT ON COLUMN "COMPANY"."CMP_LOGO" IS '회사로고';

COMMENT ON COLUMN "COMPANY"."ATT_ID" IS '첨부파일아이디
기업이미지';

CREATE TABLE "BOARD_REPORT" (
	"BOARD_RPT_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"BOARD_RPT_NO"	VARCHAR2(20)		NOT NULL,
	"BOARD_RPT_DATE"	DATE		NULL,
	"BOARD_RPT_REASON"	VARCHAR2(1000)		NULL,
	"BOARD_RPT_CHECK"	NUMBER(1)	DEFAULT 0	NULL
);

COMMENT ON COLUMN "BOARD_REPORT"."BOARD_RPT_ID" IS '게시판신고아이디';

COMMENT ON COLUMN "BOARD_REPORT"."BOARD_RPT_NO" IS '게시판신고글번호';

COMMENT ON COLUMN "BOARD_REPORT"."BOARD_RPT_DATE" IS '신고일자';

COMMENT ON COLUMN "BOARD_REPORT"."BOARD_RPT_REASON" IS '신고사유';

COMMENT ON COLUMN "BOARD_REPORT"."BOARD_RPT_CHECK" IS '처리상태';

CREATE TABLE "COMMENT_REPORT" (
	"COMM_RPT_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"COMM_RPT_DATE"	DATE		NULL,
	"COMM_RPT_REASON"	VARCHAR2(1000)		NULL,
	"COMM_ID"	VARCHAR2(20)		NOT NULL,
	"COMM_RPT_CHECK"	NUMBER(1)	DEFAULT 0	NULL
);

COMMENT ON COLUMN "COMMENT_REPORT"."COMM_RPT_ID" IS '댓글신고아이디';

COMMENT ON COLUMN "COMMENT_REPORT"."MEM_ID" IS '신고한회원아이디';

COMMENT ON COLUMN "COMMENT_REPORT"."COMM_RPT_DATE" IS '신고일자';

COMMENT ON COLUMN "COMMENT_REPORT"."COMM_RPT_REASON" IS '신고사유';

COMMENT ON COLUMN "COMMENT_REPORT"."COMM_ID" IS '댓글ID';

COMMENT ON COLUMN "COMMENT_REPORT"."COMM_RPT_CHECK" IS '처리상태';

CREATE TABLE "ALRAM" (
	"ALRAM_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"ALRAM_CONTENT"	VARCHAR2(500)		NOT NULL,
	"ALRAM_DATE"	DATE		NULL,
	"ALRAM_STATUS"	VARCHAR(1)	DEFAULT 0	NULL,
	"ALRAM_CATEGORY"	VARCHAR(10)		NULL
);

COMMENT ON COLUMN "ALRAM"."ALRAM_ID" IS '알림아이디';

COMMENT ON COLUMN "ALRAM"."MEM_ID" IS '알림받은회원아이디';

COMMENT ON COLUMN "ALRAM"."ALRAM_CONTENT" IS '알림내역';

COMMENT ON COLUMN "ALRAM"."ALRAM_DATE" IS '알림날짜';

COMMENT ON COLUMN "ALRAM"."ALRAM_STATUS" IS '알림읽기여부';

CREATE TABLE "HELP" (
	"HELP_ID"	VARCHAR2(20)		NOT NULL,
	"HELP_SORT"	VARCHAR2(12)		NOT NULL,
	"HELP_CATE"	VARCHAR2(60)		NULL,
	"HELP_TITLE"	VARCHAR2(100)		NOT NULL,
	"HELP_CONTENT"	CLOB		NOT NULL,
	"HELP_DATE"	DATE		NULL,
	"HELP_MODI_DATE"	DATE		NULL
);

COMMENT ON COLUMN "HELP"."HELP_ID" IS '도움말ID';

COMMENT ON COLUMN "HELP"."HELP_SORT" IS '구분';

COMMENT ON COLUMN "HELP"."HELP_CATE" IS '분류명';

COMMENT ON COLUMN "HELP"."HELP_TITLE" IS '제목';

COMMENT ON COLUMN "HELP"."HELP_CONTENT" IS '내용';

COMMENT ON COLUMN "HELP"."HELP_DATE" IS '작성일';

COMMENT ON COLUMN "HELP"."HELP_MODI_DATE" IS '수정일';

CREATE TABLE "NEWS" (
	"NEWS_NO"	VARCHAR2(20)		NOT NULL,
	"NEWS_NAME"	VARCHAR2(50)		NOT NULL,
	"NEWS_DATE"	DATE		NOT NULL,
	"NEWS_FIELD"	VARCHAR2(50)		NULL,
	"NEWS_HIT"	NUMBER		NULL,
	"NEWS_CONTENT"	VARCHAR2(500)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"NEWS_IMG"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "NEWS"."NEWS_NO" IS '뉴스 번호';

COMMENT ON COLUMN "NEWS"."NEWS_NAME" IS '제목';

COMMENT ON COLUMN "NEWS"."NEWS_DATE" IS '작성일';

COMMENT ON COLUMN "NEWS"."NEWS_FIELD" IS '분야';

COMMENT ON COLUMN "NEWS"."NEWS_HIT" IS '조회수';

COMMENT ON COLUMN "NEWS"."NEWS_CONTENT" IS '내용';

COMMENT ON COLUMN "NEWS"."MEM_ID" IS '회원아이디';

CREATE TABLE "CONTEST" (
	"CONT_NO"	VARCHAR2(20)		NOT NULL,
	"CONT_NAME"	VARCHAR2(50)		NOT NULL,
	"CONT_CO"	VARCHAR2(50)		NOT NULL,
	"CONT_START"	VARCHAR2(20)		NOT NULL,
	"CONT_DEAD"	VARCHAR2(20)		NOT NULL,
	"CONT_FIELD"	VARCHAR2(50)		NULL,
	"CONT_IMG"	VARCHAR2(100)		NULL,
	"CONT_CONTENT"	VARCHAR2(500)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "CONTEST"."CONT_NO" IS '공모전 번호';

COMMENT ON COLUMN "CONTEST"."CONT_NAME" IS '공모전명';

COMMENT ON COLUMN "CONTEST"."CONT_CO" IS '주관 기관';

COMMENT ON COLUMN "CONTEST"."CONT_START" IS '시작일';

COMMENT ON COLUMN "CONTEST"."CONT_DEAD" IS '마감일';

COMMENT ON COLUMN "CONTEST"."CONT_FIELD" IS '공모분야';

COMMENT ON COLUMN "CONTEST"."CONT_IMG" IS '사진';

COMMENT ON COLUMN "CONTEST"."CONT_CONTENT" IS '내용';

COMMENT ON COLUMN "CONTEST"."MEM_ID" IS '회원아이디';

CREATE TABLE "NOTICE" (
	"NOTICE_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"NOTICE_SORT"	VARCHAR2(15)	DEFAULT '전체'	NULL,
	"NOTICE_TITLE"	VARCHAR2(100)		NOT NULL,
	"NOTICE_CONTENT"	CLOB		NOT NULL,
	"NOTICE_DATE"	DATE		NULL,
	"NOTICE_HIT"	NUMBER(5,0)		NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_ID" IS '공지사항ID';

COMMENT ON COLUMN "NOTICE"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "NOTICE"."NOTICE_SORT" IS '구분';

COMMENT ON COLUMN "NOTICE"."NOTICE_TITLE" IS '제목';

COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT" IS '내용';

COMMENT ON COLUMN "NOTICE"."NOTICE_DATE" IS '작성일';

COMMENT ON COLUMN "NOTICE"."NOTICE_HIT" IS '조회수';

CREATE TABLE "EXPROD" (
	"EXPROD_ID"	VARCHAR2(20)		NOT NULL,
	"EXPROD_START"	DATE		NULL,
	"EXPROD_END"	DATE		NULL,
	"EXPROD_TARGET"	VARCHAR2(30)		NULL,
	"EXPROD_NAME"	VARCHAR2(100)		NULL,
	"EXPROD_PRICE"	NUMBER		NULL,
	"EXPROD_WAY"	VARCHAR2(100)		NULL,
	"EXPROD_TIME"	DATE		NULL,
	"EXPROD_DETAIL"	VARCHAR2(2000)		NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"EXPROD_APROVAL"	VARCHAR(1)		NULL,
	"EXLPROD_ID"	VARCHAR2(20)		NOT NULL,
	"ATT_ID"	NUMBER		NULL
);

CREATE TABLE "COMMENT" (
	"COMM_ID"	VARCHAR2(20)		NOT NULL,
	"BOARD_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"REF_COMM"	VARCHAR2(20)		NOT NULL,
	"COMM_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"COMM_DATE"	DATE		NOT NULL,
	"TOTAL_COMM"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"GOOD_COMM"	NUMBER(5)	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "COMMENT"."COMM_ID" IS '댓글ID';

COMMENT ON COLUMN "COMMENT"."BOARD_ID" IS '게시판ID';

COMMENT ON COLUMN "COMMENT"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "COMMENT"."REF_COMM" IS '상위댓글ID';

COMMENT ON COLUMN "COMMENT"."COMM_CONTENT" IS '댓글내용';

COMMENT ON COLUMN "COMMENT"."COMM_DATE" IS '작성일';

COMMENT ON COLUMN "COMMENT"."TOTAL_COMM" IS '댓글수';

COMMENT ON COLUMN "COMMENT"."GOOD_COMM" IS '댓글공감수';

CREATE TABLE "EXCART" (
	"EXCART_ID"	VARCHAR2(20)		NOT NULL,
	"EXPROD_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"EXCART_PRICE"	NUMBER		NULL
);

CREATE TABLE "EXPERT" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"EXPERT_APPROVAL"	NUMBER		NULL,
	"EXPERT_APPROVAL_DATE"	DATE		NULL,
	"EXPERT_INTRODUCTION"	VARCHAR2(200)		NULL,
	"EXPERT_JOINPATH"	VARCHAR2(30)		NULL,
	"EXPERT_FILED"	VARCHAR2(10)		NULL,
	"EXPERT_TAG"	VARCHAR2(40)		NULL,
	"EXPERT_ZIP"	VARCHAR2(20)		NULL,
	"EXPERT_ADDR"	VARCHAR2(200)		NULL,
	"EXPERT_ADDR2"	VARCHAR2(100)		NULL,
	"EXPERT_TEL"	VARCHAR2(20)		NULL,
	"EXPERT_EMAIL"	VARCHAR2(30)		NULL,
	"EXPERT_BANK"	VARCHAR2(20)		NULL,
	"EXPERT_ACCOUNT"	VARCHAR2(50)		NULL,
	"EXPERT_HOLDER"	VARCHAR2(20)		NULL,
	"ATT_ID"	NUMBER		NULL,
	"EXFIELD_ID"	VARCHAR2(20)		NULL,
	"EXJOB_ID"	VARCHAR2(20)		NULL
);

CREATE TABLE "INTEREST" (
	"INTE_NO"	VARCHAR2(20)		NOT NULL,
	"INTE_DATE"	DATE		NOT NULL,
	"PR_NO"	VARCHAR2(20)		NOT NULL,
	"MEM_ID2"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "INTEREST"."INTE_NO" IS '관심인재 번호';

COMMENT ON COLUMN "INTEREST"."INTE_DATE" IS '스크랩 날짜';

COMMENT ON COLUMN "INTEREST"."MEM_ID2" IS '회원아이디';

CREATE TABLE "TODAYSEE" (
	"TODAY_NO"	VARCHAR2(20)		NOT NULL,
	"PR_NO"	VARCHAR2(20)		NOT NULL,
	"MEM_ID2"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "TODAYSEE"."TODAY_NO" IS '조회 번호';

COMMENT ON COLUMN "TODAYSEE"."MEM_ID2" IS '회원아이디';

CREATE TABLE "EXREVIEW" (
	"EXREVIEW_ID"	VARCHAR2(20)		NOT NULL,
	"EXREVIEW_NAME"	VARCHAR2(100)		NULL,
	"EXREVIEW_WRITER"	VARCHAR2(50)		NULL,
	"EXREVIEW_PASS"	VARCHAR2(20)		NULL,
	"EXREVIEW_CONTENT"	VARCHAR2(2000)		NULL,
	"EXREVIEW_HIT"	NUMBER		NULL,
	"EXCART_ID"	VARCHAR2(20)		NOT NULL,
	"EXREVIEW_DATE"	DATE		NULL,
	"EXREVIEW_SCORE"	VARCHAR2(5)		NULL
);

CREATE TABLE "EXEVENT" (
	"EXEVENT_ID"	VARCHAR2(20)		NOT NULL,
	"EXEVENT_NAME"	VARCHAR2(50)		NULL,
	"EXEVENT_CONTENT"	VARCHAR2(2000)		NULL,
	"EXEVENT_START"	DATE		NULL,
	"EXEVENT_END"	DATE		NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"ATT_ID"	NUMBER		NULL,
	"EXEVENT_HITS"	NUMBER		NULL
);

COMMENT ON COLUMN "EXEVENT"."MEM_ID" IS '회원아이디';

CREATE TABLE "BOARD" (
	"BOARD_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"ATT_ID"	NUMBER		NULL,
	"SUB_NAME"	VARCHAR2(12)	DEFAULT '전체'	NOT NULL,
	"JOB_NAME"	VARCHAR2(30)		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(100)		NOT NULL,
	"BOARD_CONTENT"	CLOB		NOT NULL,
	"BOARD_DATE"	DATE		NOT NULL,
	"BOARD_HIT"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"TOTAL_GOOD"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"BOARD_GOOD"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"BOARD_FUN"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"BOARD_HELP"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"BOARD_CHEERUP"	NUMBER(5)	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_ID" IS '게시판ID';

COMMENT ON COLUMN "BOARD"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "BOARD"."SUB_NAME" IS '주제별분류';

COMMENT ON COLUMN "BOARD"."JOB_NAME" IS '직무별분류';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '내용';

COMMENT ON COLUMN "BOARD"."BOARD_DATE" IS '작성일';

COMMENT ON COLUMN "BOARD"."BOARD_HIT" IS '조회수';

COMMENT ON COLUMN "BOARD"."TOTAL_GOOD" IS '전체공감수';

COMMENT ON COLUMN "BOARD"."BOARD_GOOD" IS '좋아요';

COMMENT ON COLUMN "BOARD"."BOARD_FUN" IS '재밌어요';

COMMENT ON COLUMN "BOARD"."BOARD_HELP" IS '도움돼요';

COMMENT ON COLUMN "BOARD"."BOARD_CHEERUP" IS '힘내요';

CREATE TABLE "INCUM_INTERVIEW" (
	"INTERVIEW_ID"	VARCHAR2(20)		NOT NULL,
	"CMP_ID"	VARCHAR2(20)		NOT NULL,
	"JOB_NAME"	VARCHAR2(30)		NOT NULL,
	"INCUM_TITLE"	VARCHAR2(100)		NOT NULL,
	"INCUM_CONTENT"	CLOB		NOT NULL,
	"INCUM_NAME"	VARCHAR2(30)		NOT NULL,
	"INCUM_DATE"	DATE		NOT NULL,
	"INCUM_HIT"	NUMBER(5)	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "INCUM_INTERVIEW"."INTERVIEW_ID" IS '현직자인터뷰ID';

COMMENT ON COLUMN "INCUM_INTERVIEW"."CMP_ID" IS '회사아이디';

COMMENT ON COLUMN "INCUM_INTERVIEW"."JOB_NAME" IS '직무별분류';

COMMENT ON COLUMN "INCUM_INTERVIEW"."INCUM_TITLE" IS '제목';

COMMENT ON COLUMN "INCUM_INTERVIEW"."INCUM_CONTENT" IS '내용';

COMMENT ON COLUMN "INCUM_INTERVIEW"."INCUM_NAME" IS '작성자성명';

COMMENT ON COLUMN "INCUM_INTERVIEW"."INCUM_DATE" IS '작성일';

COMMENT ON COLUMN "INCUM_INTERVIEW"."INCUM_HIT" IS '조회수';

CREATE TABLE "COUNSELING" (
	"COUN_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"COUN_TITLE"	VARCHAR2(50)		NULL,
	"COUN_CONTENT"	CLOB		NULL,
	"COUN_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"COUN_STATE"	VARCHAR(10)	DEFAULT 1	NULL,
	"REF_COUN"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "COUNSELING"."COUN_ID" IS '게시판ID';

COMMENT ON COLUMN "COUNSELING"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "COUNSELING"."COUN_TITLE" IS '제목';

COMMENT ON COLUMN "COUNSELING"."COUN_CONTENT" IS '내용';

COMMENT ON COLUMN "COUNSELING"."COUN_DATE" IS '작성일';

COMMENT ON COLUMN "COUNSELING"."COUN_STATE" IS '글상태';

COMMENT ON COLUMN "COUNSELING"."REF_COUN" IS '부모글';

CREATE TABLE "RESUME_FORM" (
	"RESUME_FORM_ID"	VARCHAR2(20)		NOT NULL,
	"ATT_ID"	NUMBER		NULL,
	"RESUME_KIND"	VARCHAR2(25)		NOT NULL,
	"FORM_TITLE"	VARCHAR2(100)		NOT NULL,
	"FORM_HIT"	NUMBER(6)	DEFAULT 0	NULL,
	"FORM_CONTENT"	VARCHAR2(4000)		NOT NULL
);

COMMENT ON COLUMN "RESUME_FORM"."RESUME_FORM_ID" IS '이력서양식ID';

COMMENT ON COLUMN "RESUME_FORM"."ATT_ID" IS '첨부파일아이디';

COMMENT ON COLUMN "RESUME_FORM"."RESUME_KIND" IS '이력서분류';

COMMENT ON COLUMN "RESUME_FORM"."FORM_TITLE" IS '제목';

COMMENT ON COLUMN "RESUME_FORM"."FORM_HIT" IS '조회수';

COMMENT ON COLUMN "RESUME_FORM"."FORM_CONTENT" IS '내용';

CREATE TABLE "CORPOR_TRANS" (
	"COMPANY_ID"	VARCHAR2(20)		NOT NULL,
	"RECRU_NO"	VARCHAR2(50)		NULL,
	"TYPE_OF_WORK"	VARCHAR2(50)		NULL,
	"YOUTH_BENEFIT"	VARCHAR2(50)		NULL,
	"INTERVIEW_INFORM"	VARCHAR2(50)		NULL,
	"NUM_OF_YEARS"	VARCHAR2(50)		NULL,
	"AGE"	VARCHAR2(50)		NULL,
	"OVERTIME"	VARCHAR2(50)		NULL,
	"COMPANY_HISTORY"	VARCHAR2(50)		NULL,
	"ENTER_TYPE"	VARCHAR2(50)		NULL,
	"NUM_OF_EMP"	VARCHAR2(50)		NULL,
	"BENEFIT"	VARCHAR2(50)		NULL,
	"DINING_TOGETHER"	VARCHAR2(50)		NULL,
	"TRANS_DATE"	DATE		NOT NULL,
	"TOTAL_COUNT"	NUMBER(2)		NULL
);

COMMENT ON COLUMN "CORPOR_TRANS"."COMPANY_ID" IS '회사아이디';

COMMENT ON COLUMN "CORPOR_TRANS"."RECRU_NO" IS '채용횟수';

COMMENT ON COLUMN "CORPOR_TRANS"."TYPE_OF_WORK" IS '근무형태';

COMMENT ON COLUMN "CORPOR_TRANS"."YOUTH_BENEFIT" IS '청년혜택';

COMMENT ON COLUMN "CORPOR_TRANS"."INTERVIEW_INFORM" IS '면접통보유무';

COMMENT ON COLUMN "CORPOR_TRANS"."NUM_OF_YEARS" IS '근속연수';

COMMENT ON COLUMN "CORPOR_TRANS"."AGE" IS '연령구성';

COMMENT ON COLUMN "CORPOR_TRANS"."OVERTIME" IS '야근빈도';

COMMENT ON COLUMN "CORPOR_TRANS"."COMPANY_HISTORY" IS '업력';

COMMENT ON COLUMN "CORPOR_TRANS"."ENTER_TYPE" IS '기업형태';

COMMENT ON COLUMN "CORPOR_TRANS"."NUM_OF_EMP" IS '직원수';

COMMENT ON COLUMN "CORPOR_TRANS"."BENEFIT" IS '복리후생';

COMMENT ON COLUMN "CORPOR_TRANS"."DINING_TOGETHER" IS '회식빈도';

COMMENT ON COLUMN "CORPOR_TRANS"."TRANS_DATE" IS '등록일';

CREATE TABLE "TRANS_CALCUL" (
	"TRAN_ID"	VARCHAR2(20)		NOT NULL,
	"COMPANY_ID"	VARCHAR2(20)		NOT NULL,
	"FORM_WRITING"	NUMBER(3)	DEFAULT 0	NOT NULL,
	"JOIN_RESIGN_RATIO"	NUMBER(3)	DEFAULT 0	NOT NULL,
	"AVER_SALARY_RANK"	NUMBER(3)	DEFAULT 0	NOT NULL,
	"SALES"	NUMBER(3)	DEFAULT 0	NOT NULL,
	"BUSINESS_PROFITS"	NUMBER(3)	DEFAULT 0	NOT NULL,
	"CURRENT_PROFIT"	NUMBER(3)	DEFAULT 0	NOT NULL,
	"REVIEW_SCORE"	NUMBER(3)	DEFAULT 0	NOT NULL,
	"RENEWAL"	DATE		NOT NULL,
	"TRAN_TOTAL"	NUMBER(4)	DEFAULT 0	NOT NULL,
	"TRAN_GRADE"	VARCHAR2(2)		NOT NULL
);

COMMENT ON COLUMN "TRANS_CALCUL"."TRAN_ID" IS '투명도ID';

COMMENT ON COLUMN "TRANS_CALCUL"."COMPANY_ID" IS '회사아이디';

COMMENT ON COLUMN "TRANS_CALCUL"."FORM_WRITING" IS '양식작성개수';

COMMENT ON COLUMN "TRANS_CALCUL"."JOIN_RESIGN_RATIO" IS '입,퇴사율';

COMMENT ON COLUMN "TRANS_CALCUL"."AVER_SALARY_RANK" IS '평균연봉순위';

COMMENT ON COLUMN "TRANS_CALCUL"."SALES" IS '매출액';

COMMENT ON COLUMN "TRANS_CALCUL"."BUSINESS_PROFITS" IS '영업이익';

COMMENT ON COLUMN "TRANS_CALCUL"."CURRENT_PROFIT" IS '당기순이익';

COMMENT ON COLUMN "TRANS_CALCUL"."REVIEW_SCORE" IS '리뷰평점';

COMMENT ON COLUMN "TRANS_CALCUL"."RENEWAL" IS '갱신일';

COMMENT ON COLUMN "TRANS_CALCUL"."TRAN_TOTAL" IS '투명도총점';

COMMENT ON COLUMN "TRANS_CALCUL"."TRAN_GRADE" IS '투명도등급';

CREATE TABLE "SUPPORT" (
	"SUPPORT_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"SUPPORT_TITLE"	VARCHAR2(50)		NULL,
	"SUPPORT_CONTENT"	CLOB		NULL,
	"SUPPORT_DATE"	DATE		NULL,
	"SUPPORT_STATE"	VARCHAR(10)		NULL,
	"SUPPORT_INSTITUTE"	VARCHAR2(100)		NULL,
	"SUPPORT_HIT"	NUMBER		NULL
);

COMMENT ON COLUMN "SUPPORT"."SUPPORT_ID" IS '게시판ID';

COMMENT ON COLUMN "SUPPORT"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "SUPPORT"."SUPPORT_TITLE" IS '제목';

COMMENT ON COLUMN "SUPPORT"."SUPPORT_CONTENT" IS '내용';

COMMENT ON COLUMN "SUPPORT"."SUPPORT_DATE" IS '작성일';

COMMENT ON COLUMN "SUPPORT"."SUPPORT_STATE" IS '글상태';

COMMENT ON COLUMN "SUPPORT"."SUPPORT_INSTITUTE" IS '시행기관명';

COMMENT ON COLUMN "SUPPORT"."SUPPORT_HIT" IS '조회수';

CREATE TABLE "ATTACH" (
	"ATT_ID"	NUMBER		NOT NULL,
	"ATT_NO"	NUMBER(3)		NOT NULL,
	"ATT_STRE_COURS"	VARCHAR2(2000)		NOT NULL,
	"ATT_SAVENAME"	VARCHAR2(255)		NOT NULL,
	"ATT_FILENAME"	VARCHAR2(255)		NULL,
	"ATT_MIME"	VARCHAR2(20)		NOT NULL,
	"ATT_FILESIZE"	NUMBER(10)		NULL,
	"ATT_FANCYSIZE"	VARCHAR2(10)		NULL,
	"ATT_DOWNLOAD"	NUMBER(5)		NULL
);

COMMENT ON COLUMN "ATTACH"."ATT_ID" IS '첨부파일ID';

COMMENT ON COLUMN "ATTACH"."ATT_NO" IS '첨부파일순번';

COMMENT ON COLUMN "ATTACH"."ATT_STRE_COURS" IS '파일저장경로';

COMMENT ON COLUMN "ATTACH"."ATT_SAVENAME" IS '저장파일명';

COMMENT ON COLUMN "ATTACH"."ATT_FILENAME" IS '원본파일명';

COMMENT ON COLUMN "ATTACH"."ATT_MIME" IS '파일확장자';

COMMENT ON COLUMN "ATTACH"."ATT_FILESIZE" IS '파일크기';

COMMENT ON COLUMN "ATTACH"."ATT_FANCYSIZE" IS '파일팬시크기';

COMMENT ON COLUMN "ATTACH"."ATT_DOWNLOAD" IS '다운로드횟수';

CREATE TABLE "LIKE_COMPANY" (
	"LKCO_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"CMP_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "LIKE_COMPANY"."LKCO_ID" IS '관심기업ID';

COMMENT ON COLUMN "LIKE_COMPANY"."MEM_ID" IS '구직자아이디';

COMMENT ON COLUMN "LIKE_COMPANY"."CMP_ID" IS '회사아이디';

CREATE TABLE "LIKE_ANNO" (
	"LKANNO_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"ANNO_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "LIKE_ANNO"."LKANNO_ID" IS '관심공고ID';

COMMENT ON COLUMN "LIKE_ANNO"."MEM_ID" IS '구직자아이디';

COMMENT ON COLUMN "LIKE_ANNO"."ANNO_ID" IS '공고아이디';

CREATE TABLE "ADMIN" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_AUTH_CD"	VARCHAR2(10)		NULL
);

COMMENT ON COLUMN "ADMIN"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "ADMIN"."MEM_AUTH_CD" IS '권한';

CREATE TABLE "PR" (
	"PR_NO"	VARCHAR2(20)		NOT NULL,
	"PR_NAME"	VARCHAR2(100)		NOT NULL,
	"PR_CONTENT"	VARCHAR2(500)		NOT NULL,
	"PR_DATE"	DATE		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"MYRESUME_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "PR"."PR_NO" IS '홍보글 번호';

COMMENT ON COLUMN "PR"."PR_NAME" IS '홍보글 제목';

COMMENT ON COLUMN "PR"."PR_CONTENT" IS '홍보글 소개';

COMMENT ON COLUMN "PR"."PR_DATE" IS '작성일자';

COMMENT ON COLUMN "PR"."MYRESUME_ID" IS '이력서 아이디';

CREATE TABLE "WALFARE" (
	"WALFARE_CODE"	VARCHAR2(10)		NOT NULL,
	"WALFARE_NAME"	VARCHAR2(50)		NOT NULL,
	"WALFARE_REF"	VARCHAR2(10)		NULL
);

COMMENT ON COLUMN "WALFARE"."WALFARE_CODE" IS '복지코드';

COMMENT ON COLUMN "WALFARE"."WALFARE_NAME" IS '항목명';

COMMENT ON COLUMN "WALFARE"."WALFARE_REF" IS '상위코드';

CREATE TABLE "ANNO_WALFARE" (
	"ANNOWAL_CODE"	VARCHAR2(10)		NOT NULL,
	"WALFARE_CODE"	VARCHAR2(10)		NOT NULL,
	"DA_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "ANNO_WALFARE"."ANNOWAL_CODE" IS '공고별복지코드';

COMMENT ON COLUMN "ANNO_WALFARE"."WALFARE_CODE" IS '복지코드';

COMMENT ON COLUMN "ANNO_WALFARE"."DA_ID" IS '세부공고아이디';

CREATE TABLE "ANNO_DETAIL" (
	"DA_ID"	VARCHAR2(20)		NOT NULL,
	"ANNO_ID"	VARCHAR2(20)		NOT NULL,
	"DA_FD"	VARCHAR2(20)		NOT NULL,
	"DA_COUNT"	VARCHAR2(20)		NULL,
	"DA_TASK"	VARCHAR2(600)		NULL,
	"DA_DEPARTMENT"	VARCHAR2(20)		NULL,
	"DA_CONDITION"	VARCHAR(600)		NULL,
	"DA_PREFER"	VARCHAR(600)		NULL,
	"DA_WORKDAY"	VARCHAR2(50)		NULL,
	"DA_WORKTIME"	VARCHAR2(50)		NULL,
	"DA_CAR_CD"	VARCHAR2(10)		NOT NULL,
	"DA_CARYEAR"	VARCHAR2(20)		NULL,
	"REGION_CODE"	VARCHAR2(10)		NOT NULL,
	"JOB_CODE"	VARCHAR2(10)		NOT NULL,
	"ANNOEDU_CODE"	VARCHAR2(10)		NOT NULL,
	"EMPLTYPE_CODE"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "ANNO_DETAIL"."DA_ID" IS '세부공고아이디';

COMMENT ON COLUMN "ANNO_DETAIL"."ANNO_ID" IS '공고아이디';

COMMENT ON COLUMN "ANNO_DETAIL"."DA_FD" IS '모집분야';

COMMENT ON COLUMN "ANNO_DETAIL"."DA_COUNT" IS '모집인원';

COMMENT ON COLUMN "ANNO_DETAIL"."DA_TASK" IS '담당업무';

COMMENT ON COLUMN "ANNO_DETAIL"."DA_DEPARTMENT" IS '근무부서';

COMMENT ON COLUMN "ANNO_DETAIL"."DA_CONDITION" IS '지원조건';

COMMENT ON COLUMN "ANNO_DETAIL"."DA_PREFER" IS '우대사항';

COMMENT ON COLUMN "ANNO_DETAIL"."DA_WORKDAY" IS '근무요일';

COMMENT ON COLUMN "ANNO_DETAIL"."DA_WORKTIME" IS '근무시간';

COMMENT ON COLUMN "ANNO_DETAIL"."DA_CAR_CD" IS '경력코드';

COMMENT ON COLUMN "ANNO_DETAIL"."DA_CARYEAR" IS '경력연차';

COMMENT ON COLUMN "ANNO_DETAIL"."REGION_CODE" IS '지역코드';

COMMENT ON COLUMN "ANNO_DETAIL"."JOB_CODE" IS '직무코드';

COMMENT ON COLUMN "ANNO_DETAIL"."ANNOEDU_CODE" IS '학력코드';

COMMENT ON COLUMN "ANNO_DETAIL"."EMPLTYPE_CODE" IS '고용형태코드';

CREATE TABLE "EXLPROD" (
	"EXLPROD_ID"	VARCHAR2(20)		NOT NULL,
	"EXLPROD_NAME"	VARCHAR2(30)		NULL
);

COMMENT ON COLUMN "EXLPROD"."EXLPROD_ID" IS '분류코드';

CREATE TABLE "ANNO_EDUCATION" (
	"ANNOEDU_CODE"	VARCHAR2(10)		NOT NULL,
	"ANNOEDU_NAME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "ANNO_EDUCATION"."ANNOEDU_CODE" IS '학력코드';

COMMENT ON COLUMN "ANNO_EDUCATION"."ANNOEDU_NAME" IS '학력명';

CREATE TABLE "POSITION" (
	"POSITION_CODE"	VARCHAR2(10)		NOT NULL,
	"POSITION_NAME"	VARCHAR2(50)		NULL
);

COMMENT ON COLUMN "POSITION"."POSITION_CODE" IS '직급직책코드';

COMMENT ON COLUMN "POSITION"."POSITION_NAME" IS '직급직책명';

CREATE TABLE "EMPLTYPE" (
	"EMPLTYPE_CODE"	VARCHAR2(10)		NOT NULL,
	"EMPLTYPE_NAME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "EMPLTYPE"."EMPLTYPE_CODE" IS '고용형태코드';

COMMENT ON COLUMN "EMPLTYPE"."EMPLTYPE_NAME" IS '고용형태명';

CREATE TABLE "ANNO_POSITION" (
	"ANNOPOS_CODE"	VARCHAR2(10)		NOT NULL,
	"POSITION_CODE"	VARCHAR2(10)		NOT NULL,
	"DA_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "ANNO_POSITION"."ANNOPOS_CODE" IS '공고상세별직급직책코드';

COMMENT ON COLUMN "ANNO_POSITION"."POSITION_CODE" IS '직급직책코드';

COMMENT ON COLUMN "ANNO_POSITION"."DA_ID" IS '세부공고아이디';

CREATE TABLE "UPPER50" (
	"UPPER50_NO"	VARCHAR2(20)		NOT NULL,
	"CMP_ID"	VARCHAR2(20)		NOT NULL,
	"UPPER50_SCORE"	VARCHAR2(20)		NOT NULL,
	"JOB_CODE"	VARCHAR2(10)		NOT NULL,
	"UPPER50_SAMPLE"	VARCHAR2(10)		NULL,
	"UPPER50_DEVIATION"	VARCHAR2(10)		NULL
);

COMMENT ON COLUMN "UPPER50"."UPPER50_NO" IS '합격자 상위50%번호';

COMMENT ON COLUMN "UPPER50"."CMP_ID" IS '회사아이디';

COMMENT ON COLUMN "UPPER50"."UPPER50_SCORE" IS '상위 50% 점수';

COMMENT ON COLUMN "UPPER50"."JOB_CODE" IS '직무코드';

CREATE TABLE "UPPER70" (
	"UPPER70_NO"	VARCHAR2(20)		NOT NULL,
	"CMP_ID"	VARCHAR2(20)		NOT NULL,
	"UPPER70_SCORE"	VARCHAR2(20)		NOT NULL,
	"JOB_CODE"	VARCHAR2(10)		NOT NULL,
	"UPPER70_SAMPLE"	VARCHAR2(10)		NULL,
	"UPPER70_DEVIATION"	VARCHAR2(10)		NULL
);

COMMENT ON COLUMN "UPPER70"."UPPER70_NO" IS '합격자 상위 70% 번호';

COMMENT ON COLUMN "UPPER70"."CMP_ID" IS '회사아이디';

COMMENT ON COLUMN "UPPER70"."UPPER70_SCORE" IS '상위 70% 점수';

COMMENT ON COLUMN "UPPER70"."JOB_CODE" IS '직무코드';

CREATE TABLE "ITEM_CODE" (
	"ITEM_CODE_ID"	VARCHAR2(20)		NOT NULL,
	"PROCESS_CODE_ID"	VARCHAR2(20)		NOT NULL,
	"ITEM_CODE_NAME"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "ITEM_CODE"."ITEM_CODE_ID" IS '항목코드';

COMMENT ON COLUMN "ITEM_CODE"."PROCESS_CODE_ID" IS '분류코드';

COMMENT ON COLUMN "ITEM_CODE"."ITEM_CODE_NAME" IS '항목명';

CREATE TABLE "PROCESS" (
	"DA_ID"	VARCHAR2(20)		NOT NULL,
	"PROCESS_CODE_ID"	VARCHAR2(20)		NOT NULL,
	"PROCESS_NO"	NUMBER	DEFAULT 1	NOT NULL,
	"PROCESS_STARTDATE"	DATE		NOT NULL,
	"PROCESS_ENDDATE"	DATE		NOT NULL,
	"PROCESS_WAY"	VARCHAR2(300)		NOT NULL,
	"PROCESS_SCORE"	NUMBER	DEFAULT 0	NOT NULL,
	"ATT_ID"	NUMBER		NULL
);

COMMENT ON COLUMN "PROCESS"."DA_ID" IS '세부공고아이디';

COMMENT ON COLUMN "PROCESS"."PROCESS_CODE_ID" IS '분류코드';

COMMENT ON COLUMN "PROCESS"."PROCESS_NO" IS '각 세부 공고의 각 과정 순번';

COMMENT ON COLUMN "PROCESS"."PROCESS_STARTDATE" IS '시작날짜';

COMMENT ON COLUMN "PROCESS"."PROCESS_ENDDATE" IS '종료날짜';

COMMENT ON COLUMN "PROCESS"."PROCESS_WAY" IS '온라인, 대면 등';

COMMENT ON COLUMN "PROCESS"."PROCESS_SCORE" IS '기준만점';

COMMENT ON COLUMN "PROCESS"."ATT_ID" IS '각 과정별 점수 입증 관련 문서 업로드하는 첨부파일 아이디';

CREATE TABLE "REGION" (
	"REGION_CODE"	VARCHAR2(10)		NOT NULL,
	"REGION_NAME"	VARCHAR2(50)		NOT NULL,
	"REGION_REF"	VARCHAR2(10)		NULL
);

COMMENT ON COLUMN "REGION"."REGION_CODE" IS '지역코드';

COMMENT ON COLUMN "REGION"."REGION_NAME" IS '지역명';

COMMENT ON COLUMN "REGION"."REGION_REF" IS '상위코드';

CREATE TABLE "ANNO_JOB" (
	"JOB_CODE"	VARCHAR2(10)		NOT NULL,
	"JOB_NAME"	VARCHAR2(50)		NOT NULL,
	"JOB_REF"	VARCHAR2(10)		NULL
);

COMMENT ON COLUMN "ANNO_JOB"."JOB_CODE" IS '직무코드';

COMMENT ON COLUMN "ANNO_JOB"."JOB_NAME" IS '직무명';

COMMENT ON COLUMN "ANNO_JOB"."JOB_REF" IS '상위코드';

CREATE TABLE "INDUSTRY" (
	"INDUSTRY_CODE"	VARCHAR2(20)		NOT NULL,
	"INDUSTRY_NAME"	VARCHAR2(200)		NULL,
	"INDUSTRY_REF"	VARCHAR2(10)		NULL
);

COMMENT ON COLUMN "INDUSTRY"."INDUSTRY_CODE" IS '업종코드';

COMMENT ON COLUMN "INDUSTRY"."INDUSTRY_NAME" IS '업종명';

COMMENT ON COLUMN "INDUSTRY"."INDUSTRY_REF" IS '상위코드';

CREATE TABLE "COMMON_CODE" (
	"CODE"	VARCHAR2(10)		NULL,
	"CODE_NAME"	VARCHAR2(200)		NULL,
	"REF_CODE"	VARCHAR2(10)		NULL,
	"CODE_DESC"	VARCHAR2(200)		NULL
);

COMMENT ON COLUMN "COMMON_CODE"."CODE" IS '공통코드';

COMMENT ON COLUMN "COMMON_CODE"."CODE_NAME" IS '공통코드명';

COMMENT ON COLUMN "COMMON_CODE"."REF_CODE" IS '상위공통코드';

COMMENT ON COLUMN "COMMON_CODE"."CODE_DESC" IS '공통코드설명';

CREATE TABLE "LOG_MEMBER" (
	"LOG_ID"	NUMBER		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NULL,
	"ANNO_ID"	VARCHAR2(20)		NULL,
	"CMP_ID"	VARCHAR2(20)		NULL,
	"LOG_TIME"	TIMESTAMP		NULL
);

COMMENT ON COLUMN "LOG_MEMBER"."LOG_ID" IS '로그ID';

COMMENT ON COLUMN "LOG_MEMBER"."MEM_ID" IS '구직자ID';

COMMENT ON COLUMN "LOG_MEMBER"."ANNO_ID" IS '공고ID';

COMMENT ON COLUMN "LOG_MEMBER"."CMP_ID" IS '회사ID';

COMMENT ON COLUMN "LOG_MEMBER"."LOG_TIME" IS '기록시간';

CREATE TABLE "MYRESUME" (
	"MYRESUME_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"MYRESUME_INSERT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MYRESUME_DELETE_DATE"	DATE	DEFAULT SYSDATE	NULL
);

COMMENT ON COLUMN "MYRESUME"."MYRESUME_ID" IS '이력서 아이디';

COMMENT ON COLUMN "MYRESUME"."MYRESUME_DELETE_DATE" IS '삭제날짜';

CREATE TABLE "ASK" (
	"ASK_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"ASK_CATE"	VARCHAR2(6)		NULL,
	"ASK_TITLE"	VARCHAR2(100)		NOT NULL,
	"ASK_CONTNET"	CLOB		NOT NULL,
	"ATT_ID"	NUMBER		NOT NULL,
	"ASK_DATE"	DATE		NOT NULL,
	"REF_ASK"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "ASK"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "ASK"."ASK_CATE" IS '구분';

COMMENT ON COLUMN "ASK"."ASK_TITLE" IS '제목';

COMMENT ON COLUMN "ASK"."ASK_CONTNET" IS '내용';

COMMENT ON COLUMN "ASK"."ATT_ID" IS '첨부파일ID';

COMMENT ON COLUMN "ASK"."ASK_DATE" IS '작성일';

COMMENT ON COLUMN "ASK"."REF_ASK" IS '부모글';

CREATE TABLE "MILEAGE" (
	"MILEAGE_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"MILEAGE_DATE"	DATE		NULL,
	"MILEAGE_USE"	VARCHAR2(10)		NULL,
	"MILEAGE_TOTAL"	NUMBER		NULL
);

COMMENT ON COLUMN "MILEAGE"."MEM_ID" IS '구직자아이디';

CREATE TABLE "PROCESS_FORM" (
	"PROCESS_FORM_ID"	VARCHAR2(20)		NOT NULL,
	"PROCESS_CODE_ID"	VARCHAR2(20)		NOT NULL,
	"PROCESS_FORM_NO"	NUMBER		NOT NULL,
	"PROCESS_FORM_WAY"	VARCHAR2(300)		NULL,
	"PROCESS_FORM_SCORE"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "PROCESS_FORM"."PROCESS_FORM_ID" IS '채용과정양식ID';

COMMENT ON COLUMN "PROCESS_FORM"."PROCESS_CODE_ID" IS '분류코드';

COMMENT ON COLUMN "PROCESS_FORM"."PROCESS_FORM_NO" IS '채용과정양식 과정번호';

COMMENT ON COLUMN "PROCESS_FORM"."PROCESS_FORM_WAY" IS '채용과정양식 방식- 온라인, 대면';

COMMENT ON COLUMN "PROCESS_FORM"."PROCESS_FORM_SCORE" IS '채용과정양식 기준만점';

CREATE TABLE "ITEM_FORM" (
	"ITEM_FORM_ID"	VARCHAR2(20)		NOT NULL,
	"ITEM_CODE_ID"	VARCHAR2(20)		NOT NULL,
	"ITEM_FORM_ASK"	VARCHAR2(200)		NOT NULL
);

COMMENT ON COLUMN "ITEM_FORM"."ITEM_FORM_ID" IS '채용과정항목양식ID';

COMMENT ON COLUMN "ITEM_FORM"."ITEM_CODE_ID" IS '항목코드';

COMMENT ON COLUMN "ITEM_FORM"."ITEM_FORM_ASK" IS '채용과정항목양식 질문 관리';

CREATE TABLE "EXINTEREST" (
	"EXINTEREST_ID"	VARCHAR2(20)		NOT NULL,
	"EXPROD_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "EXINTEREST"."MEM_ID" IS '회원아이디';

CREATE TABLE "MYRESUME_ITEM" (
	"MYRESUME_ID"	VARCHAR2(20)		NOT NULL,
	"MYRESUME_ITEM_ID"	VARCHAR2(20)		NULL,
	"MYRESUME_ITEM_NO"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "MYRESUME_ITEM"."MYRESUME_ID" IS '이력서 아이디';

COMMENT ON COLUMN "MYRESUME_ITEM"."MYRESUME_ITEM_ID" IS '학력ID, 경력ID 등등';

COMMENT ON COLUMN "MYRESUME_ITEM"."MYRESUME_ITEM_NO" IS '1,2,3,4,...';

CREATE TABLE "EXFIELD" (
	"EXFIELD_ID"	VARCHAR2(20)		NULL,
	"EXFIELD_NAME"	VARCHAR2(30)		NULL
);

CREATE TABLE "EXJOB" (
	"EXJOB_ID"	VARCHAR2(20)		NULL,
	"EXJOB_NAME"	VARCHAR2(30)		NULL
);


