ALTER TABLE "SEEKER" ADD CONSTRAINT "PK_SEEKER" PRIMARY KEY (
	"MEM_ID"
);

ALTER TABLE "INCRUITER" ADD CONSTRAINT "PK_INCRUITER" PRIMARY KEY (
	"MEM_ID"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEM_ID"
);

ALTER TABLE "ANNO" ADD CONSTRAINT "PK_ANNO" PRIMARY KEY (
	"ANNO_ID"
);

ALTER TABLE "APPLY" ADD CONSTRAINT "PK_APPLY" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "RESUME_SCORE" ADD CONSTRAINT "PK_RESUME_SCORE" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "INTRODUCTION_SCORE" ADD CONSTRAINT "PK_INTRODUCTION_SCORE" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "TEST_SCORE" ADD CONSTRAINT "PK_TEST_SCORE" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "COMPETENCY_SCORE" ADD CONSTRAINT "PK_COMPETENCY_SCORE" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "PRACTICE_SCORE" ADD CONSTRAINT "PK_PRACTICE_SCORE" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "DISCUSS_SCORE" ADD CONSTRAINT "PK_DISCUSS_SCORE" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "INTERNSHIP_SCORE" ADD CONSTRAINT "PK_INTERNSHIP_SCORE" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "INDEPTH_INTERVIEW_SCORE" ADD CONSTRAINT "PK_INDEPTH_INTERVIEW_SCORE" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "ITEM" ADD CONSTRAINT "PK_ITEM" PRIMARY KEY (
	"DA_ID",
	"ITEM_CODE_ID2"
);

ALTER TABLE "PROCESS_CODE" ADD CONSTRAINT "PK_PROCESS_CODE" PRIMARY KEY (
	"PROCESS_CODE_ID"
);

ALTER TABLE "CAREER" ADD CONSTRAINT "PK_CAREER" PRIMARY KEY (
	"CAREER_ID"
);

ALTER TABLE "EDUCATION" ADD CONSTRAINT "PK_EDUCATION" PRIMARY KEY (
	"EDU_ID"
);

ALTER TABLE "CERTIFICATION" ADD CONSTRAINT "PK_CERTIFICATION" PRIMARY KEY (
	"CERT_ID"
);

ALTER TABLE "MYINTRODUCTION" ADD CONSTRAINT "PK_MYINTRODUCTION" PRIMARY KEY (
	"MYINTRO_ID"
);

ALTER TABLE "FACILITY" ADD CONSTRAINT "PK_FACILITY" PRIMARY KEY (
	"FACILITY_ID"
);

ALTER TABLE "ACTIVITY" ADD CONSTRAINT "PK_ACTIVITY" PRIMARY KEY (
	"ACT_ID"
);

ALTER TABLE "AWARD" ADD CONSTRAINT "PK_AWARD" PRIMARY KEY (
	"AWARD_ID"
);

ALTER TABLE "COURSE" ADD CONSTRAINT "PK_COURSE" PRIMARY KEY (
	"COURSE_ID"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"REVIEW_ID"
);

ALTER TABLE "CUT" ADD CONSTRAINT "PK_CUT" PRIMARY KEY (
	"CUT_ID"
);

ALTER TABLE "BLACKLIST" ADD CONSTRAINT "PK_BLACKLIST" PRIMARY KEY (
	"BLACKLIST_ID"
);

ALTER TABLE "COMPANY" ADD CONSTRAINT "PK_COMPANY" PRIMARY KEY (
	"CMP_ID"
);

ALTER TABLE "BOARD_REPORT" ADD CONSTRAINT "PK_BOARD_REPORT" PRIMARY KEY (
	"BOARD_RPT_ID"
);

ALTER TABLE "COMMENT_REPORT" ADD CONSTRAINT "PK_COMMENT_REPORT" PRIMARY KEY (
	"COMM_RPT_ID"
);

ALTER TABLE "ALRAM" ADD CONSTRAINT "PK_ALRAM" PRIMARY KEY (
	"ALRAM_ID"
);

ALTER TABLE "HELP" ADD CONSTRAINT "PK_HELP" PRIMARY KEY (
	"HELP_ID"
);

ALTER TABLE "NEWS" ADD CONSTRAINT "PK_NEWS" PRIMARY KEY (
	"NEWS_NO"
);

ALTER TABLE "CONTEST" ADD CONSTRAINT "PK_CONTEST" PRIMARY KEY (
	"CONT_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_ID"
);

ALTER TABLE "EXPROD" ADD CONSTRAINT "PK_EXPROD" PRIMARY KEY (
	"EXPROD_ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMM_ID"
);

ALTER TABLE "EXCART" ADD CONSTRAINT "PK_EXCART" PRIMARY KEY (
	"EXCART_ID"
);

ALTER TABLE "EXPERT" ADD CONSTRAINT "PK_EXPERT" PRIMARY KEY (
	"MEM_ID"
);

ALTER TABLE "INTEREST" ADD CONSTRAINT "PK_INTEREST" PRIMARY KEY (
	"INTE_NO"
);

ALTER TABLE "TODAYSEE" ADD CONSTRAINT "PK_TODAYSEE" PRIMARY KEY (
	"TODAY_NO"
);

ALTER TABLE "EXREVIEW" ADD CONSTRAINT "PK_EXREVIEW" PRIMARY KEY (
	"EXREVIEW_ID"
);

ALTER TABLE "EXEVENT" ADD CONSTRAINT "PK_EXEVENT" PRIMARY KEY (
	"EXEVENT_ID"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_ID"
);

ALTER TABLE "INCUM_INTERVIEW" ADD CONSTRAINT "PK_INCUM_INTERVIEW" PRIMARY KEY (
	"INTERVIEW_ID"
);

ALTER TABLE "COUNSELING" ADD CONSTRAINT "PK_COUNSELING" PRIMARY KEY (
	"COUN_ID"
);

ALTER TABLE "RESUME_FORM" ADD CONSTRAINT "PK_RESUME_FORM" PRIMARY KEY (
	"RESUME_FORM_ID"
);

ALTER TABLE "CORPOR_TRANS" ADD CONSTRAINT "PK_CORPOR_TRANS" PRIMARY KEY (
	"COMPANY_ID"
);

ALTER TABLE "TRANS_CALCUL" ADD CONSTRAINT "PK_TRANS_CALCUL" PRIMARY KEY (
	"TRAN_ID",
	"COMPANY_ID"
);

ALTER TABLE "SUPPORT" ADD CONSTRAINT "PK_SUPPORT" PRIMARY KEY (
	"SUPPORT_ID"
);

ALTER TABLE "ATTACH" ADD CONSTRAINT "PK_ATTACH" PRIMARY KEY (
	"ATT_ID",
	"ATT_NO"
);

ALTER TABLE "LIKE_COMPANY" ADD CONSTRAINT "PK_LIKE_COMPANY" PRIMARY KEY (
	"LKCO_ID"
);

ALTER TABLE "LIKE_ANNO" ADD CONSTRAINT "PK_LIKE_ANNO" PRIMARY KEY (
	"LKANNO_ID"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
	"MEM_ID"
);

ALTER TABLE "PR" ADD CONSTRAINT "PK_PR" PRIMARY KEY (
	"PR_NO"
);

ALTER TABLE "WALFARE" ADD CONSTRAINT "PK_WALFARE" PRIMARY KEY (
	"WALFARE_CODE"
);

ALTER TABLE "ANNO_WALFARE" ADD CONSTRAINT "PK_ANNO_WALFARE" PRIMARY KEY (
	"ANNOWAL_CODE"
);

ALTER TABLE "ANNO_DETAIL" ADD CONSTRAINT "PK_ANNO_DETAIL" PRIMARY KEY (
	"DA_ID"
);

ALTER TABLE "EXLPROD" ADD CONSTRAINT "PK_EXLPROD" PRIMARY KEY (
	"EXLPROD_ID"
);

ALTER TABLE "ANNO_EDUCATION" ADD CONSTRAINT "PK_ANNO_EDUCATION" PRIMARY KEY (
	"ANNOEDU_CODE"
);

ALTER TABLE "POSITION" ADD CONSTRAINT "PK_POSITION" PRIMARY KEY (
	"POSITION_CODE"
);

ALTER TABLE "EMPLTYPE" ADD CONSTRAINT "PK_EMPLTYPE" PRIMARY KEY (
	"EMPLTYPE_CODE"
);

ALTER TABLE "ANNO_POSITION" ADD CONSTRAINT "PK_ANNO_POSITION" PRIMARY KEY (
	"ANNOPOS_CODE"
);

ALTER TABLE "UPPER50" ADD CONSTRAINT "PK_UPPER50" PRIMARY KEY (
	"UPPER50_NO"
);

ALTER TABLE "UPPER70" ADD CONSTRAINT "PK_UPPER70" PRIMARY KEY (
	"UPPER70_NO"
);

ALTER TABLE "ITEM_CODE" ADD CONSTRAINT "PK_ITEM_CODE" PRIMARY KEY (
	"ITEM_CODE_ID"
);

ALTER TABLE "PROCESS" ADD CONSTRAINT "PK_PROCESS" PRIMARY KEY (
	"DA_ID",
	"PROCESS_CODE_ID"
);

ALTER TABLE "REGION" ADD CONSTRAINT "PK_REGION" PRIMARY KEY (
	"REGION_CODE"
);

ALTER TABLE "ANNO_JOB" ADD CONSTRAINT "PK_ANNO_JOB" PRIMARY KEY (
	"JOB_CODE"
);

ALTER TABLE "INDUSTRY" ADD CONSTRAINT "PK_INDUSTRY" PRIMARY KEY (
	"INDUSTRY_CODE"
);

ALTER TABLE "COMMON_CODE" ADD CONSTRAINT "PK_COMMON_CODE" PRIMARY KEY (
	"CODE"
);

ALTER TABLE "LOG_MEMBER" ADD CONSTRAINT "PK_LOG_MEMBER" PRIMARY KEY (
	"LOG_ID"
);

ALTER TABLE "MYRESUME" ADD CONSTRAINT "PK_MYRESUME" PRIMARY KEY (
	"MYRESUME_ID"
);

ALTER TABLE "ASK" ADD CONSTRAINT "PK_ASK" PRIMARY KEY (
	"ASK_ID",
	"MEM_ID"
);

ALTER TABLE "MILEAGE" ADD CONSTRAINT "PK_MILEAGE" PRIMARY KEY (
	"MILEAGE_ID"
);

ALTER TABLE "PROCESS_FORM" ADD CONSTRAINT "PK_PROCESS_FORM" PRIMARY KEY (
	"PROCESS_FORM_ID",
	"PROCESS_CODE_ID"
);

ALTER TABLE "ITEM_FORM" ADD CONSTRAINT "PK_ITEM_FORM" PRIMARY KEY (
	"ITEM_FORM_ID",
	"ITEM_CODE_ID"
);

ALTER TABLE "EXINTEREST" ADD CONSTRAINT "PK_EXINTEREST" PRIMARY KEY (
	"EXINTEREST_ID"
);

ALTER TABLE "MYRESUME_ITEM" ADD CONSTRAINT "PK_MYRESUME_ITEM" PRIMARY KEY (
	"MYRESUME_ID"
);

ALTER TABLE "EXFIELD" ADD CONSTRAINT "PK_EXFIELD" PRIMARY KEY (
	"EXFIELD_ID"
);

ALTER TABLE "EXJOB" ADD CONSTRAINT "PK_EXJOB" PRIMARY KEY (
	"EXJOB_ID"
);

ALTER TABLE "SEEKER" ADD CONSTRAINT "FK_MEMBER_TO_SEEKER_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "INCRUITER" ADD CONSTRAINT "FK_MEMBER_TO_INCRUITER_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "INCRUITER" ADD CONSTRAINT "FK_COMPANY_TO_INCRUITER_1" FOREIGN KEY (
	"CMP_ID"
)
REFERENCES "COMPANY" (
	"CMP_ID"
);

ALTER TABLE "ANNO" ADD CONSTRAINT "FK_COMPANY_TO_ANNO_1" FOREIGN KEY (
	"CMP_ID"
)
REFERENCES "COMPANY" (
	"CMP_ID"
);

ALTER TABLE "ANNO" ADD CONSTRAINT "FK_INCRUITER_TO_ANNO_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "INCRUITER" (
	"MEM_ID"
);

ALTER TABLE "ANNO" ADD CONSTRAINT "FK_INDUSTRY_TO_ANNO_1" FOREIGN KEY (
	"INDUSTRY_CODE"
)
REFERENCES "INDUSTRY" (
	"INDUSTRY_CODE"
);

ALTER TABLE "APPLY" ADD CONSTRAINT "FK_ANNO_DETAIL_TO_APPLY_1" FOREIGN KEY (
	"DA_ID"
)
REFERENCES "ANNO_DETAIL" (
	"DA_ID"
);

ALTER TABLE "APPLY" ADD CONSTRAINT "FK_SEEKER_TO_APPLY_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "SEEKER" (
	"MEM_ID"
);

ALTER TABLE "APPLY" ADD CONSTRAINT "FK_MYRESUME_TO_APPLY_1" FOREIGN KEY (
	"MYRESUME_ID"
)
REFERENCES "MYRESUME" (
	"MYRESUME_ID"
);

ALTER TABLE "APPLY" ADD CONSTRAINT "FK_MYINTRODUCTION_TO_APPLY_1" FOREIGN KEY (
	"MYINTRO_ID"
)
REFERENCES "MYINTRODUCTION" (
	"MYINTRO_ID"
);

ALTER TABLE "RESUME_SCORE" ADD CONSTRAINT "FK_APPLY_TO_RESUME_SCORE_1" FOREIGN KEY (
	"APPLY_ID"
)
REFERENCES "APPLY" (
	"APPLY_ID"
);

ALTER TABLE "INTRODUCTION_SCORE" ADD CONSTRAINT "FK_APPLY_TO_INTRO_SCORE_1" FOREIGN KEY (
	"APPLY_ID"
)
REFERENCES "APPLY" (
	"APPLY_ID"
);

ALTER TABLE "TEST_SCORE" ADD CONSTRAINT "FK_APPLY_TO_TEST_SCORE_1" FOREIGN KEY (
	"APPLY_ID"
)
REFERENCES "APPLY" (
	"APPLY_ID"
);

ALTER TABLE "COMPETENCY_SCORE" ADD CONSTRAINT "FK_APPLY_TO_COMPETENCY_SCORE_1" FOREIGN KEY (
	"APPLY_ID"
)
REFERENCES "APPLY" (
	"APPLY_ID"
);

ALTER TABLE "PRACTICE_SCORE" ADD CONSTRAINT "FK_APPLY_TO_PRACTICE_SCORE_1" FOREIGN KEY (
	"APPLY_ID"
)
REFERENCES "APPLY" (
	"APPLY_ID"
);

ALTER TABLE "DISCUSS_SCORE" ADD CONSTRAINT "FK_APPLY_TO_DISCUSS_SCORE_1" FOREIGN KEY (
	"APPLY_ID"
)
REFERENCES "APPLY" (
	"APPLY_ID"
);

ALTER TABLE "INTERNSHIP_SCORE" ADD CONSTRAINT "FK_APPLY_TO_INTERNSHIP_SCORE_1" FOREIGN KEY (
	"APPLY_ID"
)
REFERENCES "APPLY" (
	"APPLY_ID"
);

ALTER TABLE "INDEPTH_INTERVIEW_SCORE" ADD CONSTRAINT "FK_APPLY_TO_INDEPTH_SCORE_1" FOREIGN KEY (
	"APPLY_ID"
)
REFERENCES "APPLY" (
	"APPLY_ID"
);

ALTER TABLE "ITEM" ADD CONSTRAINT "FK_ANNO_DETAIL_TO_ITEM_1" FOREIGN KEY (
	"DA_ID"
)
REFERENCES "ANNO_DETAIL" (
	"DA_ID"
);

ALTER TABLE "ITEM" ADD CONSTRAINT "FK_ITEM_CODE_TO_ITEM_1" FOREIGN KEY (
	"ITEM_CODE_ID2"
)
REFERENCES "ITEM_CODE" (
	"ITEM_CODE_ID"
);

ALTER TABLE "CAREER" ADD CONSTRAINT "FK_SEEKER_TO_CAREER_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "SEEKER" (
	"MEM_ID"
);

ALTER TABLE "EDUCATION" ADD CONSTRAINT "FK_SEEKER_TO_EDUCATION_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "SEEKER" (
	"MEM_ID"
);

ALTER TABLE "CERTIFICATION" ADD CONSTRAINT "FK_SEEKER_TO_CERTIFICATION_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "SEEKER" (
	"MEM_ID"
);

ALTER TABLE "MYINTRODUCTION" ADD CONSTRAINT "FK_SEEKER_TO_MYINTRODUCTION_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "SEEKER" (
	"MEM_ID"
);

ALTER TABLE "FACILITY" ADD CONSTRAINT "FK_SEEKER_TO_FACILITY_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "SEEKER" (
	"MEM_ID"
);

ALTER TABLE "ACTIVITY" ADD CONSTRAINT "FK_SEEKER_TO_ACTIVITY_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "SEEKER" (
	"MEM_ID"
);

ALTER TABLE "AWARD" ADD CONSTRAINT "FK_SEEKER_TO_AWARD_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "SEEKER" (
	"MEM_ID"
);

ALTER TABLE "COURSE" ADD CONSTRAINT "FK_SEEKER_TO_COURSE_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "SEEKER" (
	"MEM_ID"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_COMPANY_TO_REVIEW_1" FOREIGN KEY (
	"COMPANY_ID"
)
REFERENCES "COMPANY" (
	"CMP_ID"
);

ALTER TABLE "CUT" ADD CONSTRAINT "FK_MEMBER_TO_CUT_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "BLACKLIST" ADD CONSTRAINT "FK_MEMBER_TO_BLACKLIST_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "BOARD_REPORT" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_REPORT_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "COMMENT_REPORT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_REPORT_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "COMMENT_REPORT" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_REPORT_1" FOREIGN KEY (
	"COMM_ID"
)
REFERENCES "COMMENT" (
	"COMM_ID"
);

ALTER TABLE "ALRAM" ADD CONSTRAINT "FK_MEMBER_TO_ALRAM_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "NEWS" ADD CONSTRAINT "FK_ADMIN_TO_NEWS_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "ADMIN" (
	"MEM_ID"
);

ALTER TABLE "CONTEST" ADD CONSTRAINT "FK_ADMIN_TO_CONTEST_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "ADMIN" (
	"MEM_ID"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_MEMBER_TO_NOTICE_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "EXPROD" ADD CONSTRAINT "FK_EXPERT_TO_EXPROD_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "EXPERT" (
	"MEM_ID"
);

ALTER TABLE "EXPROD" ADD CONSTRAINT "FK_EXLPROD_TO_EXPROD_1" FOREIGN KEY (
	"EXLPROD_ID"
)
REFERENCES "EXLPROD" (
	"EXLPROD_ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY (
	"BOARD_ID"
)
REFERENCES "BOARD" (
	"BOARD_ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "EXCART" ADD CONSTRAINT "FK_EXPROD_TO_EXCART_1" FOREIGN KEY (
	"EXPROD_ID"
)
REFERENCES "EXPROD" (
	"EXPROD_ID"
);

ALTER TABLE "EXCART" ADD CONSTRAINT "FK_MEMBER_TO_EXCART_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "EXPERT" ADD CONSTRAINT "FK_SEEKER_TO_EXPERT_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "SEEKER" (
	"MEM_ID"
);

ALTER TABLE "EXPERT" ADD CONSTRAINT "FK_EXFIELD_TO_EXPERT_1" FOREIGN KEY (
	"EXFIELD_ID"
)
REFERENCES "EXFIELD" (
	"EXFIELD_ID"
);

ALTER TABLE "EXPERT" ADD CONSTRAINT "FK_EXJOB_TO_EXPERT_1" FOREIGN KEY (
	"EXJOB_ID"
)
REFERENCES "EXJOB" (
	"EXJOB_ID"
);

ALTER TABLE "INTEREST" ADD CONSTRAINT "FK_PR_TO_INTEREST_1" FOREIGN KEY (
	"PR_NO"
)
REFERENCES "PR" (
	"PR_NO"
);

ALTER TABLE "INTEREST" ADD CONSTRAINT "FK_INCRUITER_TO_INTEREST_1" FOREIGN KEY (
	"MEM_ID2"
)
REFERENCES "INCRUITER" (
	"MEM_ID"
);

ALTER TABLE "TODAYSEE" ADD CONSTRAINT "FK_PR_TO_TODAYSEE_1" FOREIGN KEY (
	"PR_NO"
)
REFERENCES "PR" (
	"PR_NO"
);

ALTER TABLE "TODAYSEE" ADD CONSTRAINT "FK_INCRUITER_TO_TODAYSEE_1" FOREIGN KEY (
	"MEM_ID2"
)
REFERENCES "INCRUITER" (
	"MEM_ID"
);

ALTER TABLE "EXREVIEW" ADD CONSTRAINT "FK_EXCART_TO_EXREVIEW_1" FOREIGN KEY (
	"EXCART_ID"
)
REFERENCES "EXCART" (
	"EXCART_ID"
);

ALTER TABLE "EXEVENT" ADD CONSTRAINT "FK_ADMIN_TO_EXEVENT_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "ADMIN" (
	"MEM_ID"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "INCUM_INTERVIEW" ADD CONSTRAINT "FK_COMPANY_TO_INCUM_1" FOREIGN KEY (
	"CMP_ID"
)
REFERENCES "COMPANY" (
	"CMP_ID"
);

ALTER TABLE "COUNSELING" ADD CONSTRAINT "FK_MEMBER_TO_COUNSELING_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "CORPOR_TRANS" ADD CONSTRAINT "FK_COMPANY_TO_CORPOR_TRANS_1" FOREIGN KEY (
	"COMPANY_ID"
)
REFERENCES "COMPANY" (
	"CMP_ID"
);

ALTER TABLE "TRANS_CALCUL" ADD CONSTRAINT "FK_COMPANY_TO_TRANS_CALCUL_1" FOREIGN KEY (
	"COMPANY_ID"
)
REFERENCES "COMPANY" (
	"CMP_ID"
);

ALTER TABLE "SUPPORT" ADD CONSTRAINT "FK_ADMIN_TO_SUPPORT_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "ADMIN" (
	"MEM_ID"
);

ALTER TABLE "LIKE_COMPANY" ADD CONSTRAINT "FK_SEEKER_TO_LIKE_COMPANY_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "SEEKER" (
	"MEM_ID"
);

ALTER TABLE "LIKE_COMPANY" ADD CONSTRAINT "FK_COMPANY_TO_LIKE_COMPANY_1" FOREIGN KEY (
	"CMP_ID"
)
REFERENCES "COMPANY" (
	"CMP_ID"
);

ALTER TABLE "LIKE_ANNO" ADD CONSTRAINT "FK_SEEKER_TO_LIKE_ANNO_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "SEEKER" (
	"MEM_ID"
);

ALTER TABLE "LIKE_ANNO" ADD CONSTRAINT "FK_ANNO_TO_LIKE_ANNO_1" FOREIGN KEY (
	"ANNO_ID"
)
REFERENCES "ANNO" (
	"ANNO_ID"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "FK_MEMBER_TO_ADMIN_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "PR" ADD CONSTRAINT "FK_SEEKER_TO_PR_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "SEEKER" (
	"MEM_ID"
);

ALTER TABLE "PR" ADD CONSTRAINT "FK_MYRESUME_TO_PR_1" FOREIGN KEY (
	"MYRESUME_ID"
)
REFERENCES "MYRESUME" (
	"MYRESUME_ID"
);

ALTER TABLE "ANNO_WALFARE" ADD CONSTRAINT "FK_WALFARE_TO_ANNO_WALFARE_1" FOREIGN KEY (
	"WALFARE_CODE"
)
REFERENCES "WALFARE" (
	"WALFARE_CODE"
);

ALTER TABLE "ANNO_WALFARE" ADD CONSTRAINT "FK_ANNO_TO_ANNO_WAL" FOREIGN KEY (
	"DA_ID"
)
REFERENCES "ANNO_DETAIL" (
	"DA_ID"
);

ALTER TABLE "ANNO_DETAIL" ADD CONSTRAINT "FK_ANNO_TO_ANNO_DETAIL_1" FOREIGN KEY (
	"ANNO_ID"
)
REFERENCES "ANNO" (
	"ANNO_ID"
);

ALTER TABLE "ANNO_DETAIL" ADD CONSTRAINT "FK_REGION_TO_ANNO_DETAIL_1" FOREIGN KEY (
	"REGION_CODE"
)
REFERENCES "REGION" (
	"REGION_CODE"
);

ALTER TABLE "ANNO_DETAIL" ADD CONSTRAINT "FK_ANNO_JOB_TO_ANNO_DETAIL_1" FOREIGN KEY (
	"JOB_CODE"
)
REFERENCES "ANNO_JOB" (
	"JOB_CODE"
);

ALTER TABLE "ANNO_DETAIL" ADD CONSTRAINT "FK_ANNOEDUCATION_TO_DETAIL_1" FOREIGN KEY (
	"ANNOEDU_CODE"
)
REFERENCES "ANNO_EDUCATION" (
	"ANNOEDU_CODE"
);

ALTER TABLE "ANNO_DETAIL" ADD CONSTRAINT "FK_EMPLTYPE_TO_ANNO_DETAIL_1" FOREIGN KEY (
	"EMPLTYPE_CODE"
)
REFERENCES "EMPLTYPE" (
	"EMPLTYPE_CODE"
);

ALTER TABLE "ANNO_POSITION" ADD CONSTRAINT "FK_POSITION_TO_ANNO_POSITION_1" FOREIGN KEY (
	"POSITION_CODE"
)
REFERENCES "POSITION" (
	"POSITION_CODE"
);

ALTER TABLE "ANNO_POSITION" ADD CONSTRAINT "FK_ANNO_TO_ANNO_POSITION_1" FOREIGN KEY (
	"DA_ID"
)
REFERENCES "ANNO_DETAIL" (
	"DA_ID"
);

ALTER TABLE "UPPER50" ADD CONSTRAINT "FK_COMPANY_TO_UPPER50_1" FOREIGN KEY (
	"CMP_ID"
)
REFERENCES "COMPANY" (
	"CMP_ID"
);

ALTER TABLE "UPPER50" ADD CONSTRAINT "FK_ANNO_JOB_TO_UPPER50_1" FOREIGN KEY (
	"JOB_CODE"
)
REFERENCES "ANNO_JOB" (
	"JOB_CODE"
);

ALTER TABLE "UPPER70" ADD CONSTRAINT "FK_COMPANY_TO_UPPER70_1" FOREIGN KEY (
	"CMP_ID"
)
REFERENCES "COMPANY" (
	"CMP_ID"
);

ALTER TABLE "UPPER70" ADD CONSTRAINT "FK_ANNO_JOB_TO_UPPER70_1" FOREIGN KEY (
	"JOB_CODE"
)
REFERENCES "ANNO_JOB" (
	"JOB_CODE"
);

ALTER TABLE "ITEM_CODE" ADD CONSTRAINT "FK_PROCESS_CODE_TO_ITEM_CODE_1" FOREIGN KEY (
	"PROCESS_CODE_ID"
)
REFERENCES "PROCESS_CODE" (
	"PROCESS_CODE_ID"
);

ALTER TABLE "PROCESS" ADD CONSTRAINT "FK_ANNO_DETAIL_TO_PROCESS_1" FOREIGN KEY (
	"DA_ID"
)
REFERENCES "ANNO_DETAIL" (
	"DA_ID"
);

ALTER TABLE "PROCESS" ADD CONSTRAINT "FK_PROCESS_CODE_TO_PROCESS_1" FOREIGN KEY (
	"PROCESS_CODE_ID"
)
REFERENCES "PROCESS_CODE" (
	"PROCESS_CODE_ID"
);

ALTER TABLE "MYRESUME" ADD CONSTRAINT "FK_SEEKER_TO_MYRESUME_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "SEEKER" (
	"MEM_ID"
);

ALTER TABLE "ASK" ADD CONSTRAINT "FK_MEMBER_TO_ASK_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "MILEAGE" ADD CONSTRAINT "FK_SEEKER_TO_MILEAGE_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "SEEKER" (
	"MEM_ID"
);

ALTER TABLE "PROCESS_FORM" ADD CONSTRAINT "FK_CODE_TO_FORM_1" FOREIGN KEY (
	"PROCESS_CODE_ID"
)
REFERENCES "PROCESS_CODE" (
	"PROCESS_CODE_ID"
);

ALTER TABLE "ITEM_FORM" ADD CONSTRAINT "FK_ITEM_CODE_TO_ITEM_FORM_1" FOREIGN KEY (
	"ITEM_CODE_ID"
)
REFERENCES "ITEM_CODE" (
	"ITEM_CODE_ID"
);

ALTER TABLE "EXINTEREST" ADD CONSTRAINT "FK_EXPROD_TO_EXINTEREST_1" FOREIGN KEY (
	"EXPROD_ID"
)
REFERENCES "EXPROD" (
	"EXPROD_ID"
);

ALTER TABLE "EXINTEREST" ADD CONSTRAINT "FK_MEMBER_TO_EXINTEREST_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "MYRESUME_ITEM" ADD CONSTRAINT "FK_MYRESUME_TO_MYRESUME_ITEM_1" FOREIGN KEY (
	"MYRESUME_ID"
)
REFERENCES "MYRESUME" (
	"MYRESUME_ID"
);
