CREATE TABLE `SEEKER` (
	`MEM_ID`	VARCHAR2(20)	NOT NULL,
	`SEEKER_EXPERT`	VARCHAR2(5)	NULL,
	`SEEKER_BIRTH`	DATE	NULL,
	`SEEKER_GENDER`	VARCHAR2(5)	NULL,
	`Field4`	VARCHAR2(5)	NULL
);

CREATE TABLE `INCRUITER` (
	`MEM_ID`	VARCHAR2(20)	NOT NULL,
	`INCRUITER_APPROVAL`	VARCHAR2(5)	NULL,
	`Key`	VARCHAR2(10)	NOT NULL
);

CREATE TABLE `MEMBER` (
	`MEM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '회원아이디',
	`MEM_DIVISION`	VARCHAR2(5)	NULL,
	`MEM_PASS`	VARCHAR2(20)	NULL,
	`MEM_NM`	VARCHAR2(20)	NULL,
	`MEM_ADDR1`	VARCHAR2(200)	NULL,
	`MEM_ADDR2`	VARCHAR2(200)	NULL,
	`MEM_EMAIL`	VARCHAR2(200)	NULL,
	`MEM_TEL`	VARCHAR2(30)	NULL,
	`MEM_DATE`	DATE	NULL,
	`MEM_CERTIFICATION`	VARCHAR2(10)	NULL,
	`MEM_CARTTOTAL`	NUMBER	NULL,
	`ATCH_FILE_ID`	NUMBER	NOT NULL
);

CREATE TABLE `announcement` (
	`ANNO_ID`	VARCHAR2(20)	NOT NULL	COMMENT '공고아이디',
	`COMPANY_ID`	VARCHAR2(10)	NOT NULL	COMMENT '회사아이디',
	`ANNO_TITLE`	VARCHAR2(50)	NOT NULL	COMMENT '제목',
	`ANNO_CONTENT`	CLOB	NULL	COMMENT '내용',
	`ANNO_STARTDATE`	DATE	NOT NULL	COMMENT '접수시작날짜',
	`ANNO_ENDDATE`	DATE	NOT NULL	COMMENT '접수종료날짜',
	`ANNO_HIT`	NUMBER	NOT NULL	DEFAULT 0	COMMENT '조회수',
	`ANNO_DATE`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '작성일',
	`ANNO_STATE`	NUMBER	NULL	DEFAULT 0	COMMENT '공고글상태
0: 임시저장
1: 공고중
2: 공고만료
3: 삭제됨',
	`ANNO_TYPE`	VARCHAR2(20)	NULL	COMMENT '공고타입
N: 일반채용
B: 블라인드채용',
	`ANNO_MANAGER`	VARCHAR2(20)	NOT NULL	COMMENT '담당자이름',
	`ANNO_TEL`	VARCHAR2(20)	NOT NULL	COMMENT '담당자전화번호',
	`ANNO_MAIL`	VARCHAR2(50)	NOT NULL	COMMENT '담당자이메일',
	`ANNO_WORKENV`	VARCHAR2(500)	NULL	COMMENT '근무환경',
	`INDUSTRY_CODE`	VARCHAR2(20)	NOT NULL	COMMENT '업종코드'
);

CREATE TABLE `JOB_APPLY` (
	`APPLY_ID`	VARCHAR2(20)	NOT NULL	COMMENT '지원아이디',
	`ANNO_ID`	VARCHAR2(20)	NOT NULL	COMMENT '공고아이디',
	`MEM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '구직자아이디',
	`APPLY_RESULT`	VARCHAR2(20)	NOT NULL	DEFAULT 진행중	COMMENT '지원결과',
	`APPLY_DATE`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '지원날짜',
	`APPLY_MODIFY_DATE`	DATE	NULL	DEFAULT SYSDATE	COMMENT '지원수정날짜',
	`APPLY_DELETE`	CHAR(1)	NOT NULL	DEFAULT N	COMMENT '지원삭제여부'
);

CREATE TABLE `RESUME` (
	`APPLY_ID`	VARCHAR2(20)	NOT NULL	COMMENT '지원아이디',
	`RESUME_CAREER`	NUMBER	NULL	DEFAULT 0	COMMENT '경력 점수',
	`RESUME_EDU`	NUMBER	NULL	DEFAULT 0	COMMENT '학력 점수',
	`RESUME_CERT`	NUMBER	NULL	DEFAULT 0	COMMENT '자격증 점수',
	`RESUME_FACILITY`	NUMBER	NULL	DEFAULT 0	COMMENT '기능',
	`RESUME_ACTIVITY`	NUMBER	NULL	DEFAULT 0	COMMENT '주요활동 점수',
	`RESUME_SOCIAL_EXPERIENCE`	NUMBER	NULL	DEFAULT 0	COMMENT '사회경험 점수',
	`RESUME_AWARD`	NUMBER	NULL	DEFAULT 0	COMMENT '수상내역 점수',
	`RESUME_COURSE`	NUMBER	NULL	DEFAULT 0	COMMENT '교육이수 점수',
	`RESUME_DUTY`	NUMBER	NULL	DEFAULT 0	COMMENT '병역사항 점수',
	`RESUME_ADD1`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 입사지원 항목1 점수',
	`RESUME_ADD2`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 입사지원 항목2 점수',
	`RESUME_ADD3`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 입사지원 항목3 점수'
);

CREATE TABLE `INTRODUCTION` (
	`APPLY_ID`	VARCHAR2(20)	NOT NULL	COMMENT '지원아이디',
	`INTRO_GROWTH`	NUMBER	NULL	DEFAULT 0	COMMENT '성장과정 점수',
	`INTRO_PERSONALITY`	NUMBER	NULL	DEFAULT 0	COMMENT '성격 장단점 점수',
	`INTRO_SCHOOLDAY`	NUMBER	NULL	DEFAULT 0	COMMENT '학창시절 점수',
	`INTRO_JOB_EXPERIENCE`	NUMBER	NULL	DEFAULT 0	COMMENT '직무경험',
	`INTRO_MOTIVATION`	NUMBER	NULL	DEFAULT 0	COMMENT '지원동기 점수',
	`INTRO_ASPIRATION`	NUMBER	NULL	DEFAULT 0	COMMENT '입사 후 포부 점수',
	`INTRO_FAMILY`	NUMBER	NULL	DEFAULT 0	COMMENT '가족소개 점수',
	`INTRO_SUBACTIVITY`	NUMBER	NULL	DEFAULT 0	COMMENT '교외활동 점수',
	`INTRO_MAJOR`	NUMBER	NULL	DEFAULT 0	COMMENT '전공선택 점수',
	`INTRO_COURSE`	NUMBER	NULL	DEFAULT 0	COMMENT '생활진로 점수',
	`INTRO_OBJECTIVE`	NUMBER	NULL	DEFAULT 0	COMMENT '희망업무 점수',
	`INTRO_CLUB`	NUMBER	NULL	DEFAULT 0	COMMENT '동아리 점수',
	`INTRO_VOLUNTEER`	NUMBER	NULL	DEFAULT 0	COMMENT '봉사활동 점수',
	`INTRO_INTRO_ADD1`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 자기소개 항목1 점수',
	`INTRO_INTRO_ADD2`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 자기소개 항목2 점수',
	`INTRO_INTRO_ADD3`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 자기소개 항목3 점수'
);

CREATE TABLE `TEST` (
	`APPLY_ID`	VARCHAR2(20)	NOT NULL	COMMENT '지원아이디',
	`TEST_SUBJECT1`	NUMBER	NULL	DEFAULT 0	COMMENT '과목1 점수',
	`TEST_SUBJECT2`	NUMBER	NULL	DEFAULT 0	COMMENT '과목2 점수',
	`TEST_SUBJECT3`	NUMBER	NULL	DEFAULT 0	COMMENT '과목3 점수',
	`TEST_SUBJECT4`	NUMBER	NULL	DEFAULT 0	COMMENT '과목4 점수',
	`TEST_SUBJECT5`	NUMBER	NULL	DEFAULT 0	COMMENT '과목5 점수',
	`TEST_ADDSUBJECT1`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 필기시험 과목1 점수',
	`TEST_SUBJECT_ADD2`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 필기시험 과목2 점수',
	`TEST_SUBJECT_ADD3`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 필기시험 과목3 점수'
);

CREATE TABLE `COMPETENCY` (
	`APPLY_ID`	VARCHAR2(20)	NOT NULL	COMMENT '지원아이디',
	`COMPETENCY_FACIAL`	NUMBER	NULL	DEFAULT 0	COMMENT '시선과 표정 점수',
	`COMPETENCY_POSTURE`	NUMBER	NULL	DEFAULT 0	COMMENT '대면자세 및 행동 점수',
	`COMPETENCY_SPEAKING`	NUMBER	NULL	DEFAULT 0	COMMENT '언어와 표현 점수',
	`COMPETENCY_QUERY_IDENTIFICATION`	NUMBER	NULL	DEFAULT 0	COMMENT '질의파악능력 점수',
	`COMPETENCY_META_COGNITION`	NUMBER	NULL	DEFAULT 0	COMMENT '메타인지 점수',
	`COMPETENCY_RECOGNITION`	NUMBER	NULL	DEFAULT 0	COMMENT '상황인식능력 점수',
	`COMPETENCY_RESOLVE`	NUMBER	NULL	DEFAULT 0	COMMENT '문제해경능력',
	`COMPETENCY_EXPRESSION`	NUMBER	NULL	DEFAULT 0	COMMENT '자기표현력 점수',
	`COMPETENCY_LOGIC`	NUMBER	NULL	DEFAULT 0	COMMENT '논리력 점수',
	`COMPETENCY_LEADERSHIP`	NUMBER	NULL	DEFAULT 0	COMMENT '리더십 점수',
	`COMPETENCY_RELATIONSHIP`	NUMBER	NULL	DEFAULT 0	COMMENT '인간관계 점수',
	`COMPETENCY_COMPETENCY_ADD1`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 역량평가 항목1 점수',
	`COMPETENCY_COMPETENCY_ADD2`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 역량평가 항목2 점수',
	`COMPETENCY_COMPETENCY_ADD3`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 역량평가 항목3 점수'
);

CREATE TABLE `PRACTICE` (
	`APPLY_ID`	VARCHAR2(20)	NOT NULL	COMMENT '지원아이디',
	`PRACTICE_UNDERSTANDING`	NUMBER	NULL	DEFAULT 0	COMMENT '직무이해도 점수',
	`PRACTICE_APPROPRIATION`	NUMBER	NULL	DEFAULT 0	COMMENT '직무접학성 점수',
	`PRACTICE_KNOWLEDGE`	NUMBER	NULL	DEFAULT 0	COMMENT '실무관련지식 점수',
	`PRACTICE_EXPERIENCE`	NUMBER	NULL	DEFAULT 0	COMMENT '실무경험 점수',
	`PRACTICE_ADD1`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 실무면접 항목1 점수',
	`PRACTICE_ADD2`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 실무면접 항목2 점수',
	`PRACTICE_ADD3`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 실무면접 항목3 점수',
	`PRACTICE_ADD4`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 실무면접 항목4 점수',
	`PRACTICE_ADD5`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 실무면접 항목5 점수'
);

CREATE TABLE `DISCUSS` (
	`APPLY_ID`	VARCHAR2(20)	NOT NULL	COMMENT '지원아이디',
	`DISCUSS_POSTURE`	NUMBER	NULL	DEFAULT 0	COMMENT '토론자세 점수',
	`DISCUSS_SUBJECT_IDENTIFICATION`	NUMBER	NULL	DEFAULT 0	COMMENT '주제파악 점수',
	`DISCUSS_PROBLEM_IDENTIFICATION`	NUMBER	NULL	DEFAULT 0	COMMENT '문제파악 점수',
	`DISCUSS_RESOLVE`	NUMBER	NULL	DEFAULT 0	COMMENT '해결방안 점수',
	`DISCUSS_QUERY_IDENTIFICATION`	NUMBER	NULL	DEFAULT 0	COMMENT '질의파악능력',
	`DISCUSS_PROGRESS`	NUMBER	NULL	DEFAULT 0	COMMENT '토론진행 점수',
	`DISCUSS_ADD1`	NUMBER	NULL	DEFAULT 0	COMMENT '토론 추가항목1 점수',
	`DISCUSS_ADD2`	NUMBER	NULL	DEFAULT 0	COMMENT '토론 추가항목2 점수',
	`DISCUSS_ADD3`	NUMBER	NULL	DEFAULT 0	COMMENT '토론 추가항목3 점수'
);

CREATE TABLE `INTERNSHIP` (
	`APPLY_ID`	VARCHAR2(20)	NOT NULL	COMMENT '지원아이디',
	`INTERN_ACHIVEMENT`	NUMBER	NULL	DEFAULT 0	COMMENT '업무달성도',
	`INTERN_TRUST`	NUMBER	NULL	DEFAULT 0	COMMENT '업무신뢰도 점수',
	`INTERN_CREATIVITY`	NUMBER	NULL	DEFAULT 0	COMMENT '창의력 점수',
	`INTERN_KNOWLEDGE`	NUMBER	NULL	DEFAULT 0	COMMENT '직무지식',
	`INTERN_DETERMINATION`	NUMBER	NULL	DEFAULT 0	COMMENT '판단력',
	`INTERN_COOPERATION`	NUMBER	NULL	DEFAULT 0	COMMENT '협조성 점수',
	`INTERN_OBSERVATION`	NUMBER	NULL	DEFAULT 0	COMMENT '규율성',
	`INTERN_ACTIVENESS`	NUMBER	NULL	DEFAULT 0	COMMENT '적극성 점수',
	`INTERN_RESPONSIBILITY`	NUMBER	NULL	DEFAULT 0	COMMENT '책임감 점수',
	`INTERN_EFFICIENCY`	NUMBER	NULL	DEFAULT 0	COMMENT '효율성 점수',
	`INTERN_CHALLENGE`	NUMBER	NULL	DEFAULT 0	COMMENT '도전의식',
	`INTERN_COMMUNITY`	NUMBER	NULL	DEFAULT 0	COMMENT '공동체 점수',
	`INTERN_ATTITUDE`	NUMBER	NULL	DEFAULT 0	COMMENT '태도 점수',
	`INTERN_DELIGENCY`	NUMBER	NULL	DEFAULT 0	COMMENT '성실성 점수',
	`INTERN_ADD1`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 인턴십 항목1 점수',
	`INTERN_ADD2`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 인턴십 항목2 점수',
	`INTERN_ADD3`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 인턴십 항목3 점수'
);

CREATE TABLE `INDEPTH_INTERVIEW` (
	`APPLY_ID`	VARCHAR2(20)	NOT NULL	COMMENT '지원아이디',
	`INDPETH_INTRODUCTION`	NUMBER	NULL	DEFAULT 0	COMMENT '자기소개 점수',
	`INDEPTH_MOTIVATION`	NUMBER	NULL	DEFAULT 0	COMMENT '회사지원동기 점수',
	`INDEPTH_PROSANDCONS`	NUMBER	NULL	DEFAULT 0	COMMENT '장단점',
	`INDEPTH_HOBBY`	NUMBER	NULL	DEFAULT 0	COMMENT '취미 점수',
	`INDEPTH_SPECIALTY`	NUMBER	NULL	DEFAULT 0	COMMENT '특기 점수',
	`INDEPTH_RELIEVE`	NUMBER	NULL	DEFAULT 0	COMMENT '스트레스해소 점수',
	`INDEPTH_ROLE_MODEL`	NUMBER	NULL	DEFAULT 0	COMMENT '존경인물 점수',
	`INDEPTH_ORGANIZATION`	NUMBER	NULL	DEFAULT 0	COMMENT '조직생활 점수',
	`INDEPTH_AGGRESSIVENESS`	NUMBER	NULL	DEFAULT 0	COMMENT '공격형 점수',
	`INDEPTH_LEADERSHIP`	NUMBER	NULL	DEFAULT 0	COMMENT '리더십 점수',
	`INDEPTH_TEAMWORK`	NUMBER	NULL	DEFAULT 0	COMMENT '팀워크 점수',
	`INDEPTH_CONFLICT`	NUMBER	NULL	DEFAULT 0	COMMENT '갈등해결 점수',
	`INDEPTH_SACRIFICE`	NUMBER	NULL	DEFAULT 0	COMMENT '희생',
	`INDEPTH_ACHIVEMENT`	NUMBER	NULL	DEFAULT 0	COMMENT '성취경험 점수',
	`INDEPTH_WLBALANCE`	NUMBER	NULL	DEFAULT 0	COMMENT '워라밸 점수',
	`INPEPTH_NIGHT_SHIFT`	NUMBER	NULL	DEFAULT 0	COMMENT '야근 점수',
	`INDEPTH_UNION`	NUMBER	NULL	DEFAULT 0	COMMENT '노조 점수',
	`INDEPTH_STRIKE`	NUMBER	NULL	DEFAULT 0	COMMENT '파업 점수',
	`INDEPTH_SENIOR`	NUMBER	NULL	DEFAULT 0	COMMENT '상사갈등 점수',
	`INDEPTH_ADD1`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 임원면접 항목1 점수',
	`INDEPTH_ADD2`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 임원면접 항목2 점수',
	`INDEPTH_ADD3`	NUMBER	NULL	DEFAULT 0	COMMENT '추가 임원면접 항목3 점수'
);

CREATE TABLE `PROCESS_ITEM` (
	`PROCESS_ID`	VARCHAR2(20)	NOT NULL	COMMENT '채용과정아이디',
	`ANNO_ID`	VARCHAR2(20)	NOT NULL	COMMENT '공고아이디',
	`ITEM_CODE_ID`	VARCHAR2(20)	NOT NULL	COMMENT '항목코드',
	`PROCESS_ITEM_ASK`	VARCHAR2(200)	NOT NULL	COMMENT '질문'
);

CREATE TABLE `PROCESS_CODE` (
	`PROCESS_CODE_ID`	VARCHAR2(20)	NOT NULL	COMMENT '분류코드',
	`PROCESS_CODE_NO`	VARCHAR2(20)	NOT NULL	COMMENT '분류번호',
	`PROCESS_CODE_NAME`	VVARCHAR2(30)	NOT NULL	COMMENT '채용과정명'
);

CREATE TABLE `CAREER` (
	`CAREER_ID`	VARCHAR2(20)	NOT NULL	COMMENT '경력아이디',
	`CAREER_CATEGORY`	VARCHAR2(30)	NULL	DEFAULT 자유분야	COMMENT '업종',
	`CARRER_COMPANY_NAME`	VARCHAR2(50)	NOT NULL	DEFAULT 프리랜서	COMMENT '직장명',
	`CARRER_TASK`	VARCHAR2(50)	NULL	COMMENT '직무',
	`CAREER_CLASS`	VARCHAR2(20)	NULL	COMMENT '직급',
	`CAREER_JOIN_DATE`	DATE	NULL	COMMENT '입사일',
	`CAREER_RESIGN_DATE`	DATE	NULL	COMMENT '퇴사일',
	`CAREER_SALARY`	NUMBER	NULL	DEFAULT 0	COMMENT '연봉',
	`CAREER_ANNUAL`	NUMBER	NULL	DEFAULT 0	COMMENT '연차',
	`MEM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '구직자아이디'
);

CREATE TABLE `EDUCATION` (
	`EDU_ID`	VARCHAR2(20)	NOT NULL	COMMENT '학력아이디',
	`EDU_NAME`	VARCHAR2(50)	NULL	COMMENT '학교명',
	`EDU_DEPARTMENT`	VARCHAR2(50)	NOT NULL	COMMENT '학과명',
	`EDU_MAJOR`	VARCHAR2(50)	NOT NULL	COMMENT '전공',
	`EDU_ENTERED_DATE`	DATE	NULL	COMMENT '입학일',
	`EDU_GRADUATED_DATE`	DATE	NOT NULL	COMMENT '졸업일,중퇴일,자퇴일',
	`EDU_STATUS`	VARCHAR2(20)	NULL	DEFAULT 재학중	COMMENT '상태',
	`EDU_SCORE`	NUMBER	NOT NULL	DEFAULT 0	COMMENT '학점',
	`EDU_SCORE_STANDARD`	NUMBER	NOT NULL	DEFAULT 0	COMMENT '기준학점',
	`MEM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '구직자아이디'
);

CREATE TABLE `CERTIFICATION` (
	`CERT_ID`	VARCHAR2(20)	NOT NULL	COMMENT '자격증아이디',
	`CERT_NO`	VARCHAR2(30)	NOT NULL	COMMENT '자격번호',
	`CERT_NAME`	VARCHAR2(50)	NOT NULL	COMMENT '자격증명',
	`CERT_DATE`	DATE	NOT NULL	COMMENT '발급일',
	`CERT_INSTITUTION`	VARCHAR2(50)	NOT NULL	COMMENT '시행부처',
	`MEM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '구직자아이디'
);

CREATE TABLE `MYINTRODUCTION` (
	`MYINTRO_ID`	VARCHAR2(20)	NOT NULL	COMMENT '내 자기소개서 아이디',
	`MEM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '내 아이디',
	`MYINTRO_GROWTH`	VARCHAR2(2000)	NULL	COMMENT '내 성장과정',
	`MYINTRO_PERSONALITY`	VARCHAR2(2000)	NULL	COMMENT '내 성격 장단점',
	`MYINTRO_SCHOOLDAY`	VARCHAR2(2000)	NULL	COMMENT '내 학창시절',
	`MYINTRO_JOB_EXPRIENCE`	VARCHAR2(2000)	NULL	COMMENT '내 직무경험',
	`MYINTRO_MOTIVATION`	VARCHAR2(2000)	NULL	COMMENT '내 지원동기',
	`MYINTRO_ASPIRATION`	VARCHAR2(2000)	NULL	COMMENT '내 입사 후 포부',
	`MYINTRO_FAMILY`	VARCHAR2(2000)	NULL	COMMENT '내 가족소개',
	`MYINTRO_SUBACTIVITY`	VARCHAR2(2000)	NULL	COMMENT '내 교외활동',
	`MYINTRO_MAJOR`	VARCHAR2(2000)	NULL	COMMENT '내 전공선택',
	`MYINTRO_COURSE`	VARCHAR2(2000)	NULL	COMMENT '생활진로',
	`MYINTRO_OBJECTIVE`	VARCHAR2(2000)	NULL	COMMENT '내 희망업무',
	`MYINTRO_CLUB`	VARCHAR2(2000)	NULL	COMMENT '내 동아리',
	`MYINTRO_VOLUNTEER`	VARCHAR2(2000)	NULL	COMMENT '내 봉사활동',
	`MYINTRO_ADD1`	VARCHAR2(2000)	NULL	COMMENT '내 추가항목1',
	`MYINTRO_ADD2`	VARCHAR2(2000)	NULL	COMMENT '내 추가항목2',
	`MYINTRO_ADD3`	VARCHAR2(2000)	NULL	COMMENT '내 추가항목3'
);

CREATE TABLE `FACILITY` (
	`FACILITY_ID`	VARCHAR2(20)	NOT NULL	COMMENT '기능아이디',
	`FACILITY_NAME`	VARCHAR2(50)	NOT NULL	COMMENT '기능명',
	`FACILITY_CATEGORY`	VARCHAR2(50)	NOT NULL	COMMENT '기능종류',
	`FACILITY_LEVEL`	VARCHAR2(30)	NOT NULL	DEFAULT 초급	COMMENT '수준',
	`FACILITY_GETDATE`	DATE	NOT NULL	COMMENT '취득일',
	`FACILITY_PERIOD`	NUMBER	NOT NULL	DEFAULT 0	COMMENT '훈련기간',
	`MEM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '구직자아이디'
);

CREATE TABLE `ACTIVITY` (
	`ACT_ID`	VARCHAR2(20)	NOT NULL	COMMENT '주요활동아이디',
	`ACT_NAME`	VARCHAR2(50)	NOT NULL	COMMENT '주요활동명',
	`ACT_CATEGORY`	VARCAHR2(50)	NOT NULL	COMMENT '주요활동종류',
	`ACT_INSTITUTION`	VARCAHR2(50)	NULL	COMMENT '주요활동기관',
	`ACT_PERIOD`	NUMBER	NOT NULL	DEFAULT 0	COMMENT '주요활동기간',
	`MEM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '회원아이디'
);

CREATE TABLE `AWARD` (
	`AWARD_ID`	VARCHAR2(20)	NOT NULL	COMMENT '수상내역아이디',
	`AWARD_COMPETITION`	VARCHAR2(50)	NOT NULL	COMMENT '수상대회명',
	`AWARD_NAME`	VARCHAR2(50)	NOT NULL	COMMENT '수상명',
	`AWARD_CATEGORY`	VARCHAR2(50)	NOT NULL	COMMENT '수상대회종류',
	`AWARD_DATE`	DATE	NOT NULL	COMMENT '수상날짜',
	`AWARD_INSTITUTION`	VARCHAR2(50)	NOT NULL	COMMENT '수상기관',
	`MEM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '회원아이디'
);

CREATE TABLE `COURSE` (
	`COURSE_ID`	VARCHAR2(20)	NOT NULL	COMMENT '교육이수아이디',
	`COURSE_NAME`	VARCHAR2(50)	NOT NULL	COMMENT '교육명',
	`COURSE_CATEGORY`	VARCHAR2(30)	NOT NULL	COMMENT '교육종류',
	`COURSE_INSTITUTION`	VARCHAR2(50)	NOT NULL	COMMENT '교육기관',
	`COURSE_PERIOD`	NUMBER	NOT NULL	DEFAULT 0	COMMENT '교육기간',
	`MEM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '회원아이디'
);

CREATE TABLE `REVIEW` (
	`REVIEW_ID`	VARCHAR2(20)	NOT NULL	COMMENT '리뷰아이디',
	`MEM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '회원아이디',
	`REVIEW_TITLE`	VARCHAR2(50)	NOT NULL	COMMENT '리뷰제목',
	`REVIEW_CONTENT`	VARCHAR2(1000)	NULL	COMMENT '리뷰내용',
	`REVIEW_DATE`	DATE	NULL	COMMENT '리뷰날짜',
	`REVIEW_ATTATCH`	VARCHAR(255)	NOT NULL	COMMENT '리뷰첨부파일',
	`REVIEW_SCORE`	NUMBER(1)	NOT NULL	COMMENT '리뷰별점',
	`COMPANY_ID`	VARCHAR2(10)	NOT NULL,
	`REVIEW_CHECK`	NUMBER(1)	NULL	DEFAULT 0	COMMENT '리뷰승인여부'
);

CREATE TABLE `CUT` (
	`CUT_ID`	VARCHAR2(20)	NOT NULL	COMMENT '차단아이디',
	`CUT_DATE`	DATE	NULL	COMMENT '차단일자',
	`CUT_CONTENT`	VARCHAR2(1000)	NOT NULL	COMMENT '차단사유',
	`MEM_ID`	VARCHAR2(10)	NOT NULL	COMMENT '차단당한회원아이디',
	`CUT_CHECK`	NUMBER(1)	NULL	DEFAULT 0	COMMENT '차단만료여부'
);

CREATE TABLE `BLACKLIST` (
	`BLACKLIST_ID`	VARCHAR2(20)	NOT NULL	COMMENT '블랙리스트아이디',
	`BLACKLIST_DATE`	DATE	NULL	COMMENT '블랙리스트된 날짜',
	`BLACKLIST_CONTENT`	VARCHAR2(1000)	NOT NULL	COMMENT '블랙리스트 사유',
	`MEM_ID`	VARCHAR2(10)	NOT NULL	COMMENT '블랙당한회원아이디',
	`BLACKLIST_CHECK`	NUMBER(1)	NULL	DEFAULT 0	COMMENT '블랙만료여부'
);

CREATE TABLE `COMPANY` (
	`COMPANY_ID`	VARCHAR2(20)	NOT NULL	COMMENT '회사아이디',
	`COMPANY_NUMBER`	VARCHAR2(20)	NOT NULL	COMMENT '법인등록번호',
	`COMPANY_NAME`	VARCHAR2(100)	NOT NULL	COMMENT '법인명',
	`COMPANY_REPRESENTATIVE_NAME`	VARCHAR2(20)	NOT NULL	COMMENT '회사대표자성명',
	`COMPANY_BUSINESS_NUMBER`	VARCHAR2(20)	NOT NULL	COMMENT '사업자등록번호',
	`COMPANY_DEFAULT_ADRESS`	VARCHAR2(100)	NOT NULL	COMMENT '회사기본주소',
	`COMPANY_DETAIL_ADRESS`	VARCHAR2(100)	NOT NULL	COMMENT '회사상세주소',
	`COMPANY_ZIP`	VARCHAR2(20)	NOT NULL	COMMENT '회사우편번호',
	`COMPANY_PHONE`	VARCHAR2(20)	NOT NULL	COMMENT '회사전화번호',
	`COMPANY_ESTABLISHMENT_DATE`	DATE	NOT NULL	COMMENT '회사설립일자',
	`COMPANY_SMALL_MEDIUM_ENTERPRISE_STATUS`	VARCHAR2(20)	NOT NULL	COMMENT '회사형태',
	`COMPANY_EMPLOYEES_NUMBER`	VARCHAR2(100)	NOT NULL	COMMENT '회사종업원수',
	`COMPANY_AVERAGE_CONTINUOUS_WORK`	VARCHAR2(100)	NOT NULL	COMMENT '종업원평균근속기간내용',
	`COMPANY_PERSON_AVERAGE_SALARY`	VARCHAR2(100)	NOT NULL	COMMENT '회사1인평균급여금액',
	`COMPANY_MAIN_BUSINESS_NAME`	VARCHAR2(100)	NOT NULL	COMMENT '회사주요사업명',
	`COMPANY_GRADE`	VARCHAR2(100)	NOT NULL	COMMENT '회사등급',
	`COMPANY_SCORE`	NUMBER(10)	NOT NULL	COMMENT '회사평점',
	`COMPANY_REVIEW`	VARCHAR2(100)	NOT NULL	COMMENT '회사리뷰'
);

CREATE TABLE `BOARD_REPORT` (
	`BOARD_REPORT_ID`	VARCHAR2(20)	NOT NULL	COMMENT '게시판신고아이디',
	`MEM_ID2`	VARCHAR2(10)	NOT NULL,
	`Field2`	VARCHAR(255)	NULL,
	`BOARD_REPORT_NO`	NUMBER	NOT NULL	COMMENT '게시판신고글번호',
	`BOARD_REPORT_DATE`	DATE	NULL	COMMENT '신고일자',
	`BOARD_REPORT_REASON`	VARCHAR2(1000)	NOT NULL	COMMENT '신고사유'
);

CREATE TABLE `COMMENT_REPORT` (
	`COMMENT_REPORT_ID`	VARCHAR2(20)	NOT NULL	COMMENT '댓글신고아이디',
	`MEM_ID2`	VARCHAR2(10)	NOT NULL	COMMENT '신고한회원아이디',
	`Field2`	VARCHAR(255)	NULL,
	`COMMENT_REPORT_DATE`	DATE	NULL	COMMENT '신고일자',
	`COMMENT_REPORT_REASON`	VARCHAR2(1000)	NULL	COMMENT '신고사유',
	`COMM_ID`	VARCHAR2(10)	NOT NULL	COMMENT '댓글ID'
);

CREATE TABLE `BANKING` (
	`BANKING_ACCOUNT`	VARCHAR2(50)	NOT NULL,
	`BANKING_BANK`	VARCHAR2(20)	NULL,
	`BANKING_NM`	VARCHAR2(20)	NULL,
	`BANKING_BALANCE`	NUMBER	NULL,
	`MEM_ID`	VARCHAR2(20)	NOT NULL
);

CREATE TABLE `ALRAM` (
	`ALRAM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '알림아이디',
	`ALRAM_CONTENT`	VARCHAR2(500)	NOT NULL	COMMENT '알림내역',
	`ALRAM_DATE`	DATE	NULL	COMMENT '알림날짜',
	`ALRAM_READ_STATUS`	NUMBER(1)	NULL	DEFAULT 0	COMMENT '알림읽기여부',
	`MEM_ID`	VARCHAR2(10)	NOT NULL	COMMENT '알림보낸회원아이디',
	`MEM_ID2`	VARCHAR2(10)	NOT NULL	COMMENT '알림받은회원아이디'
);

CREATE TABLE `HELP` (
	`HELP_ID`	VARCHAR2(20)	NOT NULL	COMMENT '도움말ID',
	`MEM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '회원아이디',
	`HELP_SORT`	VARCHAR2(50)	NOT NULL	COMMENT '구분',
	`HELP_CATE`	VARCHAR2(50)	NOT NULL	COMMENT '분류명',
	`HELP_TITLE`	VARCHAR2(100)	NOT NULL	COMMENT '제목',
	`HELP_CONTENT`	CLOB	NOT NULL	COMMENT '내용',
	`HELP_DATE`	DATE	NOT NULL	COMMENT '작성일',
	`HELP_MODI_DATE`	DATE	NOT NULL	COMMENT '수정일',
	`HELP_VIEWS`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '조회수'
);

CREATE TABLE `NEWS` (
	`NEWS_NO`	VARCHAR2(10)	NOT NULL	COMMENT '뉴스 번호',
	`NEWS_NAME`	VARCHAR2(50)	NOT NULL	COMMENT '제목',
	`NEWS_DATE`	DATE	NOT NULL	COMMENT '작성일',
	`NEWS_FIELD`	VARCHAR2(50)	NULL	COMMENT '분야',
	`NEWS_LOOK`	VARCHAR2(10)	NULL	COMMENT '조회수',
	`Key2`	VARCHAR(255)	NOT NULL,
	`NEWS_CONTENT`	VARCHAR2(500)	NOT NULL	COMMENT '내용'
);

CREATE TABLE `CONTEST` (
	`CONT_NO`	VARCHAR2(10)	NOT NULL	COMMENT '공모전 번호',
	`CONT_NAME`	VARCHAR2(50)	NOT NULL	COMMENT '공모전명',
	`CONT_CO`	VARCHAR2(50)	NOT NULL	COMMENT '주관 기관',
	`CONT_START`	VARCHAR2(20)	NOT NULL	COMMENT '시작일',
	`CONT_DEAD`	VARCHAR2(20)	NOT NULL	COMMENT '마감일',
	`CONT_FIELD`	VARCHAR2(50)	NULL	COMMENT '공모분야',
	`CONT_IMG`	VARCHAR2(100)	NULL	COMMENT '사진',
	`CONT_CONTENT`	VARCHAR2(500)	NOT NULL	COMMENT '내용',
	`Key2`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `NOTICE` (
	`NOTICE_ID`	VARCHAR2(20)	NOT NULL	COMMENT '공지사항ID',
	`MEM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '회원아이디',
	`NOTICE_SORT`	VARCHAR2(50)	NOT NULL	COMMENT '구분',
	`NOTICE_TITLE`	VARCHAR2(100)	NOT NULL	COMMENT '제목',
	`NOTICE_DATE`	DATE	NOT NULL	COMMENT '작성일',
	`NOTICE_CONTENT`	CLOB	NOT NULL	COMMENT '내용',
	`NOTICE_STATE`	NUMBER(5)	NOT NULL	DEFAULT 접수	COMMENT '처리상태',
	`NOTICE_HIT`	NUMBER(4,0)	NULL	DEFAULT 0	COMMENT '조회수'
);

CREATE TABLE `EXPROD` (
	`EXPROD_ID`	VARCHAR2(20)	NOT NULL,
	`EXPROD_START`	DATE	NULL,
	`EXPROD_END`	DATE	NULL,
	`EXPROD_TARGET`	VARCHAR2(30)	NULL,
	`EXPROD_NM`	VARCHAR2(100)	NULL,
	`EXPROD_PRICE`	NUMBER	NULL,
	`EXPROD_WAY`	VARCHAR2(100)	NULL,
	`EXPROD_TIME`	DATE	NULL,
	`EXPROD_DETAIL`	VARCHAR2(2000)	NULL,
	`MEM_ID`	VARCHAR2(20)	NOT NULL,
	`EXPROD_APROVAL`	VARCHAR2(10)	NULL,
	`EXLPROD_ID`	VARCHAR2(10)	NOT NULL,
	`ATCH_FILE_ID`	NUMBER	NOT NULL
);

CREATE TABLE `COMMENT` (
	`COMM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '댓글ID',
	`COMM_DATE`	DATE	NOT NULL	COMMENT '작성일',
	`TOTAL_COMM`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '댓글수',
	`COMM_CONTENT`	VARCHAR2(100)	NOT NULL	COMMENT '댓글내용',
	`GOOD_COMM`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '댓글공감수',
	`COMM_WRITER`	VARCHAR2(50)	NOT NULL	COMMENT '댓글작성자',
	`BOARD_ID`	VARCHAR2(20)	NOT NULL	COMMENT '게시판ID'
);

CREATE TABLE `REPORT` (
	`REPORT_ID`	VARCHAR2(20)	NOT NULL,
	`MEM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '회원아이디',
	`MEM_ID2`	VARCHAR2(20)	NOT NULL	COMMENT '회원아이디',
	`REPORT_SORT`	VARCHAR2(50)	NOT NULL	COMMENT '구분',
	`REPORT_CONTENT`	VARCHAR2(100)	NOT NULL	COMMENT '내용',
	`REPORT_STATE`	NUMBER(5)	NULL
);

CREATE TABLE `EXCART` (
	`EXCART_ID`	VARCHAR2(20)	NOT NULL,
	`EXPROD_ID`	VARCHAR2(10)	NOT NULL,
	`MEM_ID`	VARCHAR2(20)	NOT NULL
);

CREATE TABLE `EXPERT` (
	`MEM_ID`	VARCHAR2(20)	NOT NULL,
	`EXPERT_APPROVAL`	VARCHAR2(10)	NULL,
	`EXPERT_APPROVAL_DATE`	DATE	NULL,
	`EXPERT_INTRODUCTION`	VARCHAR2(200)	NULL,
	`EXPERT_JOINPATH`	VARCHAR2(30)	NULL,
	`EXPERT_FILED`	VARCHAR2(10)	NULL,
	`EXPERT_TAG`	VARCHAR2(40)	NULL,
	`EXPERT_ADDR`	VARCHAR2(200)	NULL,
	`EXPERT_TEL`	VARCHAR2(20)	NULL,
	`EXPERT_EMAIL`	VARCHAR2(30)	NULL,
	`EXLPROD_ID`	VARCHAR2(20)	NOT NULL,
	`EXPRET_MONEY`	NUMBER	NULL
);

CREATE TABLE `INTEREST` (
	`INTE_NO`	VARCHAR2(10)	NOT NULL	COMMENT '관심인재 번호',
	`INTE_DATE`	DATE	NOT NULL	COMMENT '스크랩 날짜',
	`Key2`	VARCHAR(255)	NOT NULL,
	`Key33`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `TODAYSEE` (
	`TODAY_NO`	VARCHAR2(10)	NOT NULL	COMMENT '조회 번호',
	`Key2`	VARCHAR(255)	NOT NULL,
	`Key3`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `EXREVIEW` (
	`EXREVIEW_ID`	VARCHAR2(20)	NOT NULL,
	`EXREVIEW_NM`	VARCHAR2(100)	NULL,
	`EXREVIEW_WRITER`	VARCHAR2(50)	NULL,
	`EXREVIEW_PASS`	VARCHAR2(20)	NULL,
	`EXREVIEW_CONTENT`	VARCHAR2(2000)	NULL,
	`EXREVIEW_HITS`	NUMBER	NULL,
	`EXCART_ID`	VARCHAR2(10)	NOT NULL,
	`EXREVIEW_DATE`	DATE	NULL,
	`EXREVIEW_SCORE`	VARCHAR2(5)	NULL
);

CREATE TABLE `EXEVENT` (
	`EXEVENT_ID`	VARCHAR2(20)	NOT NULL,
	`EXEVENT_NM`	VARCHAR2(50)	NULL,
	`EXEVENT_CONTENT`	VARCHAR2(2000)	NULL,
	`EXEVENT_START`	DATE	NULL,
	`EXEVENT_END`	DATE	NULL,
	`Key2`	VARCHAR2(10)	NOT NULL,
	`ATCH_FILE_ID`	NUMBER	NOT NULL
);

CREATE TABLE `BOARD` (
	`BOARD_ID`	VARCHAR2(20)	NOT NULL	COMMENT '게시판ID',
	`MEM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '회원아이디',
	`BOARD_NO`	NUMBER(5)	NOT NULL	COMMENT '순번',
	`SUB_CATE`	VARCHAR2(50)	NOT NULL	COMMENT '주제별분류명',
	`BOARD_VIEWS`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '조회수',
	`JOB_CATE`	VARCHAR2(50)	NOT NULL	COMMENT '직무별분류명',
	`BOARD_TITLE`	VARCHAR2(50)	NOT NULL	COMMENT '제목',
	`BOARD_CONTENT`	CLOB	NOT NULL	COMMENT '내용',
	`BOARD_WRITER`	VARCHAR2(50)	NOT NULL	COMMENT '작성자',
	`BOARD_DATE`	DATE	NOT NULL	COMMENT '작성일',
	`TOTAL_GOOD`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '전체공감수',
	`BOARD_GOOD`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '좋아요',
	`BOARD_FUN`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '재밌어요',
	`BOARD_HELP`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '도움돼요',
	`BOARD_CHEERUP`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '힘내요'
);

CREATE TABLE `INCUMBENT_INTERVIEW` (
	`INTERVIEW_ID`	VARCHAR2(20)	NOT NULL	COMMENT '현직자인터뷰ID',
	`ANNO_ID`	VARCHAR2(20)	NOT NULL	COMMENT '현직자인터뷰ID',
	`JOB_CATE`	VARCHAR2(50)	NOT NULL	COMMENT '직무별분류명',
	`RECRU_STATUS`	NUMBER(5)	NOT NULL	COMMENT '채용여부',
	`INCUM_TITLE`	VARCHAR2(50)	NOT NULL	COMMENT '제목',
	`COMPANY_NAME`	VARCHAR2(50)	NULL	COMMENT '회사명',
	`DEPARTMENT_NAME`	VARCHAR2(50)	NULL	COMMENT '부서명',
	`INCUM_NAME`	VARCHAR2(50)	NOT NULL	COMMENT '작성자',
	`INCUM_DATE`	DATE	NOT NULL	COMMENT '작성일',
	`INCUM_VIEWS`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '조회수',
	`INCUM_CONTENT`	CLOB	NOT NULL	COMMENT '내용',
	`COMPANY_ID`	VARCHAR2(20)	NOT NULL	COMMENT '회사아이디'
);

CREATE TABLE `COUNSELING` (
	`COUN_NO`	VARCHAR2(20)	NOT NULL	COMMENT '게시판ID',
	`MEM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '회원아이디',
	`COUN_TITLE`	VARCHAR2(50)	NULL	COMMENT '제목',
	`COUN_CONTENT`	CLOB	NULL	COMMENT '내용',
	`COUN_DATE`	DATE	NULL	DEFAULT SYSDATE	COMMENT '작성일',
	`COUN_STATE`	NUMBER	NULL	DEFAULT 1	COMMENT '글상태
0: 삭제됨
1: 등록됨',
	`COUN_PARENT`	VARCHAR2(20)	NULL	COMMENT '부모글'
);

CREATE TABLE `RESUME_FORM` (
	`RESUME_FORM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '이력서양식ID',
	`RESUME_FORM_CATE`	VARCHAR2(100)	NOT NULL	COMMENT '이력서분류명',
	`FORM_TITLE`	VARCHAR2(100)	NOT NULL	COMMENT '제목',
	`DOWNLOAD`	NUMBER(20)	NOT NULL	DEFAULT 0	COMMENT '다운로드수',
	`FORM_VIEWS`	NUMBER(20)	NOT NULL	DEFAULT 0	COMMENT '조회수',
	`FORM_CONTENT`	VARCHAR2	NOT NULL	COMMENT '내용'
);

CREATE TABLE `TRANSPARENCY_FORM` (
	`Key`	VARCHAR2(20)	NOT NULL	COMMENT '회사아이디',
	`RECRU_NO`	VARCHAR2(50)	NULL	COMMENT '채용횟수',
	`TYPE_OF_WORK`	VARCHAR2(50)	NULL	COMMENT '근무형태',
	`YOUTH_BENEFIT`	VARCHAR2(50)	NULL	COMMENT '청년혜택',
	`SOCIAL_INSURANCE`	VARCHAR2(50)	NULL	COMMENT '4대보험',
	`INTER_EXTER`	VARCHAR2(50)	NULL	COMMENT '내,외근비율',
	`NUM_OF_YEARS`	VARCHAR2(50)	NULL	COMMENT '근속연수',
	`AGE`	VARCHAR2(50)	NULL	COMMENT '연령구성',
	`OVERTIME`	VARCHAR2(50)	NULL	COMMENT '야근빈도',
	`COMPANY_HISTORY`	VARCHAR2(50)	NULL	COMMENT '업력',
	`ENTER_TYPE`	VARCHAR2(50)	NULL	COMMENT '기업형태',
	`NUM_OF_EMP`	VARCHAR2(50)	NULL	COMMENT '직원수',
	`BENEFIT`	VARCHAR2(50)	NULL	COMMENT '복리후생',
	`DINING_TOGETHER`	VARCHAR2(50)	NULL	COMMENT '회식빈도',
	`TRANS_DATE`	DATE	NOT NULL	COMMENT '등록일'
);

CREATE TABLE `TRANSPARENCY` (
	`Key2`	VARCHAR2(20)	NOT NULL	COMMENT '회사아이디',
	`Key`	VARCHAR2(20)	NOT NULL	COMMENT '리뷰아이디',
	`FORM_WRITING`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '양식작성개수',
	`INCOME_INDUSTRY`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '업종별연봉',
	`JOIN_RESIGN_RATIO`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '입,퇴사자 추이',
	`AVER_SALARY_RANK`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '평균연봉순위',
	`SIMILAR_INDUSTRY`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '동종업계순위',
	`SALES`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '매출액',
	`BUSINESS_PROFITS`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '영업이익',
	`CURRENT_PROFIT`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '당기순이익',
	`LOCATION_IN_INDUSTRY`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '산업내위치',
	`CORPORATE_RATING`	VARCHAR2(50)	NOT NULL	COMMENT '기업등급',
	`INCREASE_EMPLOYEES`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '사원수증가',
	`REVIEW_SCORE`	NUMBER(5)	NOT NULL	DEFAULT 0	COMMENT '리뷰평점',
	`RENEWAL`	DATE	NOT NULL	COMMENT '갱신일'
);

CREATE TABLE `SUPPORT` (
	`SUPPORT_ID`	VARCHAR2(20)	NOT NULL	COMMENT '게시판ID',
	`MEM_ID`	VARCHAR2(10)	NOT NULL	COMMENT '회원아이디',
	`SUPPORT_TITLE`	VARCHAR2(50)	NULL	COMMENT '제목',
	`SUPPORT_CONTENT`	CLOB	NULL	COMMENT '내용',
	`SUPPORT_DATE`	DATE	NULL	COMMENT '작성일',
	`SUPPORT_STATE`	NUMBER	NULL	COMMENT '글상태',
	`SUPPORT_INSTITUTE`	VARCHAR2(100)	NULL	COMMENT '기관명'
);

CREATE TABLE `ATTACHED_FILE` (
	`ATCH_FILE_ID`	NUMBER	NOT NULL,
	`FILE_SN`	NUMBER(3)	NOT NULL,
	`FILE_STRE_COURS`	VARCHAR2(2000)	NOT NULL,
	`STRE_FILE_NM`	VARCHAR2(255)	NOT NULL,
	`ORIGNL_FILE_NM`	VARCHAR2(255)	NULL,
	`FILE_EXTSN`	VARCHAR2(20)	NOT NULL,
	`FILE_CN`	CLOB	NULL,
	`FILE_SIZE`	NUMBER(8)	NULL
);

CREATE TABLE `like_company` (
	`LIKECO_ID`	VARCHAR2(20)	NOT NULL,
	`MEM_ID`	VARCHAR2(20)	NOT NULL,
	`COMPANY_ID`	VARCHAR2(20)	NOT NULL	COMMENT '회사아이디'
);

CREATE TABLE `like_announcement` (
	`LIKEAN_ID`	VARCHAR2(20)	NOT NULL,
	`ANNO_ID`	VARCHAR2(20)	NOT NULL	COMMENT '공고아이디',
	`MEM_ID`	VARCHAR2(20)	NOT NULL,
	`COMPANY_ID`	VARCHAR2(20)	NOT NULL	COMMENT '회사아이디'
);

CREATE TABLE `ADMIN` (
	`MEM_ID`	VARCHAR2(20)	NOT NULL	COMMENT '회원아이디'
);

CREATE TABLE `PR` (
	`PR_NO`	VARCHAR2(10)	NOT NULL	COMMENT '홍보글 번호',
	`PR_NAME`	VARCHAR2(100)	NOT NULL	COMMENT '홍보글 제목',
	`PR_CONTENT`	VARCHAR2(500)	NOT NULL	COMMENT '홍보글 소개',
	`PR_DATE`	DATE	NOT NULL	COMMENT '작성일자',
	`Key2`	VARCHAR(255)	NOT NULL
);

CREATE TABLE `WALFARE` (
	`WALFARE_CODE`	VARCHAR2(20)	NOT NULL	COMMENT '복지코드',
	`WALFARE_NAME`	VARCHAR2	NOT NULL	COMMENT '항목명',
	`WALFARE_REF`	VARCHAR2(20)	NULL	COMMENT '상위코드'
);

CREATE TABLE `ANNO_WALFARE` (
	`ANNOWAL_ID`	VARCHAR2(20)	NOT NULL	COMMENT '공고별복지ID',
	`ANNO_ID`	VARCHAR2(20)	NOT NULL	COMMENT '공고아이디',
	`WALFARE_CODE`	VARCHAR2(20)	NOT NULL	COMMENT '복지코드'
);

CREATE TABLE `announcement_detail` (
	`DANNO_ID`	VARCHAR2(20)	NOT NULL	COMMENT '세부공고아이디',
	`ANNO_ID`	VARCHAR2(20)	NOT NULL	COMMENT '공고아이디',
	`DANNO_FD`	VARCHAR2(20)	NOT NULL	COMMENT '모집분야',
	`DANNO_COUNT`	VARCHAR2(20)	NULL	COMMENT '모집인원',
	`DANNO_CAREER`	VARCHAR2(20)	NOT NULL	COMMENT '경력',
	`DANNO_CAREERYEAR`	VARCHAR2(20)	NULL	COMMENT '경력연차',
	`DANNO_TASK`	VARCHAR2(200)	NULL	COMMENT '담당업무',
	`DANNO_DEPARTMENT`	VARCHAR2(20)	NULL	COMMENT '근무부서',
	`DANNO_PREFER`	VARCHAR2(200)	NULL	COMMENT '우대사항',
	`DANNO_GENDER`	VARCHAR2(10)	NULL	COMMENT '성별
여/남',
	`DANNO_AGE`	VARCHAR2(20)	NULL	COMMENT '연령',
	`DANNO_SALARY`	VARCHAR2(20)	NULL	COMMENT '연봉급여',
	`DANNO_PROBATION`	VARCHAR2(20)	NULL	COMMENT '수습기간',
	`DANNO_WORKDAY`	VARCHAR2(20)	NULL	COMMENT '근무요일',
	`DANNO_WORKTIME`	VARCHAR2(20)	NULL	COMMENT '근무시간',
	`ANNOEDU_CODE`	VARCHAR2(20)	NOT NULL	COMMENT '학력코드',
	`EMPLTYPE_CODE`	VARCHAR2(20)	NOT NULL	COMMENT '고용형태코드',
	`JOB_CODE`	VARCHAR2(20)	NOT NULL	COMMENT '직무코드'
);

CREATE TABLE `DEPOSIT` (
	`DEPOSIT_ID`	VARCHAR2(20)	NOT NULL,
	`BANKING_ACCOUNT`	VARCHAR2(50)	NOT NULL,
	`DEPOSIT_DIVISION`	VARCHAR2(10)	NULL,
	`DEPOSIT_SENDER`	VARCHAR2(20)	NULL,
	`DEPOSIT_RECIPIENT`	VARCHAR2(20)	NULL,
	`DEPOSIT_AMOUNT`	NUMBER	NULL,
	`DEPOSIT_DATE`	DATE	NULL
);

CREATE TABLE `EXLPROD` (
	`EXLPROD_ID`	VARCHAR2(20)	NOT NULL	COMMENT '분류코드',
	`EXLPROD_DIVISION`	VARCHAR2(30)	NULL,
	`EXLPROD_FIELD`	VARCHAR2(30)	NULL,
	`EXLPROD_JOB`	VARCHAR2(30)	NULL
);

CREATE TABLE `ANNO_EDUCATION` (
	`ANNOEDU_CODE`	VARCHAR2(20)	NOT NULL	COMMENT '학력코드',
	`ANNOEDU_NAME`	VARCHAR2(20)	NULL
);

CREATE TABLE `POSITION` (
	`POSITION_CODE`	VARCHAR2(20)	NOT NULL	COMMENT '직급직책코드',
	`POSITION_NAME`	VARCHAR2(50)	NOT NULL	COMMENT '직급직책명'
);

CREATE TABLE `EMPLTYPE` (
	`EMPLTYPE_CODE`	VARCHAR2(20)	NOT NULL	COMMENT '고용형태코드',
	`EMPLTYPE_NAME`	VARCHAR2(20)	NULL	COMMENT '고용형태'
);

CREATE TABLE `ANNO_POSITION` (
	`ANNOPOS_CODE`	VARCHAR2(20)	NOT NULL,
	`DANNO_ID`	VARCHAR2(20)	NOT NULL	COMMENT '세부공고아이디',
	`POSITION_CODE`	VARCHAR2(20)	NOT NULL	COMMENT '직급직책코드'
);

CREATE TABLE `UPPER50` (
	`UPPER50_NO`	VARCHAR2(20)	NOT NULL,
	`COMPANY_ID`	VARCHAR2(10)	NOT NULL	COMMENT '회사아이디',
	`UPPER50_SCORE`	VARCHAR2(20)	NULL
);

CREATE TABLE `UPPER70` (
	`UPPER70_NO`	VARCHAR2(20)	NOT NULL,
	`COMPANY_ID`	VARCHAR2(10)	NOT NULL	COMMENT '회사아이디',
	`UPPER70_SCORE`	VARCHAR2(20)	NULL
);

CREATE TABLE `ITEM_CODE` (
	`ITEM_CODE_ID`	VARCHAR2(20)	NOT NULL	COMMENT '항목코드',
	`PROCESS_CODE_ID`	VARCHAR2(20)	NOT NULL	COMMENT '분류코드',
	`ITEM_CODE_NAME`	VARCHAR2(30)	NOT NULL	COMMENT '항목명'
);

CREATE TABLE `PROCESS` (
	`ANNO_ID`	VARCHAR2(20)	NOT NULL	COMMENT '공고아이디',
	`PROCESS_CODE_ID`	VARCHAR2(20)	NOT NULL	COMMENT '분류코드',
	`COMPANY_ID`	VARCHAR2(20)	NOT NULL	COMMENT '회사아이디',
	`PROCESS_STARTDATE`	DATE	NOT NULL	COMMENT '시작날짜',
	`PROCESS_ENDDATE`	DATE	NOT NULL	COMMENT '종료날짜',
	`PROCESS_PERFECT_SCORE`	NUMBER	NOT NULL	DEFAULT 0	COMMENT '기준만점'
);

CREATE TABLE `REGION` (
	`REGION_CODE`	NUMBER	NOT NULL	COMMENT '지역코드',
	`REGION_NAME`	VARCHAR2(50)	NOT NULL	COMMENT '지역명',
	`REGION_REF`	NUMBER	NULL	COMMENT '상위코드'
);

CREATE TABLE `ANNO_REGION` (
	`ANNOREG_ID`	VARCHAR2(20)	NOT NULL	COMMENT '공고별근무지역ID',
	`DANNO_ID`	VARCHAR2(20)	NOT NULL	COMMENT '세부공고아이디',
	`REGION_CODE`	NUMBER	NOT NULL	COMMENT '지역코드'
);

CREATE TABLE `ANNO_JOB` (
	`JOB_CODE`	VARCHAR2(20)	NOT NULL	COMMENT '직무코드',
	`JOB_NAME`	VARCHAR2(50)	NOT NULL	COMMENT '직무명',
	`JOB_REF`	VARCHAR2(20)	NULL	COMMENT '상위코드'
);

CREATE TABLE `INDUSTRY` (
	`INDUSTRY_CODE`	VARCHAR2(20)	NOT NULL	COMMENT '업종코드',
	`INDUSTRY_NAME`	VARCHAR2(50)	NULL	COMMENT '업종명',
	`INDUSTRY_REF`	VARCHAR2(20)	NULL	COMMENT '상위코드'
);

CREATE TABLE `CAREERROAD` (
	`CAROAD_NO`	VARCHAR2(20)	NOT NULL,
	`COMPANY_ID`	VARCHAR2(10)	NOT NULL	COMMENT '회사아이디'
);

ALTER TABLE `SEEKER` ADD CONSTRAINT `PK_SEEKER` PRIMARY KEY (
	`MEM_ID`
);

ALTER TABLE `INCRUITER` ADD CONSTRAINT `PK_INCRUITER` PRIMARY KEY (
	`MEM_ID`
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`MEM_ID`
);

ALTER TABLE `announcement` ADD CONSTRAINT `PK_ANNOUNCEMENT` PRIMARY KEY (
	`ANNO_ID`,
	`COMPANY_ID`
);

ALTER TABLE `JOB_APPLY` ADD CONSTRAINT `PK_JOB_APPLY` PRIMARY KEY (
	`APPLY_ID`
);

ALTER TABLE `RESUME` ADD CONSTRAINT `PK_RESUME` PRIMARY KEY (
	`APPLY_ID`
);

ALTER TABLE `INTRODUCTION` ADD CONSTRAINT `PK_INTRODUCTION` PRIMARY KEY (
	`APPLY_ID`
);

ALTER TABLE `TEST` ADD CONSTRAINT `PK_TEST` PRIMARY KEY (
	`APPLY_ID`
);

ALTER TABLE `COMPETENCY` ADD CONSTRAINT `PK_COMPETENCY` PRIMARY KEY (
	`APPLY_ID`
);

ALTER TABLE `PRACTICE` ADD CONSTRAINT `PK_PRACTICE` PRIMARY KEY (
	`APPLY_ID`
);

ALTER TABLE `DISCUSS` ADD CONSTRAINT `PK_DISCUSS` PRIMARY KEY (
	`APPLY_ID`
);

ALTER TABLE `INTERNSHIP` ADD CONSTRAINT `PK_INTERNSHIP` PRIMARY KEY (
	`APPLY_ID`
);

ALTER TABLE `INDEPTH_INTERVIEW` ADD CONSTRAINT `PK_INDEPTH_INTERVIEW` PRIMARY KEY (
	`APPLY_ID`
);

ALTER TABLE `PROCESS_ITEM` ADD CONSTRAINT `PK_PROCESS_ITEM` PRIMARY KEY (
	`PROCESS_ID`
);

ALTER TABLE `PROCESS_CODE` ADD CONSTRAINT `PK_PROCESS_CODE` PRIMARY KEY (
	`PROCESS_CODE_ID`
);

ALTER TABLE `CAREER` ADD CONSTRAINT `PK_CAREER` PRIMARY KEY (
	`CAREER_ID`
);

ALTER TABLE `EDUCATION` ADD CONSTRAINT `PK_EDUCATION` PRIMARY KEY (
	`EDU_ID`
);

ALTER TABLE `CERTIFICATION` ADD CONSTRAINT `PK_CERTIFICATION` PRIMARY KEY (
	`CERT_ID`
);

ALTER TABLE `MYINTRODUCTION` ADD CONSTRAINT `PK_MYINTRODUCTION` PRIMARY KEY (
	`MYINTRO_ID`
);

ALTER TABLE `FACILITY` ADD CONSTRAINT `PK_FACILITY` PRIMARY KEY (
	`FACILITY_ID`
);

ALTER TABLE `ACTIVITY` ADD CONSTRAINT `PK_ACTIVITY` PRIMARY KEY (
	`ACT_ID`
);

ALTER TABLE `AWARD` ADD CONSTRAINT `PK_AWARD` PRIMARY KEY (
	`AWARD_ID`
);

ALTER TABLE `COURSE` ADD CONSTRAINT `PK_COURSE` PRIMARY KEY (
	`COURSE_ID`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `PK_REVIEW` PRIMARY KEY (
	`REVIEW_ID`
);

ALTER TABLE `CUT` ADD CONSTRAINT `PK_CUT` PRIMARY KEY (
	`CUT_ID`
);

ALTER TABLE `BLACKLIST` ADD CONSTRAINT `PK_BLACKLIST` PRIMARY KEY (
	`BLACKLIST_ID`
);

ALTER TABLE `COMPANY` ADD CONSTRAINT `PK_COMPANY` PRIMARY KEY (
	`COMPANY_ID`
);

ALTER TABLE `BOARD_REPORT` ADD CONSTRAINT `PK_BOARD_REPORT` PRIMARY KEY (
	`BOARD_REPORT_ID`
);

ALTER TABLE `COMMENT_REPORT` ADD CONSTRAINT `PK_COMMENT_REPORT` PRIMARY KEY (
	`COMMENT_REPORT_ID`
);

ALTER TABLE `BANKING` ADD CONSTRAINT `PK_BANKING` PRIMARY KEY (
	`BANKING_ACCOUNT`
);

ALTER TABLE `ALRAM` ADD CONSTRAINT `PK_ALRAM` PRIMARY KEY (
	`ALRAM_ID`
);

ALTER TABLE `HELP` ADD CONSTRAINT `PK_HELP` PRIMARY KEY (
	`HELP_ID`
);

ALTER TABLE `NEWS` ADD CONSTRAINT `PK_NEWS` PRIMARY KEY (
	`NEWS_NO`
);

ALTER TABLE `CONTEST` ADD CONSTRAINT `PK_CONTEST` PRIMARY KEY (
	`CONT_NO`
);

ALTER TABLE `NOTICE` ADD CONSTRAINT `PK_NOTICE` PRIMARY KEY (
	`NOTICE_ID`
);

ALTER TABLE `EXPROD` ADD CONSTRAINT `PK_EXPROD` PRIMARY KEY (
	`EXPROD_ID`
);

ALTER TABLE `COMMENT` ADD CONSTRAINT `PK_COMMENT` PRIMARY KEY (
	`COMM_ID`
);

ALTER TABLE `REPORT` ADD CONSTRAINT `PK_REPORT` PRIMARY KEY (
	`REPORT_ID`
);

ALTER TABLE `EXCART` ADD CONSTRAINT `PK_EXCART` PRIMARY KEY (
	`EXCART_ID`
);

ALTER TABLE `EXPERT` ADD CONSTRAINT `PK_EXPERT` PRIMARY KEY (
	`MEM_ID`
);

ALTER TABLE `INTEREST` ADD CONSTRAINT `PK_INTEREST` PRIMARY KEY (
	`INTE_NO`
);

ALTER TABLE `TODAYSEE` ADD CONSTRAINT `PK_TODAYSEE` PRIMARY KEY (
	`TODAY_NO`
);

ALTER TABLE `EXREVIEW` ADD CONSTRAINT `PK_EXREVIEW` PRIMARY KEY (
	`EXREVIEW_ID`
);

ALTER TABLE `EXEVENT` ADD CONSTRAINT `PK_EXEVENT` PRIMARY KEY (
	`EXEVENT_ID`
);

ALTER TABLE `BOARD` ADD CONSTRAINT `PK_BOARD` PRIMARY KEY (
	`BOARD_ID`
);

ALTER TABLE `INCUMBENT_INTERVIEW` ADD CONSTRAINT `PK_INCUMBENT_INTERVIEW` PRIMARY KEY (
	`INTERVIEW_ID`
);

ALTER TABLE `COUNSELING` ADD CONSTRAINT `PK_COUNSELING` PRIMARY KEY (
	`COUN_NO`,
	`MEM_ID`
);

ALTER TABLE `RESUME_FORM` ADD CONSTRAINT `PK_RESUME_FORM` PRIMARY KEY (
	`RESUME_FORM_ID`
);

ALTER TABLE `TRANSPARENCY_FORM` ADD CONSTRAINT `PK_TRANSPARENCY_FORM` PRIMARY KEY (
	`Key`
);

ALTER TABLE `TRANSPARENCY` ADD CONSTRAINT `PK_TRANSPARENCY` PRIMARY KEY (
	`Key2`
);

ALTER TABLE `SUPPORT` ADD CONSTRAINT `PK_SUPPORT` PRIMARY KEY (
	`SUPPORT_ID`,
	`MEM_ID`
);

ALTER TABLE `ATTACHED_FILE` ADD CONSTRAINT `PK_ATTACHED_FILE` PRIMARY KEY (
	`ATCH_FILE_ID`
);

ALTER TABLE `like_company` ADD CONSTRAINT `PK_LIKE_COMPANY` PRIMARY KEY (
	`LIKECO_ID`,
	`MEM_ID`,
	`COMPANY_ID`
);

ALTER TABLE `like_announcement` ADD CONSTRAINT `PK_LIKE_ANNOUNCEMENT` PRIMARY KEY (
	`LIKEAN_ID`,
	`ANNO_ID`,
	`MEM_ID`,
	`COMPANY_ID`
);

ALTER TABLE `ADMIN` ADD CONSTRAINT `PK_ADMIN` PRIMARY KEY (
	`MEM_ID`
);

ALTER TABLE `PR` ADD CONSTRAINT `PK_PR` PRIMARY KEY (
	`PR_NO`
);

ALTER TABLE `WALFARE` ADD CONSTRAINT `PK_WALFARE` PRIMARY KEY (
	`WALFARE_CODE`
);

ALTER TABLE `ANNO_WALFARE` ADD CONSTRAINT `PK_ANNO_WALFARE` PRIMARY KEY (
	`ANNOWAL_ID`,
	`ANNO_ID`
);

ALTER TABLE `announcement_detail` ADD CONSTRAINT `PK_ANNOUNCEMENT_DETAIL` PRIMARY KEY (
	`DANNO_ID`,
	`ANNO_ID`
);

ALTER TABLE `DEPOSIT` ADD CONSTRAINT `PK_DEPOSIT` PRIMARY KEY (
	`DEPOSIT_ID`
);

ALTER TABLE `EXLPROD` ADD CONSTRAINT `PK_EXLPROD` PRIMARY KEY (
	`EXLPROD_ID`
);

ALTER TABLE `ANNO_EDUCATION` ADD CONSTRAINT `PK_ANNO_EDUCATION` PRIMARY KEY (
	`ANNOEDU_CODE`
);

ALTER TABLE `POSITION` ADD CONSTRAINT `PK_POSITION` PRIMARY KEY (
	`POSITION_CODE`
);

ALTER TABLE `EMPLTYPE` ADD CONSTRAINT `PK_EMPLTYPE` PRIMARY KEY (
	`EMPLTYPE_CODE`
);

ALTER TABLE `ANNO_POSITION` ADD CONSTRAINT `PK_ANNO_POSITION` PRIMARY KEY (
	`ANNOPOS_CODE`,
	`DANNO_ID`
);

ALTER TABLE `UPPER50` ADD CONSTRAINT `PK_UPPER50` PRIMARY KEY (
	`UPPER50_NO`
);

ALTER TABLE `UPPER70` ADD CONSTRAINT `PK_UPPER70` PRIMARY KEY (
	`UPPER70_NO`
);

ALTER TABLE `ITEM_CODE` ADD CONSTRAINT `PK_ITEM_CODE` PRIMARY KEY (
	`ITEM_CODE_ID`
);

ALTER TABLE `PROCESS` ADD CONSTRAINT `PK_PROCESS` PRIMARY KEY (
	`ANNO_ID`,
	`PROCESS_CODE_ID`,
	`COMPANY_ID`
);

ALTER TABLE `REGION` ADD CONSTRAINT `PK_REGION` PRIMARY KEY (
	`REGION_CODE`
);

ALTER TABLE `ANNO_REGION` ADD CONSTRAINT `PK_ANNO_REGION` PRIMARY KEY (
	`ANNOREG_ID`,
	`DANNO_ID`
);

ALTER TABLE `ANNO_JOB` ADD CONSTRAINT `PK_ANNO_JOB` PRIMARY KEY (
	`JOB_CODE`
);

ALTER TABLE `INDUSTRY` ADD CONSTRAINT `PK_INDUSTRY` PRIMARY KEY (
	`INDUSTRY_CODE`
);

ALTER TABLE `CAREERROAD` ADD CONSTRAINT `PK_CAREERROAD` PRIMARY KEY (
	`CAROAD_NO`
);

ALTER TABLE `SEEKER` ADD CONSTRAINT `FK_MEMBER_TO_SEEKER_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `MEMBER` (
	`MEM_ID`
);

ALTER TABLE `INCRUITER` ADD CONSTRAINT `FK_MEMBER_TO_INCRUITER_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `MEMBER` (
	`MEM_ID`
);

ALTER TABLE `INCRUITER` ADD CONSTRAINT `FK_COMPANY_TO_INCRUITER_1` FOREIGN KEY (
	`Key`
)
REFERENCES `COMPANY` (
	`COMPANY_ID`
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `FK_ATTACHED_FILE_TO_MEMBER_1` FOREIGN KEY (
	`ATCH_FILE_ID`
)
REFERENCES `ATTACHED_FILE` (
	`ATCH_FILE_ID`
);

ALTER TABLE `announcement` ADD CONSTRAINT `FK_COMPANY_TO_announcement_1` FOREIGN KEY (
	`COMPANY_ID`
)
REFERENCES `COMPANY` (
	`COMPANY_ID`
);

ALTER TABLE `announcement` ADD CONSTRAINT `FK_INDUSTRY_TO_announcement_1` FOREIGN KEY (
	`INDUSTRY_CODE`
)
REFERENCES `INDUSTRY` (
	`INDUSTRY_CODE`
);

ALTER TABLE `JOB_APPLY` ADD CONSTRAINT `FK_announcement_TO_JOB_APPLY_1` FOREIGN KEY (
	`ANNO_ID`
)
REFERENCES `announcement` (
	`ANNO_ID`
);

ALTER TABLE `JOB_APPLY` ADD CONSTRAINT `FK_SEEKER_TO_JOB_APPLY_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `SEEKER` (
	`MEM_ID`
);

ALTER TABLE `RESUME` ADD CONSTRAINT `FK_JOB_APPLY_TO_RESUME_1` FOREIGN KEY (
	`APPLY_ID`
)
REFERENCES `JOB_APPLY` (
	`APPLY_ID`
);

ALTER TABLE `INTRODUCTION` ADD CONSTRAINT `FK_JOB_APPLY_TO_INTRODUCTION_1` FOREIGN KEY (
	`APPLY_ID`
)
REFERENCES `JOB_APPLY` (
	`APPLY_ID`
);

ALTER TABLE `TEST` ADD CONSTRAINT `FK_JOB_APPLY_TO_TEST_1` FOREIGN KEY (
	`APPLY_ID`
)
REFERENCES `JOB_APPLY` (
	`APPLY_ID`
);

ALTER TABLE `COMPETENCY` ADD CONSTRAINT `FK_JOB_APPLY_TO_COMPETENCY_1` FOREIGN KEY (
	`APPLY_ID`
)
REFERENCES `JOB_APPLY` (
	`APPLY_ID`
);

ALTER TABLE `PRACTICE` ADD CONSTRAINT `FK_JOB_APPLY_TO_PRACTICE_1` FOREIGN KEY (
	`APPLY_ID`
)
REFERENCES `JOB_APPLY` (
	`APPLY_ID`
);

ALTER TABLE `DISCUSS` ADD CONSTRAINT `FK_JOB_APPLY_TO_DISCUSS_1` FOREIGN KEY (
	`APPLY_ID`
)
REFERENCES `JOB_APPLY` (
	`APPLY_ID`
);

ALTER TABLE `INTERNSHIP` ADD CONSTRAINT `FK_JOB_APPLY_TO_INTERNSHIP_1` FOREIGN KEY (
	`APPLY_ID`
)
REFERENCES `JOB_APPLY` (
	`APPLY_ID`
);

ALTER TABLE `INDEPTH_INTERVIEW` ADD CONSTRAINT `FK_JOB_APPLY_TO_INDEPTH_INTERVIEW_1` FOREIGN KEY (
	`APPLY_ID`
)
REFERENCES `JOB_APPLY` (
	`APPLY_ID`
);

ALTER TABLE `PROCESS_ITEM` ADD CONSTRAINT `FK_announcement_TO_PROCESS_ITEM_1` FOREIGN KEY (
	`ANNO_ID`
)
REFERENCES `announcement` (
	`ANNO_ID`
);

ALTER TABLE `PROCESS_ITEM` ADD CONSTRAINT `FK_ITEM_CODE_TO_PROCESS_ITEM_1` FOREIGN KEY (
	`ITEM_CODE_ID`
)
REFERENCES `ITEM_CODE` (
	`ITEM_CODE_ID`
);

ALTER TABLE `CAREER` ADD CONSTRAINT `FK_SEEKER_TO_CAREER_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `SEEKER` (
	`MEM_ID`
);

ALTER TABLE `EDUCATION` ADD CONSTRAINT `FK_SEEKER_TO_EDUCATION_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `SEEKER` (
	`MEM_ID`
);

ALTER TABLE `CERTIFICATION` ADD CONSTRAINT `FK_SEEKER_TO_CERTIFICATION_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `SEEKER` (
	`MEM_ID`
);

ALTER TABLE `MYINTRODUCTION` ADD CONSTRAINT `FK_SEEKER_TO_MYINTRODUCTION_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `SEEKER` (
	`MEM_ID`
);

ALTER TABLE `FACILITY` ADD CONSTRAINT `FK_SEEKER_TO_FACILITY_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `SEEKER` (
	`MEM_ID`
);

ALTER TABLE `ACTIVITY` ADD CONSTRAINT `FK_SEEKER_TO_ACTIVITY_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `SEEKER` (
	`MEM_ID`
);

ALTER TABLE `AWARD` ADD CONSTRAINT `FK_SEEKER_TO_AWARD_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `SEEKER` (
	`MEM_ID`
);

ALTER TABLE `COURSE` ADD CONSTRAINT `FK_SEEKER_TO_COURSE_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `SEEKER` (
	`MEM_ID`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `FK_MEMBER_TO_REVIEW_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `MEMBER` (
	`MEM_ID`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `FK_COMPANY_TO_REVIEW_1` FOREIGN KEY (
	`COMPANY_ID`
)
REFERENCES `COMPANY` (
	`COMPANY_ID`
);

ALTER TABLE `CUT` ADD CONSTRAINT `FK_MEMBER_TO_CUT_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `MEMBER` (
	`MEM_ID`
);

ALTER TABLE `BLACKLIST` ADD CONSTRAINT `FK_MEMBER_TO_BLACKLIST_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `MEMBER` (
	`MEM_ID`
);

ALTER TABLE `BOARD_REPORT` ADD CONSTRAINT `FK_MEMBER_TO_BOARD_REPORT_1` FOREIGN KEY (
	`MEM_ID2`
)
REFERENCES `MEMBER` (
	`MEM_ID`
);

ALTER TABLE `COMMENT_REPORT` ADD CONSTRAINT `FK_MEMBER_TO_COMMENT_REPORT_1` FOREIGN KEY (
	`MEM_ID2`
)
REFERENCES `MEMBER` (
	`MEM_ID`
);

ALTER TABLE `COMMENT_REPORT` ADD CONSTRAINT `FK_COMMENT_TO_COMMENT_REPORT_1` FOREIGN KEY (
	`COMM_ID`
)
REFERENCES `COMMENT` (
	`COMM_ID`
);

ALTER TABLE `BANKING` ADD CONSTRAINT `FK_MEMBER_TO_BANKING_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `MEMBER` (
	`MEM_ID`
);

ALTER TABLE `ALRAM` ADD CONSTRAINT `FK_MEMBER_TO_ALRAM_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `MEMBER` (
	`MEM_ID`
);

ALTER TABLE `ALRAM` ADD CONSTRAINT `FK_MEMBER_TO_ALRAM_2` FOREIGN KEY (
	`MEM_ID2`
)
REFERENCES `MEMBER` (
	`MEM_ID`
);

ALTER TABLE `HELP` ADD CONSTRAINT `FK_ADMIN_TO_HELP_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `ADMIN` (
	`MEM_ID`
);

ALTER TABLE `NEWS` ADD CONSTRAINT `FK_ADMIN_TO_NEWS_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `ADMIN` (
	`MEM_ID`
);

ALTER TABLE `CONTEST` ADD CONSTRAINT `FK_ADMIN_TO_CONTEST_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `ADMIN` (
	`MEM_ID`
);

ALTER TABLE `NOTICE` ADD CONSTRAINT `FK_ADMIN_TO_NOTICE_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `ADMIN` (
	`MEM_ID`
);

ALTER TABLE `EXPROD` ADD CONSTRAINT `FK_EXPERT_TO_EXPROD_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `EXPERT` (
	`MEM_ID`
);

ALTER TABLE `EXPROD` ADD CONSTRAINT `FK_EXLPROD_TO_EXPROD_1` FOREIGN KEY (
	`EXLPROD_ID`
)
REFERENCES `EXLPROD` (
	`EXLPROD_ID`
);

ALTER TABLE `EXPROD` ADD CONSTRAINT `FK_ATTACHED_FILE_TO_EXPROD_1` FOREIGN KEY (
	`ATCH_FILE_ID`
)
REFERENCES `ATTACHED_FILE` (
	`ATCH_FILE_ID`
);

ALTER TABLE `COMMENT` ADD CONSTRAINT `FK_BOARD_TO_COMMENT_1` FOREIGN KEY (
	`BOARD_ID`
)
REFERENCES `BOARD` (
	`BOARD_ID`
);

ALTER TABLE `REPORT` ADD CONSTRAINT `FK_MEMBER_TO_REPORT_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `MEMBER` (
	`MEM_ID`
);

ALTER TABLE `REPORT` ADD CONSTRAINT `FK_MEMBER_TO_REPORT_2` FOREIGN KEY (
	`MEM_ID2`
)
REFERENCES `MEMBER` (
	`MEM_ID`
);

ALTER TABLE `EXCART` ADD CONSTRAINT `FK_EXPROD_TO_EXCART_1` FOREIGN KEY (
	`EXPROD_ID`
)
REFERENCES `EXPROD` (
	`EXPROD_ID`
);

ALTER TABLE `EXCART` ADD CONSTRAINT `FK_MEMBER_TO_EXCART_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `MEMBER` (
	`MEM_ID`
);

ALTER TABLE `EXPERT` ADD CONSTRAINT `FK_SEEKER_TO_EXPERT_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `SEEKER` (
	`MEM_ID`
);

ALTER TABLE `EXPERT` ADD CONSTRAINT `FK_EXLPROD_TO_EXPERT_1` FOREIGN KEY (
	`EXLPROD_ID`
)
REFERENCES `EXLPROD` (
	`EXLPROD_ID`
);

ALTER TABLE `INTEREST` ADD CONSTRAINT `FK_PR_TO_INTEREST_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `PR` (
	`PR_NO`
);

ALTER TABLE `INTEREST` ADD CONSTRAINT `FK_INCRUITER_TO_INTEREST_1` FOREIGN KEY (
	`Key33`
)
REFERENCES `INCRUITER` (
	`MEM_ID`
);

ALTER TABLE `TODAYSEE` ADD CONSTRAINT `FK_PR_TO_TODAYSEE_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `PR` (
	`PR_NO`
);

ALTER TABLE `TODAYSEE` ADD CONSTRAINT `FK_INCRUITER_TO_TODAYSEE_1` FOREIGN KEY (
	`Key3`
)
REFERENCES `INCRUITER` (
	`MEM_ID`
);

ALTER TABLE `EXREVIEW` ADD CONSTRAINT `FK_EXCART_TO_EXREVIEW_1` FOREIGN KEY (
	`EXCART_ID`
)
REFERENCES `EXCART` (
	`EXCART_ID`
);

ALTER TABLE `EXEVENT` ADD CONSTRAINT `FK_ADMIN_TO_EXEVENT_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `ADMIN` (
	`MEM_ID`
);

ALTER TABLE `EXEVENT` ADD CONSTRAINT `FK_ATTACHED_FILE_TO_EXEVENT_1` FOREIGN KEY (
	`ATCH_FILE_ID`
)
REFERENCES `ATTACHED_FILE` (
	`ATCH_FILE_ID`
);

ALTER TABLE `BOARD` ADD CONSTRAINT `FK_MEMBER_TO_BOARD_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `MEMBER` (
	`MEM_ID`
);

ALTER TABLE `INCUMBENT_INTERVIEW` ADD CONSTRAINT `FK_announcement_TO_INCUMBENT_INTERVIEW_1` FOREIGN KEY (
	`ANNO_ID`
)
REFERENCES `announcement` (
	`ANNO_ID`
);

ALTER TABLE `INCUMBENT_INTERVIEW` ADD CONSTRAINT `FK_announcement_TO_INCUMBENT_INTERVIEW_2` FOREIGN KEY (
	`COMPANY_ID`
)
REFERENCES `announcement` (
	`COMPANY_ID`
);

ALTER TABLE `COUNSELING` ADD CONSTRAINT `FK_MEMBER_TO_COUNSELING_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `MEMBER` (
	`MEM_ID`
);

ALTER TABLE `TRANSPARENCY_FORM` ADD CONSTRAINT `FK_COMPANY_TO_TRANSPARENCY_FORM_1` FOREIGN KEY (
	`Key`
)
REFERENCES `COMPANY` (
	`COMPANY_ID`
);

ALTER TABLE `TRANSPARENCY` ADD CONSTRAINT `FK_COMPANY_TO_TRANSPARENCY_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `COMPANY` (
	`COMPANY_ID`
);

ALTER TABLE `TRANSPARENCY` ADD CONSTRAINT `FK_REVIEW_TO_TRANSPARENCY_1` FOREIGN KEY (
	`Key`
)
REFERENCES `REVIEW` (
	`REVIEW_ID`
);

ALTER TABLE `SUPPORT` ADD CONSTRAINT `FK_ADMIN_TO_SUPPORT_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `ADMIN` (
	`MEM_ID`
);

ALTER TABLE `like_company` ADD CONSTRAINT `FK_SEEKER_TO_like_company_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `SEEKER` (
	`MEM_ID`
);

ALTER TABLE `like_company` ADD CONSTRAINT `FK_COMPANY_TO_like_company_1` FOREIGN KEY (
	`COMPANY_ID`
)
REFERENCES `COMPANY` (
	`COMPANY_ID`
);

ALTER TABLE `like_announcement` ADD CONSTRAINT `FK_announcement_TO_like_announcement_1` FOREIGN KEY (
	`ANNO_ID`
)
REFERENCES `announcement` (
	`ANNO_ID`
);

ALTER TABLE `like_announcement` ADD CONSTRAINT `FK_announcement_TO_like_announcement_2` FOREIGN KEY (
	`COMPANY_ID`
)
REFERENCES `announcement` (
	`COMPANY_ID`
);

ALTER TABLE `like_announcement` ADD CONSTRAINT `FK_SEEKER_TO_like_announcement_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `SEEKER` (
	`MEM_ID`
);

ALTER TABLE `ADMIN` ADD CONSTRAINT `FK_MEMBER_TO_ADMIN_1` FOREIGN KEY (
	`MEM_ID`
)
REFERENCES `MEMBER` (
	`MEM_ID`
);

ALTER TABLE `PR` ADD CONSTRAINT `FK_SEEKER_TO_PR_1` FOREIGN KEY (
	`Key2`
)
REFERENCES `SEEKER` (
	`MEM_ID`
);

ALTER TABLE `ANNO_WALFARE` ADD CONSTRAINT `FK_announcement_TO_ANNO_WALFARE_1` FOREIGN KEY (
	`ANNO_ID`
)
REFERENCES `announcement` (
	`ANNO_ID`
);

ALTER TABLE `ANNO_WALFARE` ADD CONSTRAINT `FK_WALFARE_TO_ANNO_WALFARE_1` FOREIGN KEY (
	`WALFARE_CODE`
)
REFERENCES `WALFARE` (
	`WALFARE_CODE`
);

ALTER TABLE `announcement_detail` ADD CONSTRAINT `FK_announcement_TO_announcement_detail_1` FOREIGN KEY (
	`ANNO_ID`
)
REFERENCES `announcement` (
	`ANNO_ID`
);

ALTER TABLE `announcement_detail` ADD CONSTRAINT `FK_ANNO_EDUCATION_TO_announcement_detail_1` FOREIGN KEY (
	`ANNOEDU_CODE`
)
REFERENCES `ANNO_EDUCATION` (
	`ANNOEDU_CODE`
);

ALTER TABLE `announcement_detail` ADD CONSTRAINT `FK_EMPLTYPE_TO_announcement_detail_1` FOREIGN KEY (
	`EMPLTYPE_CODE`
)
REFERENCES `EMPLTYPE` (
	`EMPLTYPE_CODE`
);

ALTER TABLE `announcement_detail` ADD CONSTRAINT `FK_ANNO_JOB_TO_announcement_detail_1` FOREIGN KEY (
	`JOB_CODE`
)
REFERENCES `ANNO_JOB` (
	`JOB_CODE`
);

ALTER TABLE `DEPOSIT` ADD CONSTRAINT `FK_BANKING_TO_DEPOSIT_1` FOREIGN KEY (
	`BANKING_ACCOUNT`
)
REFERENCES `BANKING` (
	`BANKING_ACCOUNT`
);

ALTER TABLE `ANNO_POSITION` ADD CONSTRAINT `FK_announcement_detail_TO_ANNO_POSITION_1` FOREIGN KEY (
	`DANNO_ID`
)
REFERENCES `announcement_detail` (
	`DANNO_ID`
);

ALTER TABLE `ANNO_POSITION` ADD CONSTRAINT `FK_POSITION_TO_ANNO_POSITION_1` FOREIGN KEY (
	`POSITION_CODE`
)
REFERENCES `POSITION` (
	`POSITION_CODE`
);

ALTER TABLE `UPPER50` ADD CONSTRAINT `FK_COMPANY_TO_UPPER50_1` FOREIGN KEY (
	`COMPANY_ID`
)
REFERENCES `COMPANY` (
	`COMPANY_ID`
);

ALTER TABLE `UPPER70` ADD CONSTRAINT `FK_COMPANY_TO_UPPER70_1` FOREIGN KEY (
	`COMPANY_ID`
)
REFERENCES `COMPANY` (
	`COMPANY_ID`
);

ALTER TABLE `ITEM_CODE` ADD CONSTRAINT `FK_PROCESS_CODE_TO_ITEM_CODE_1` FOREIGN KEY (
	`PROCESS_CODE_ID`
)
REFERENCES `PROCESS_CODE` (
	`PROCESS_CODE_ID`
);

ALTER TABLE `PROCESS` ADD CONSTRAINT `FK_announcement_TO_PROCESS_1` FOREIGN KEY (
	`ANNO_ID`
)
REFERENCES `announcement` (
	`ANNO_ID`
);

ALTER TABLE `PROCESS` ADD CONSTRAINT `FK_announcement_TO_PROCESS_2` FOREIGN KEY (
	`COMPANY_ID`
)
REFERENCES `announcement` (
	`COMPANY_ID`
);

ALTER TABLE `PROCESS` ADD CONSTRAINT `FK_PROCESS_CODE_TO_PROCESS_1` FOREIGN KEY (
	`PROCESS_CODE_ID`
)
REFERENCES `PROCESS_CODE` (
	`PROCESS_CODE_ID`
);

ALTER TABLE `ANNO_REGION` ADD CONSTRAINT `FK_announcement_detail_TO_ANNO_REGION_1` FOREIGN KEY (
	`DANNO_ID`
)
REFERENCES `announcement_detail` (
	`DANNO_ID`
);

ALTER TABLE `ANNO_REGION` ADD CONSTRAINT `FK_REGION_TO_ANNO_REGION_1` FOREIGN KEY (
	`REGION_CODE`
)
REFERENCES `REGION` (
	`REGION_CODE`
);

ALTER TABLE `CAREERROAD` ADD CONSTRAINT `FK_COMPANY_TO_CAREERROAD_1` FOREIGN KEY (
	`COMPANY_ID`
)
REFERENCES `COMPANY` (
	`COMPANY_ID`
);

