CREATE TABLE "SEEKER" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"SEEKER_EXPERT"	NUMBER		NULL,
	"SEEKER_BIRTH"	DATE		NULL,
	"SEEKER_GENDER"	VARCHAR2(5)		NULL
);

CREATE TABLE "INCRUITER" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"INCRUITER_APPROVAL"	NUMBER		NULL,
	"Key"	VARCHAR2(10)		NOT NULL,
	"INCRUITER_ AUTHORITY"	VARCHR2(20)		NULL
);

COMMENT ON COLUMN "INCRUITER"."MEM_ID" IS '구인자아이디';

CREATE TABLE "MEMBER" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_DIVISION"	VARCHAR2(5)		NULL,
	"MEM_PASS"	VARCHAR2(20)		NULL,
	"MEM_NM"	VARCHAR2(20)		NULL,
	"MEM_ZIP"	VARCHAR(20)		NULL,
	"MEM_ADDR1"	VARCHAR2(200)		NULL,
	"MEM_ADDR2"	VARCHAR2(200)		NULL,
	"MEM_EMAIL"	VARCHAR2(200)		NULL,
	"MEM_TEL"	VARCHAR2(30)		NULL,
	"MEM_DATE"	DATE		NULL,
	"MEM_CERTIFICATION"	VARCHAR2(10)		NULL,
	"MEM_CARTTOTAL"	NUMBER		NULL,
	"MEM_PHOTO"	VARCHAR2(200)		NULL,
	"MEM_NICKNAME"	VARCHAR2(50)		NULL,
	"MEM_MILEAGE"	NUMBER		NULL,
	"MEM_DELETE"	DATE		NULL
);

COMMENT ON COLUMN "MEMBER"."MEM_ID" IS '회원아이디';

CREATE TABLE "ANNOUNCEMENT" (
	"ANNO_ID"	VARCHAR2(20)		NOT NULL,
	"COMPANY_ID"	VARCHAR2(20)		NOT NULL,
	"ANNO_TITLE"	VARCHAR2(50)		NOT NULL,
	"ANNO_CONTENT"	CLOB		NULL,
	"ANNO_STARTDATE"	DATE		NOT NULL,
	"ANNO_ENDDATE"	DATE		NOT NULL,
	"ANNO_HIT"	NUMBER	DEFAULT 0	NOT NULL,
	"ANNO_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ANNO_STATE"	NUMBER	DEFAULT 0	NULL,
	"ANNO_TYPE"	VARCHAR2(20)		NULL,
	"ANNO_MANAGER"	VARCHAR2(20)		NOT NULL,
	"ANNO_TEL"	VARCHAR2(20)		NOT NULL,
	"ANNO_MAIL"	VARCHAR2(50)		NOT NULL,
	"ANNO_WORKENV"	VARCHAR2(500)		NULL,
	"INDUSTRY_CD"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNO_ID" IS '공고아이디';

COMMENT ON COLUMN "ANNOUNCEMENT"."COMPANY_ID" IS '회사아이디';

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNO_TITLE" IS '제목';

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNO_CONTENT" IS '내용';

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNO_STARTDATE" IS '접수시작날짜';

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNO_ENDDATE" IS '접수종료날짜';

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNO_HIT" IS '조회수';

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNO_DATE" IS '작성일';

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNO_STATE" IS '공고글상태
0: 임시저장
1: 공고중
2: 공고만료
3: 삭제됨';

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNO_TYPE" IS '공고타입
N: 일반채용
B: 블라인드채용';

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNO_MANAGER" IS '담당자이름';

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNO_TEL" IS '담당자전화번호';

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNO_MAIL" IS '담당자이메일';

COMMENT ON COLUMN "ANNOUNCEMENT"."ANNO_WORKENV" IS '근무환경';

CREATE TABLE "JOB_APPLY" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"DANNO_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"MYRESUME_ID"	VARCHAR2(20)		NOT NULL,
	"MYINTRO_ID"	VARCHAR2(20)		NOT NULL,
	"APPLY_RESULT"	VARCHAR2(20)	DEFAULT 진행중	NOT NULL,
	"APPLY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"APPLY_UPDATE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"APPLY_DELETE_DATE"	DATE		NOT NULL,
	"APPLY_TOTAL"	NUMBER	DEFAULT 0	NULL
);

COMMENT ON COLUMN "JOB_APPLY"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "JOB_APPLY"."DANNO_ID" IS '세부공고아이디';

COMMENT ON COLUMN "JOB_APPLY"."MEM_ID" IS '구직자아이디';

COMMENT ON COLUMN "JOB_APPLY"."MYRESUME_ID" IS '이력서 아이디';

COMMENT ON COLUMN "JOB_APPLY"."MYINTRO_ID" IS '내 자기소개서 아이디';

COMMENT ON COLUMN "JOB_APPLY"."APPLY_RESULT" IS '지원결과';

COMMENT ON COLUMN "JOB_APPLY"."APPLY_DATE" IS '지원날짜';

COMMENT ON COLUMN "JOB_APPLY"."APPLY_UPDATE_DATE" IS '지원수정날짜';

COMMENT ON COLUMN "JOB_APPLY"."APPLY_DELETE_DATE" IS '지원 삭제날짜';

COMMENT ON COLUMN "JOB_APPLY"."APPLY_TOTAL" IS '지원자총점평균';

CREATE TABLE "RESUME_SCORE" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"RESUME_CAREER"	NUMBER	DEFAULT 0	NULL,
	"RESUME_EDU"	NUMBER	DEFAULT 0	NULL,
	"RESUME_CERT"	NUMBER	DEFAULT 0	NULL,
	"RESUME_FACILITY"	NUMBER	DEFAULT 0	NULL,
	"RESUME_ACTIVITY"	NUMBER	DEFAULT 0	NULL,
	"RESUME_SOCIAL_EXPERIENCE"	NUMBER	DEFAULT 0	NULL,
	"RESUME_AWARD"	NUMBER	DEFAULT 0	NULL,
	"RESUME_COURSE"	NUMBER	DEFAULT 0	NULL,
	"RESUME_DUTY"	NUMBER	DEFAULT 0	NULL,
	"RESUME_ADD1"	NUMBER	DEFAULT 0	NULL,
	"RESUME_ADD2"	NUMBER	DEFAULT 0	NULL,
	"RESUME_ADD3"	NUMBER	DEFAULT 0	NULL,
	"RESUME_TOTAL"	NUMBER	DEFAULT 0	NULL,
	"RESUME_SCORE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "RESUME_SCORE"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_CAREER" IS '경력 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_EDU" IS '학력 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_CERT" IS '자격증 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_FACILITY" IS '기능';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_ACTIVITY" IS '주요활동 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_SOCIAL_EXPERIENCE" IS '사회경험 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_AWARD" IS '수상내역 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_COURSE" IS '교육이수 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_DUTY" IS '병역사항 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_ADD1" IS '추가 입사지원 항목1 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_ADD2" IS '추가 입사지원 항목2 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_ADD3" IS '추가 입사지원 항목3 점수';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_TOTAL" IS '입사지원서 총점';

COMMENT ON COLUMN "RESUME_SCORE"."RESUME_SCORE_DATE" IS '입사지원서 점수부여 날짜';

CREATE TABLE "INTRODUCTION_SCORE" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"INTRO_GROWTH"	NUMBER	DEFAULT 0	NULL,
	"INTRO_PERSONALITY"	NUMBER	DEFAULT 0	NULL,
	"INTRO_SCHOOLDAY"	NUMBER	DEFAULT 0	NULL,
	"INTRO_JOB_EXPERIENCE"	NUMBER	DEFAULT 0	NULL,
	"INTRO_MOTIVATION"	NUMBER	DEFAULT 0	NULL,
	"INTRO_ASPIRATION"	NUMBER	DEFAULT 0	NULL,
	"INTRO_FAMILY"	NUMBER	DEFAULT 0	NULL,
	"INTRO_SUBACTIVITY"	NUMBER	DEFAULT 0	NULL,
	"INTRO_MAJOR"	NUMBER	DEFAULT 0	NULL,
	"INTRO_COURSE"	NUMBER	DEFAULT 0	NULL,
	"INTRO_OBJECTIVE"	NUMBER	DEFAULT 0	NULL,
	"INTRO_CLUB"	NUMBER	DEFAULT 0	NULL,
	"INTRO_VOLUNTEER"	NUMBER	DEFAULT 0	NULL,
	"INTRO_INTRO_ADD1"	NUMBER	DEFAULT 0	NULL,
	"INTRO_INTRO_ADD2"	NUMBER	DEFAULT 0	NULL,
	"INTRO_INTRO_ADD3"	NUMBER	DEFAULT 0	NULL,
	"INTRO_TOTAL"	NUMBER	DEFAULT 0	NULL,
	"INTRO_SCORE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "INTRODUCTION_SCORE"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_GROWTH" IS '성장과정 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_PERSONALITY" IS '성격 장단점 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_SCHOOLDAY" IS '학창시절 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_JOB_EXPERIENCE" IS '직무경험';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_MOTIVATION" IS '지원동기 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_ASPIRATION" IS '입사 후 포부 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_FAMILY" IS '가족소개 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_SUBACTIVITY" IS '교외활동 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_MAJOR" IS '전공선택 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_COURSE" IS '생활진로 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_OBJECTIVE" IS '희망업무 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_CLUB" IS '동아리 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_VOLUNTEER" IS '봉사활동 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_INTRO_ADD1" IS '추가 자기소개 항목1 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_INTRO_ADD2" IS '추가 자기소개 항목2 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_INTRO_ADD3" IS '추가 자기소개 항목3 점수';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_TOTAL" IS '자기소개서 총점';

COMMENT ON COLUMN "INTRODUCTION_SCORE"."INTRO_SCORE_DATE" IS '자기소개서 점수부여날짜';

CREATE TABLE "TEST_SCORE" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"TEST_SUBJECT1"	NUMBER	DEFAULT 0	NULL,
	"TEST_SUBJECT2"	NUMBER	DEFAULT 0	NULL,
	"TEST_SUBJECT3"	NUMBER	DEFAULT 0	NULL,
	"TEST_SUBJECT4"	NUMBER	DEFAULT 0	NULL,
	"TEST_SUBJECT5"	NUMBER	DEFAULT 0	NULL,
	"TEST_ADDSUBJECT1"	NUMBER	DEFAULT 0	NULL,
	"TEST_SUBJECT_ADD2"	NUMBER	DEFAULT 0	NULL,
	"TEST_SUBJECT_ADD3"	NUMBER	DEFAULT 0	NULL,
	"TEST_TOTAL"	NUMBER	DEFAULT 0	NULL,
	"TEST_SCORE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "TEST_SCORE"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "TEST_SCORE"."TEST_SUBJECT1" IS '과목1 점수';

COMMENT ON COLUMN "TEST_SCORE"."TEST_SUBJECT2" IS '과목2 점수';

COMMENT ON COLUMN "TEST_SCORE"."TEST_SUBJECT3" IS '과목3 점수';

COMMENT ON COLUMN "TEST_SCORE"."TEST_SUBJECT4" IS '과목4 점수';

COMMENT ON COLUMN "TEST_SCORE"."TEST_SUBJECT5" IS '과목5 점수';

COMMENT ON COLUMN "TEST_SCORE"."TEST_ADDSUBJECT1" IS '추가 필기시험 과목1 점수';

COMMENT ON COLUMN "TEST_SCORE"."TEST_SUBJECT_ADD2" IS '추가 필기시험 과목2 점수';

COMMENT ON COLUMN "TEST_SCORE"."TEST_SUBJECT_ADD3" IS '추가 필기시험 과목3 점수';

COMMENT ON COLUMN "TEST_SCORE"."TEST_TOTAL" IS '필기시험 총점';

COMMENT ON COLUMN "TEST_SCORE"."TEST_SCORE_DATE" IS '필기시험 점수부여날짜';

CREATE TABLE "COMPETENCY_SCORE" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"COMPETENCY_FACIAL"	NUMBER	DEFAULT 0	NULL,
	"COMPETENCY_POSTURE"	NUMBER	DEFAULT 0	NULL,
	"COMPETENCY_SPEAKING"	NUMBER	DEFAULT 0	NULL,
	"COMPETENCY_QUERY_IDENTIFICATION"	NUMBER	DEFAULT 0	NULL,
	"COMPETENCY_META_COGNITION"	NUMBER	DEFAULT 0	NULL,
	"COMPETENCY_RECOGNITION"	NUMBER	DEFAULT 0	NULL,
	"COMPETENCY_RESOLVE"	NUMBER	DEFAULT 0	NULL,
	"COMPETENCY_EXPRESSION"	NUMBER	DEFAULT 0	NULL,
	"COMPETENCY_LOGIC"	NUMBER	DEFAULT 0	NULL,
	"COMPETENCY_LEADERSHIP"	NUMBER	DEFAULT 0	NULL,
	"COMPETENCY_RELATIONSHIP"	NUMBER	DEFAULT 0	NULL,
	"COMPETENCY_COMPETENCY_ADD1"	NUMBER	DEFAULT 0	NULL,
	"COMPETENCY_COMPETENCY_ADD2"	NUMBER	DEFAULT 0	NULL,
	"COMPETENCY_COMPETENCY_ADD3"	NUMBER	DEFAULT 0	NULL,
	"COMPETENCY_TOTAL"	NUMBER	DEFAULT 0	NULL,
	"COMPETENCY_SCORE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "COMPETENCY_SCORE"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETENCY_FACIAL" IS '시선과 표정 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETENCY_POSTURE" IS '대면자세 및 행동 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETENCY_SPEAKING" IS '언어와 표현 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETENCY_QUERY_IDENTIFICATION" IS '질의파악능력 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETENCY_META_COGNITION" IS '메타인지 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETENCY_RECOGNITION" IS '상황인식능력 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETENCY_RESOLVE" IS '문제해경능력';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETENCY_EXPRESSION" IS '자기표현력 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETENCY_LOGIC" IS '논리력 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETENCY_LEADERSHIP" IS '리더십 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETENCY_RELATIONSHIP" IS '인간관계 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETENCY_COMPETENCY_ADD1" IS '추가 역량평가 항목1 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETENCY_COMPETENCY_ADD2" IS '추가 역량평가 항목2 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETENCY_COMPETENCY_ADD3" IS '추가 역량평가 항목3 점수';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETENCY_TOTAL" IS '역량평가 총점';

COMMENT ON COLUMN "COMPETENCY_SCORE"."COMPETENCY_SCORE_DATE" IS '역량평가 점수부여날짜';

CREATE TABLE "PRACTICE_SCORE" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"PRACTICE_UNDERSTANDING"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_APPROPRIATION"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_KNOWLEDGE"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_EXPERIENCE"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_ADD1"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_ADD2"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_ADD3"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_ADD4"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_ADD5"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_TOTAL"	NUMBER	DEFAULT 0	NULL,
	"PRACTICE_SCORE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "PRACTICE_SCORE"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_UNDERSTANDING" IS '직무이해도 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_APPROPRIATION" IS '직무접학성 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_KNOWLEDGE" IS '실무관련지식 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_EXPERIENCE" IS '실무경험 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_ADD1" IS '추가 실무면접 항목1 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_ADD2" IS '추가 실무면접 항목2 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_ADD3" IS '추가 실무면접 항목3 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_ADD4" IS '추가 실무면접 항목4 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_ADD5" IS '추가 실무면접 항목5 점수';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_TOTAL" IS '실무면접 총점';

COMMENT ON COLUMN "PRACTICE_SCORE"."PRACTICE_SCORE_DATE" IS '실무면접 점수부여날짜';

CREATE TABLE "DISCUSS_SCORE" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"DISCUSS_POSTURE"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_SUBJECT_IDENTIFICATION"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_PROBLEM_IDENTIFICATION"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_RESOLVE"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_QUERY_IDENTIFICATION"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_PROGRESS"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_ADD1"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_ADD2"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_ADD3"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_TOTAL"	NUMBER	DEFAULT 0	NULL,
	"DISCUSS_SCORE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "DISCUSS_SCORE"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_POSTURE" IS '토론자세 점수';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_SUBJECT_IDENTIFICATION" IS '주제파악 점수';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_PROBLEM_IDENTIFICATION" IS '문제파악 점수';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_RESOLVE" IS '해결방안 점수';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_QUERY_IDENTIFICATION" IS '질의파악능력';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_PROGRESS" IS '토론진행 점수';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_ADD1" IS '토론 추가항목1 점수';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_ADD2" IS '토론 추가항목2 점수';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_ADD3" IS '토론 추가항목3 점수';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_TOTAL" IS '토론면접 총점';

COMMENT ON COLUMN "DISCUSS_SCORE"."DISCUSS_SCORE_DATE" IS '토론면접 점수부여날짜';

CREATE TABLE "INTERNSHIP_SCORE" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"INTERN_ACHIVEMENT"	NUMBER	DEFAULT 0	NULL,
	"INTERN_TRUST"	NUMBER	DEFAULT 0	NULL,
	"INTERN_CREATIVITY"	NUMBER	DEFAULT 0	NULL,
	"INTERN_KNOWLEDGE"	NUMBER	DEFAULT 0	NULL,
	"INTERN_DETERMINATION"	NUMBER	DEFAULT 0	NULL,
	"INTERN_COOPERATION"	NUMBER	DEFAULT 0	NULL,
	"INTERN_OBSERVATION"	NUMBER	DEFAULT 0	NULL,
	"INTERN_ACTIVENESS"	NUMBER	DEFAULT 0	NULL,
	"INTERN_RESPONSIBILITY"	NUMBER	DEFAULT 0	NULL,
	"INTERN_EFFICIENCY"	NUMBER	DEFAULT 0	NULL,
	"INTERN_CHALLENGE"	NUMBER	DEFAULT 0	NULL,
	"INTERN_COMMUNITY"	NUMBER	DEFAULT 0	NULL,
	"INTERN_ATTITUDE"	NUMBER	DEFAULT 0	NULL,
	"INTERN_DELIGENCY"	NUMBER	DEFAULT 0	NULL,
	"INTERN_ADD1"	NUMBER	DEFAULT 0	NULL,
	"INTERN_ADD2"	NUMBER	DEFAULT 0	NULL,
	"INTERN_ADD3"	NUMBER	DEFAULT 0	NULL,
	"INTERN_TOTAL"	NUMBER	DEFAULT 0	NULL,
	"INTERN_SCORE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "INTERNSHIP_SCORE"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_ACHIVEMENT" IS '업무달성도';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_TRUST" IS '업무신뢰도 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_CREATIVITY" IS '창의력 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_KNOWLEDGE" IS '직무지식';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_DETERMINATION" IS '판단력';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_COOPERATION" IS '협조성 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_OBSERVATION" IS '규율성';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_ACTIVENESS" IS '적극성 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_RESPONSIBILITY" IS '책임감 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_EFFICIENCY" IS '효율성 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_CHALLENGE" IS '도전의식';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_COMMUNITY" IS '공동체 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_ATTITUDE" IS '태도 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_DELIGENCY" IS '성실성 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_ADD1" IS '추가 인턴십 항목1 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_ADD2" IS '추가 인턴십 항목2 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_ADD3" IS '추가 인턴십 항목3 점수';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_TOTAL" IS '인턴십 총점';

COMMENT ON COLUMN "INTERNSHIP_SCORE"."INTERN_SCORE_DATE" IS '인턴십 점수부여날짜';

CREATE TABLE "INDEPTH_INTERVIEW_SCORE" (
	"APPLY_ID"	VARCHAR2(20)		NOT NULL,
	"INDPETH_INTRODUCTION"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_MOTIVATION"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_PROSANDCONS"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_HOBBY"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_SPECIALTY"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_RELIEVE"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_ROLE_MODEL"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_ORGANIZATION"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_AGGRESSIVENESS"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_LEADERSHIP"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_TEAMWORK"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_CONFLICT"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_SACRIFICE"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_ACHIVEMENT"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_WLBALANCE"	NUMBER	DEFAULT 0	NULL,
	"INPEPTH_NIGHT_SHIFT"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_UNION"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_STRIKE"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_SENIOR"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_ADD1"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_ADD2"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_ADD3"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_TOTAL"	NUMBER	DEFAULT 0	NULL,
	"INDEPTH_SCORE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."APPLY_ID" IS '지원아이디';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDPETH_INTRODUCTION" IS '자기소개 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_MOTIVATION" IS '회사지원동기 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_PROSANDCONS" IS '장단점';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_HOBBY" IS '취미 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_SPECIALTY" IS '특기 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_RELIEVE" IS '스트레스해소 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_ROLE_MODEL" IS '존경인물 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_ORGANIZATION" IS '조직생활 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_AGGRESSIVENESS" IS '공격형 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_LEADERSHIP" IS '리더십 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_TEAMWORK" IS '팀워크 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_CONFLICT" IS '갈등해결 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_SACRIFICE" IS '희생';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_ACHIVEMENT" IS '성취경험 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_WLBALANCE" IS '워라밸 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INPEPTH_NIGHT_SHIFT" IS '야근 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_UNION" IS '노조 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_STRIKE" IS '파업 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_SENIOR" IS '상사갈등 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_ADD1" IS '추가 임원면접 항목1 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_ADD2" IS '추가 임원면접 항목2 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_ADD3" IS '추가 임원면접 항목3 점수';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_TOTAL" IS '임원면접 총점';

COMMENT ON COLUMN "INDEPTH_INTERVIEW_SCORE"."INDEPTH_SCORE_DATE" IS '임원면접 점수부여날짜';

CREATE TABLE "PROCESS_ITEM" (
	"DANNO_ID"	VARCHAR2(20)		NOT NULL,
	"ITEM_CODE_ID2"	VARCHAR2(20)		NOT NULL,
	"PROCESS_ITEM_ASK"	VARCHAR2(200)		NOT NULL
);

COMMENT ON COLUMN "PROCESS_ITEM"."DANNO_ID" IS '세부공고아이디';

COMMENT ON COLUMN "PROCESS_ITEM"."ITEM_CODE_ID2" IS '항목코드';

COMMENT ON COLUMN "PROCESS_ITEM"."PROCESS_ITEM_ASK" IS '질문';

CREATE TABLE "PROCESS_CODE" (
	"PROCESS_CODE_ID"	VARCHAR2(20)		NOT NULL,
	"PROCESS_CODE_NAME"	VVARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "PROCESS_CODE"."PROCESS_CODE_ID" IS '분류코드';

COMMENT ON COLUMN "PROCESS_CODE"."PROCESS_CODE_NAME" IS '채용과정명';

CREATE TABLE "CAREER" (
	"CAREER_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"CAREER_CATEGORY"	VARCHAR2(30)	DEFAULT 자유분야	NULL,
	"CARRER_COMPANY_NAME"	VARCHAR2(50)	DEFAULT 프리랜서	NOT NULL,
	"CARRER_TASK"	VARCHAR2(50)		NULL,
	"CAREER_CLASS"	VARCHAR2(20)		NULL,
	"CAREER_JOIN_DATE"	DATE		NULL,
	"CAREER_RESIGN_DATE"	DATE		NULL,
	"CAREER_SALARY"	NUMBER	DEFAULT 0	NULL,
	"CAREER_ANNUAL"	NUMBER	DEFAULT 0	NULL,
	"CAREER_INSERT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CAREER_DELETE_DATE"	DATE		NULL,
	"ATTACH_ID"	VARCHAR2(20		NULL
);

COMMENT ON COLUMN "CAREER"."CAREER_ID" IS '경력아이디';

COMMENT ON COLUMN "CAREER"."MEM_ID" IS '구직자아이디';

COMMENT ON COLUMN "CAREER"."CAREER_CATEGORY" IS '업종';

COMMENT ON COLUMN "CAREER"."CARRER_COMPANY_NAME" IS '직장명';

COMMENT ON COLUMN "CAREER"."CARRER_TASK" IS '직무';

COMMENT ON COLUMN "CAREER"."CAREER_CLASS" IS '직급';

COMMENT ON COLUMN "CAREER"."CAREER_JOIN_DATE" IS '입사일';

COMMENT ON COLUMN "CAREER"."CAREER_RESIGN_DATE" IS '퇴사일';

COMMENT ON COLUMN "CAREER"."CAREER_SALARY" IS '연봉';

COMMENT ON COLUMN "CAREER"."CAREER_ANNUAL" IS '연차';

COMMENT ON COLUMN "CAREER"."CAREER_INSERT_DATE" IS '경력 작성날짜';

COMMENT ON COLUMN "CAREER"."CAREER_DELETE_DATE" IS '경력 삭제날짜';

COMMENT ON COLUMN "CAREER"."ATTACH_ID" IS '첨부파일아이디';

CREATE TABLE "EDUCATION" (
	"EDU_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"EDU_NAME"	VARCHAR2(50)		NULL,
	"EDU_DEPARTMENT"	VARCHAR2(50)		NOT NULL,
	"EDU_MAJOR"	VARCHAR2(50)		NOT NULL,
	"EDU_ENTERED_DATE"	DATE		NULL,
	"EDU_GRADUATED_DATE"	DATE		NOT NULL,
	"EDU_STATUS"	VARCHAR2(20)	DEFAULT 재학중	NULL,
	"EDU_SCORE"	NUMBER	DEFAULT 0	NOT NULL,
	"EDU_SCORE_STANDARD"	NUMBER	DEFAULT 0	NOT NULL,
	"EDU_INSERT_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"EDU_DELETE_DATE"	DATE		NULL,
	"ATTACH_ID"	VARCHAR2(20		NULL
);

COMMENT ON COLUMN "EDUCATION"."EDU_ID" IS '학력아이디';

COMMENT ON COLUMN "EDUCATION"."MEM_ID" IS '구직자아이디';

COMMENT ON COLUMN "EDUCATION"."EDU_NAME" IS '학교명';

COMMENT ON COLUMN "EDUCATION"."EDU_DEPARTMENT" IS '학과명';

COMMENT ON COLUMN "EDUCATION"."EDU_MAJOR" IS '전공';

COMMENT ON COLUMN "EDUCATION"."EDU_ENTERED_DATE" IS '입학일';

COMMENT ON COLUMN "EDUCATION"."EDU_GRADUATED_DATE" IS '졸업일,중퇴일,자퇴일';

COMMENT ON COLUMN "EDUCATION"."EDU_STATUS" IS '상태';

COMMENT ON COLUMN "EDUCATION"."EDU_SCORE" IS '학점';

COMMENT ON COLUMN "EDUCATION"."EDU_SCORE_STANDARD" IS '기준학점';

COMMENT ON COLUMN "EDUCATION"."EDU_INSERT_DATE" IS '작성날짜';

COMMENT ON COLUMN "EDUCATION"."EDU_DELETE_DATE" IS '학력  삭제날짜';

COMMENT ON COLUMN "EDUCATION"."ATTACH_ID" IS '첨부파일아이디';

CREATE TABLE "CERTIFICATION" (
	"CERT_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"CERT_NO"	VARCHAR2(30)		NOT NULL,
	"CERT_NAME"	VARCHAR2(50)		NOT NULL,
	"CERT_DATE"	DATE		NOT NULL,
	"CERT_INSTITUTION"	VARCHAR2(50)		NOT NULL,
	"CERT_INSERT_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"CERT_DELETE_DATE"	DATE		NULL,
	"ATTACH_ID"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "CERTIFICATION"."CERT_ID" IS '자격증아이디';

COMMENT ON COLUMN "CERTIFICATION"."MEM_ID" IS '구직자아이디';

COMMENT ON COLUMN "CERTIFICATION"."CERT_NO" IS '자격번호';

COMMENT ON COLUMN "CERTIFICATION"."CERT_NAME" IS '자격증명';

COMMENT ON COLUMN "CERTIFICATION"."CERT_DATE" IS '발급일';

COMMENT ON COLUMN "CERTIFICATION"."CERT_INSTITUTION" IS '시행부처';

COMMENT ON COLUMN "CERTIFICATION"."CERT_INSERT_DATE" IS '자격증 작성날짜';

COMMENT ON COLUMN "CERTIFICATION"."CERT_DELETE_DATE" IS '자격증 삭제날짜';

COMMENT ON COLUMN "CERTIFICATION"."ATTACH_ID" IS '첨부파일아이디';

CREATE TABLE "MYINTRODUCTION" (
	"MYINTRO_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"MYINTRO_GROWTH"	VARCHAR2(2000)		NULL,
	"MYINTRO_PERSONALITY"	VARCHAR2(2000)		NULL,
	"MYINTRO_SCHOOLDAY"	VARCHAR2(2000)		NULL,
	"MYINTRO_JOB_EXPRIENCE"	VARCHAR2(2000)		NULL,
	"MYINTRO_MOTIVATION"	VARCHAR2(2000)		NULL,
	"MYINTRO_ASPIRATION"	VARCHAR2(2000)		NULL,
	"MYINTRO_FAMILY"	VARCHAR2(2000)		NULL,
	"MYINTRO_SUBACTIVITY"	VARCHAR2(2000)		NULL,
	"MYINTRO_MAJOR"	VARCHAR2(2000)		NULL,
	"MYINTRO_COURSE"	VARCHAR2(2000)		NULL,
	"MYINTRO_OBJECTIVE"	VARCHAR2(2000)		NULL,
	"MYINTRO_CLUB"	VARCHAR2(2000)		NULL,
	"MYINTRO_VOLUNTEER"	VARCHAR2(2000)		NULL,
	"MYINTRO_ADD1"	VARCHAR2(2000)		NULL,
	"MYINTRO_ADD2"	VARCHAR2(2000)		NULL,
	"MYINTRO_ADD3"	VARCHAR2(2000)		NULL,
	"MYINTRO_INSERT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MYINTRO_DELETE_DATE"	DATE		NULL
);

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_ID" IS '내 자기소개서 아이디';

COMMENT ON COLUMN "MYINTRODUCTION"."MEM_ID" IS '내 아이디';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_GROWTH" IS '내 성장과정';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_PERSONALITY" IS '내 성격 장단점';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_SCHOOLDAY" IS '내 학창시절';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_JOB_EXPRIENCE" IS '내 직무경험';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_MOTIVATION" IS '내 지원동기';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_ASPIRATION" IS '내 입사 후 포부';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_FAMILY" IS '내 가족소개';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_SUBACTIVITY" IS '내 교외활동';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_MAJOR" IS '내 전공선택';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_COURSE" IS '생활진로';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_OBJECTIVE" IS '내 희망업무';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_CLUB" IS '내 동아리';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_VOLUNTEER" IS '내 봉사활동';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_ADD1" IS '내 추가항목1';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_ADD2" IS '내 추가항목2';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_ADD3" IS '내 추가항목3';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_INSERT_DATE" IS '내 자기소개서 작성날짜';

COMMENT ON COLUMN "MYINTRODUCTION"."MYINTRO_DELETE_DATE" IS '내 자기소개서 삭제날짜';

CREATE TABLE "FACILITY" (
	"FACILITY_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"FACILITY_NAME"	VARCHAR2(50)		NOT NULL,
	"FACILITY_CATEGORY"	VARCHAR2(50)		NOT NULL,
	"FACILITY_LEVEL"	VARCHAR2(30)	DEFAULT 초급	NOT NULL,
	"FACILITY_GETDATE"	DATE		NOT NULL,
	"FACILITY_PERIOD"	NUMBER	DEFAULT 0	NOT NULL,
	"FACILITY_INSERT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"FACILITY_DELETE_DATE"	DATE		NULL,
	"ATTACH_ID"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "FACILITY"."FACILITY_ID" IS '기능아이디';

COMMENT ON COLUMN "FACILITY"."MEM_ID" IS '구직자아이디';

COMMENT ON COLUMN "FACILITY"."FACILITY_NAME" IS '기능명';

COMMENT ON COLUMN "FACILITY"."FACILITY_CATEGORY" IS '기능종류';

COMMENT ON COLUMN "FACILITY"."FACILITY_LEVEL" IS '수준';

COMMENT ON COLUMN "FACILITY"."FACILITY_GETDATE" IS '취득일';

COMMENT ON COLUMN "FACILITY"."FACILITY_PERIOD" IS '훈련기간';

COMMENT ON COLUMN "FACILITY"."FACILITY_INSERT_DATE" IS '기능 작성날짜';

COMMENT ON COLUMN "FACILITY"."FACILITY_DELETE_DATE" IS '기능 삭제 날짜';

COMMENT ON COLUMN "FACILITY"."ATTACH_ID" IS '첨부파일아이디';

CREATE TABLE "ACTIVITY" (
	"ACT_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"ACT_NAME"	VARCHAR2(50)		NOT NULL,
	"ACT_CATEGORY"	VARCAHR2(50)		NOT NULL,
	"ACT_INSTITUTION"	VARCAHR2(50)		NULL,
	"ACT_PERIOD"	NUMBER	DEFAULT 0	NOT NULL,
	"ACT_INSERT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ACT_DELETE_DATE"	DATE		NULL,
	"ATTACH_ID"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "ACTIVITY"."ACT_ID" IS '주요활동아이디';

COMMENT ON COLUMN "ACTIVITY"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "ACTIVITY"."ACT_NAME" IS '주요활동명';

COMMENT ON COLUMN "ACTIVITY"."ACT_CATEGORY" IS '주요활동종류';

COMMENT ON COLUMN "ACTIVITY"."ACT_INSTITUTION" IS '주요활동기관';

COMMENT ON COLUMN "ACTIVITY"."ACT_PERIOD" IS '주요활동기간';

COMMENT ON COLUMN "ACTIVITY"."ACT_INSERT_DATE" IS '주요활동 작성날짜';

COMMENT ON COLUMN "ACTIVITY"."ACT_DELETE_DATE" IS '주요활동 삭제날짜';

COMMENT ON COLUMN "ACTIVITY"."ATTACH_ID" IS '첨부파일아이디';

CREATE TABLE "AWARD" (
	"AWARD_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"AWARD_COMPETITION"	VARCHAR2(50)		NOT NULL,
	"AWARD_NAME"	VARCHAR2(50)		NOT NULL,
	"AWARD_CATEGORY"	VARCHAR2(50)		NOT NULL,
	"AWARD_DATE"	DATE		NOT NULL,
	"AWARD_INSTITUTION"	VARCHAR2(50)		NOT NULL,
	"AWARD_INSERT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"AWARD_DELETE_DATE"	DATE		NULL,
	"ATTACH_ID"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "AWARD"."AWARD_ID" IS '수상내역아이디';

COMMENT ON COLUMN "AWARD"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "AWARD"."AWARD_COMPETITION" IS '수상대회명';

COMMENT ON COLUMN "AWARD"."AWARD_NAME" IS '수상명';

COMMENT ON COLUMN "AWARD"."AWARD_CATEGORY" IS '수상대회종류';

COMMENT ON COLUMN "AWARD"."AWARD_DATE" IS '수상날짜';

COMMENT ON COLUMN "AWARD"."AWARD_INSTITUTION" IS '수상기관';

COMMENT ON COLUMN "AWARD"."AWARD_INSERT_DATE" IS '수상내역 작성날짜';

COMMENT ON COLUMN "AWARD"."AWARD_DELETE_DATE" IS '수상내역 삭제날짜';

COMMENT ON COLUMN "AWARD"."ATTACH_ID" IS '첨부파일아이디';

CREATE TABLE "COURSE" (
	"COURSE_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"COURSE_NAME"	VARCHAR2(50)		NOT NULL,
	"COURSE_CATEGORY"	VARCHAR2(30)		NOT NULL,
	"COURSE_INSTITUTION"	VARCHAR2(50)		NOT NULL,
	"COURSE_PERIOD"	NUMBER	DEFAULT 0	NOT NULL,
	"COURSE_INSERT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COURSE_DELETE_DATE"	DATE		NULL,
	"ATTACH_ID"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "COURSE"."COURSE_ID" IS '교육이수아이디';

COMMENT ON COLUMN "COURSE"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "COURSE"."COURSE_NAME" IS '교육명';

COMMENT ON COLUMN "COURSE"."COURSE_CATEGORY" IS '교육종류';

COMMENT ON COLUMN "COURSE"."COURSE_INSTITUTION" IS '교육기관';

COMMENT ON COLUMN "COURSE"."COURSE_PERIOD" IS '교육기간';

COMMENT ON COLUMN "COURSE"."COURSE_INSERT_DATE" IS '교육이수 작성날짜';

COMMENT ON COLUMN "COURSE"."COURSE_DELETE_DATE" IS '교육이수 삭제날짜';

COMMENT ON COLUMN "COURSE"."ATTACH_ID" IS '첨부파일아이디';

CREATE TABLE "REVIEW" (
	"REVIEW_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"REVIEW_TITLE"	VARCHAR2(50)		NOT NULL,
	"REVIEW_CONTENT"	VARCHAR2(1000)		NULL,
	"REVIEW_DATE"	DATE		NULL,
	"REVIEW_ATTATCH"	VARCHAR2(100)		NOT NULL,
	"REVIEW_SCORE"	NUMBER(1)	DEFAULT 1	NULL,
	"COMPANY_ID"	VARCHAR2(20)		NOT NULL,
	"REVIEW_CHECK"	NUMBER(1)	DEFAULT 0	NULL
);

COMMENT ON COLUMN "REVIEW"."REVIEW_ID" IS '리뷰아이디';

COMMENT ON COLUMN "REVIEW"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "REVIEW"."REVIEW_TITLE" IS '리뷰제목';

COMMENT ON COLUMN "REVIEW"."REVIEW_CONTENT" IS '리뷰내용';

COMMENT ON COLUMN "REVIEW"."REVIEW_DATE" IS '리뷰날짜';

COMMENT ON COLUMN "REVIEW"."REVIEW_ATTATCH" IS '리뷰첨부파일';

COMMENT ON COLUMN "REVIEW"."REVIEW_SCORE" IS '리뷰별점';

COMMENT ON COLUMN "REVIEW"."REVIEW_CHECK" IS '리뷰승인여부';

CREATE TABLE "CUT" (
	"CUT_ID"	VARCHAR2(20)		NOT NULL,
	"CUT_DATE"	DATE		NULL,
	"CUT_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"CUT_CHECK"	NUMBER(1)	DEFAULT 0	NULL
);

COMMENT ON COLUMN "CUT"."CUT_ID" IS '차단아이디';

COMMENT ON COLUMN "CUT"."CUT_DATE" IS '차단일자';

COMMENT ON COLUMN "CUT"."CUT_CONTENT" IS '차단사유';

COMMENT ON COLUMN "CUT"."MEM_ID" IS '차단당한회원아이디';

COMMENT ON COLUMN "CUT"."CUT_CHECK" IS '차단만료여부';

CREATE TABLE "BLACKLIST" (
	"BLACKLIST_ID"	VARCHAR2(20)		NOT NULL,
	"BLACKLIST_DATE"	DATE		NULL,
	"BLACKLIST_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"BLACKLIST_CHECK"	NUMBER(1)	DEFAULT 0	NULL
);

COMMENT ON COLUMN "BLACKLIST"."BLACKLIST_ID" IS '블랙리스트아이디';

COMMENT ON COLUMN "BLACKLIST"."BLACKLIST_DATE" IS '블랙리스트된 날짜';

COMMENT ON COLUMN "BLACKLIST"."BLACKLIST_CONTENT" IS '블랙리스트 사유';

COMMENT ON COLUMN "BLACKLIST"."MEM_ID" IS '블랙당한회원아이디';

COMMENT ON COLUMN "BLACKLIST"."BLACKLIST_CHECK" IS '블랙만료여부';

CREATE TABLE "COMPANY" (
	"COMPANY_ID"	VARCHAR2(20)		NOT NULL,
	"COMPANY_NUMBER"	VARCHAR2(20)		NOT NULL,
	"COMPANY_NAME"	VARCHAR2(100)		NOT NULL,
	"COMPANY_REPRESENTATIVE_NAME"	VARCHAR2(20)		NOT NULL,
	"COMPANY_BUSINESS_NUMBER"	VARCHAR2(20)		NOT NULL,
	"COMPANY_DEFAULT_ADRESS"	VARCHAR2(100)		NOT NULL,
	"COMPANY_DETAIL_ADRESS"	VARCHAR2(100)		NOT NULL,
	"COMPANY_ZIP"	VARCHAR2(20)		NOT NULL,
	"COMPANY_PHONE"	VARCHAR2(20)		NOT NULL,
	"COMPANY_ESTABLISHMENT_DATE"	DATE		NOT NULL,
	"COMPANY_SMALL_MEDIUM_ENTERPRISE_STATUS"	VARCHAR2(20)		NOT NULL,
	"COMPANY_EMPLOYEES_NUMBER"	VARCHAR2(100)		NULL,
	"COMPANY_AVERAGE_CONTINUOUS_WORK"	VARCHAR2(100)		NULL,
	"COMPANY_PERSON_AVERAGE_SALARY"	VARCHAR2(100)		NULL,
	"COMPANY_MAIN_BUSINESS_NAME"	VARCHAR2(100)		NOT NULL,
	"COMPANY_CHECK"	NUMBER(1)	DEFAULT 0	NULL,
	"COMPANY_LOGO"	VARCHAR2(200)		NULL
);

COMMENT ON COLUMN "COMPANY"."COMPANY_ID" IS '회사아이디';

COMMENT ON COLUMN "COMPANY"."COMPANY_NUMBER" IS '법인등록번호';

COMMENT ON COLUMN "COMPANY"."COMPANY_NAME" IS '법인명';

COMMENT ON COLUMN "COMPANY"."COMPANY_REPRESENTATIVE_NAME" IS '회사대표자성명';

COMMENT ON COLUMN "COMPANY"."COMPANY_BUSINESS_NUMBER" IS '사업자등록번호';

COMMENT ON COLUMN "COMPANY"."COMPANY_DEFAULT_ADRESS" IS '회사기본주소';

COMMENT ON COLUMN "COMPANY"."COMPANY_DETAIL_ADRESS" IS '회사상세주소';

COMMENT ON COLUMN "COMPANY"."COMPANY_ZIP" IS '회사우편번호';

COMMENT ON COLUMN "COMPANY"."COMPANY_PHONE" IS '회사전화번호';

COMMENT ON COLUMN "COMPANY"."COMPANY_ESTABLISHMENT_DATE" IS '회사설립일자';

COMMENT ON COLUMN "COMPANY"."COMPANY_SMALL_MEDIUM_ENTERPRISE_STATUS" IS '회사형태';

COMMENT ON COLUMN "COMPANY"."COMPANY_EMPLOYEES_NUMBER" IS '회사종업원수';

COMMENT ON COLUMN "COMPANY"."COMPANY_AVERAGE_CONTINUOUS_WORK" IS '종업원평균근속기간내용';

COMMENT ON COLUMN "COMPANY"."COMPANY_PERSON_AVERAGE_SALARY" IS '회사1인평균급여금액';

COMMENT ON COLUMN "COMPANY"."COMPANY_MAIN_BUSINESS_NAME" IS '회사주요사업명';

COMMENT ON COLUMN "COMPANY"."COMPANY_CHECK" IS '승인여부';

COMMENT ON COLUMN "COMPANY"."COMPANY_LOGO" IS '회사로고';

CREATE TABLE "BOARD_REPORT" (
	"BOARD_REPORT_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"BOARD_REPORT_NO"	VARCHAR2(20)		NOT NULL,
	"BOARD_REPORT_DATE"	DATE		NULL,
	"BOARD_REPORT_REASON"	VARCHAR2(1000)		NOT NULL,
	"BOARD_REPORT_CHECK"	NUMBER(1)	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "BOARD_REPORT"."BOARD_REPORT_ID" IS '게시판신고아이디';

COMMENT ON COLUMN "BOARD_REPORT"."BOARD_REPORT_NO" IS '게시판신고글번호';

COMMENT ON COLUMN "BOARD_REPORT"."BOARD_REPORT_DATE" IS '신고일자';

COMMENT ON COLUMN "BOARD_REPORT"."BOARD_REPORT_REASON" IS '신고사유';

COMMENT ON COLUMN "BOARD_REPORT"."BOARD_REPORT_CHECK" IS '처리상태';

CREATE TABLE "COMMENT_REPORT" (
	"COMMENT_REPORT_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"COMMENT_REPORT_DATE"	DATE		NULL,
	"COMMENT_REPORT_REASON"	VARCHAR2(1000)		NULL,
	"COMM_ID"	VARCHAR2(10)		NOT NULL,
	"COMMENT_REPORT_CHECK"	NUMBER(1)	DEFAULT 0	NULL
);

COMMENT ON COLUMN "COMMENT_REPORT"."COMMENT_REPORT_ID" IS '댓글신고아이디';

COMMENT ON COLUMN "COMMENT_REPORT"."MEM_ID" IS '신고한회원아이디';

COMMENT ON COLUMN "COMMENT_REPORT"."COMMENT_REPORT_DATE" IS '신고일자';

COMMENT ON COLUMN "COMMENT_REPORT"."COMMENT_REPORT_REASON" IS '신고사유';

COMMENT ON COLUMN "COMMENT_REPORT"."COMM_ID" IS '댓글ID';

COMMENT ON COLUMN "COMMENT_REPORT"."COMMENT_REPORT_CHECK" IS '처리상태';

CREATE TABLE "BANKING" (
	"BANKING_ACCOUNT"	VARCHAR2(50)		NOT NULL,
	"BANKING_BANK"	VARCHAR2(20)		NOT NULL,
	"BANKING_NM"	VARCHAR2(20)		NOT NULL,
	"BANKING_BALANCE"	NUMBER		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BANKING"."BANKING_ACCOUNT" IS '계좌번호';

COMMENT ON COLUMN "BANKING"."BANKING_BANK" IS '은행';

COMMENT ON COLUMN "BANKING"."BANKING_NM" IS '예금주';

COMMENT ON COLUMN "BANKING"."BANKING_BALANCE" IS '잔액';

COMMENT ON COLUMN "BANKING"."MEM_ID" IS '회원아이디';

CREATE TABLE "ALRAM" (
	"ALRAM_ID"	VARCHAR2(20)		NOT NULL,
	"ALRAM_CONTENT"	VARCHAR2(500)		NOT NULL,
	"ALRAM_DATE"	DATE		NULL,
	"ALRAM_READ_STATUS"	NUMBER(1)	DEFAULT 0	NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "ALRAM"."ALRAM_ID" IS '알림아이디';

COMMENT ON COLUMN "ALRAM"."ALRAM_CONTENT" IS '알림내역';

COMMENT ON COLUMN "ALRAM"."ALRAM_DATE" IS '알림날짜';

COMMENT ON COLUMN "ALRAM"."ALRAM_READ_STATUS" IS '알림읽기여부';

COMMENT ON COLUMN "ALRAM"."MEM_ID" IS '알림받은회원아이디';

CREATE TABLE "HELP" (
	"HELP_ID"	VARCHAR2(20)		NOT NULL,
	"HELP_SORT"	VARCHAR2(50)		NOT NULL,
	"HELP_CATE"	VARCHAR2(50)		NOT NULL,
	"HELP_TITLE"	VARCHAR2(100)		NOT NULL,
	"HELP_CONTENT"	CLOB		NOT NULL,
	"HELP_DATE"	DATE		NOT NULL,
	"HELP_MODI_DATE"	DATE		NOT NULL,
	"HELP_HIT"	NUMBER(5)	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "HELP"."HELP_ID" IS '도움말ID';

COMMENT ON COLUMN "HELP"."HELP_SORT" IS '구분';

COMMENT ON COLUMN "HELP"."HELP_CATE" IS '분류명';

COMMENT ON COLUMN "HELP"."HELP_TITLE" IS '제목';

COMMENT ON COLUMN "HELP"."HELP_CONTENT" IS '내용';

COMMENT ON COLUMN "HELP"."HELP_DATE" IS '작성일';

COMMENT ON COLUMN "HELP"."HELP_MODI_DATE" IS '수정일';

COMMENT ON COLUMN "HELP"."HELP_HIT" IS '조회수';

CREATE TABLE "NEWS" (
	"NEWS_NO"	VARCHAR2(20)		NOT NULL,
	"NEWS_NAME"	VARCHAR2(50)		NOT NULL,
	"NEWS_DATE"	DATE		NOT NULL,
	"NEWS_FIELD"	VARCHAR2(50)		NULL,
	"NEWS_HIT"	NUMBER		NULL,
	"NEWS_CONTENT"	VARCHAR2(500)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "NEWS"."NEWS_NO" IS '뉴스 번호';

COMMENT ON COLUMN "NEWS"."NEWS_NAME" IS '제목';

COMMENT ON COLUMN "NEWS"."NEWS_DATE" IS '작성일';

COMMENT ON COLUMN "NEWS"."NEWS_FIELD" IS '분야';

COMMENT ON COLUMN "NEWS"."NEWS_HIT" IS '조회수';

COMMENT ON COLUMN "NEWS"."NEWS_CONTENT" IS '내용';

COMMENT ON COLUMN "NEWS"."MEM_ID" IS '회원아이디';

CREATE TABLE "CONTEST" (
	"CONT_NO"	VARCHAR2(20)		NOT NULL,
	"CONT_NAME"	VARCHAR2(50)		NOT NULL,
	"CONT_CO"	VARCHAR2(50)		NOT NULL,
	"CONT_START"	VARCHAR2(20)		NOT NULL,
	"CONT_DEAD"	VARCHAR2(20)		NOT NULL,
	"CONT_FIELD"	VARCHAR2(50)		NULL,
	"CONT_IMG"	VARCHAR2(100)		NULL,
	"CONT_CONTENT"	VARCHAR2(500)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "CONTEST"."CONT_NO" IS '공모전 번호';

COMMENT ON COLUMN "CONTEST"."CONT_NAME" IS '공모전명';

COMMENT ON COLUMN "CONTEST"."CONT_CO" IS '주관 기관';

COMMENT ON COLUMN "CONTEST"."CONT_START" IS '시작일';

COMMENT ON COLUMN "CONTEST"."CONT_DEAD" IS '마감일';

COMMENT ON COLUMN "CONTEST"."CONT_FIELD" IS '공모분야';

COMMENT ON COLUMN "CONTEST"."CONT_IMG" IS '사진';

COMMENT ON COLUMN "CONTEST"."CONT_CONTENT" IS '내용';

COMMENT ON COLUMN "CONTEST"."MEM_ID" IS '회원아이디';

CREATE TABLE "NOTICE" (
	"NOTICE_ID"	VARCHAR2(20)		NOT NULL,
	"NOTICE_SORT"	VARCHAR2(50)	DEFAULT 전체	NOT NULL,
	"NOTICE_TITLE"	VARCHAR2(100)		NOT NULL,
	"NOTICE_DATE"	DATE		NOT NULL,
	"NOTICE_CONTENT"	CLOB		NOT NULL,
	"NOTICE_STATE"	NUMBER(5)	DEFAULT 접수	NOT NULL,
	"NOTICE_HIT"	NUMBER(4,0)	DEFAULT 0	NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_ID" IS '공지사항ID';

COMMENT ON COLUMN "NOTICE"."NOTICE_SORT" IS '구분';

COMMENT ON COLUMN "NOTICE"."NOTICE_TITLE" IS '제목';

COMMENT ON COLUMN "NOTICE"."NOTICE_DATE" IS '작성일';

COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT" IS '내용';

COMMENT ON COLUMN "NOTICE"."NOTICE_STATE" IS '처리상태';

COMMENT ON COLUMN "NOTICE"."NOTICE_HIT" IS '조회수';

COMMENT ON COLUMN "NOTICE"."MEM_ID" IS '회원아이디';

CREATE TABLE "EXPROD" (
	"EXPROD_ID"	VARCHAR2(20)		NOT NULL,
	"EXPROD_START"	DATE		NULL,
	"EXPROD_END"	DATE		NULL,
	"EXPROD_TARGET"	VARCHAR2(30)		NULL,
	"EXPROD_NM"	VARCHAR2(100)		NULL,
	"EXPROD_PRICE"	NUMBER		NULL,
	"EXPROD_WAY"	VARCHAR2(100)		NULL,
	"EXPROD_TIME"	DATE		NULL,
	"EXPROD_DETAIL"	VARCHAR2(2000)		NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"EXPROD_APROVAL"	NUMBER		NULL,
	"EXLPROD_ID"	VARCHAR2(10)		NOT NULL
);

CREATE TABLE "COMMENT" (
	"COMM_ID"	VARCHAR2(20)		NOT NULL,
	"BOARD_ID"	VARCHAR2(20)		NOT NULL,
	"COMM_ID2"	VARCHAR2(20)		NOT NULL,
	"COMM_DATE"	DATE		NOT NULL,
	"TOTAL_COMM"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"COMM_CONTENT"	VARCHAR2		NOT NULL,
	"GOOD_COMM"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"COMM_WRITER"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "COMMENT"."COMM_ID" IS '댓글ID';

COMMENT ON COLUMN "COMMENT"."BOARD_ID" IS '게시판ID';

COMMENT ON COLUMN "COMMENT"."COMM_ID2" IS '상위댓글ID';

COMMENT ON COLUMN "COMMENT"."COMM_DATE" IS '작성일';

COMMENT ON COLUMN "COMMENT"."TOTAL_COMM" IS '댓글수';

COMMENT ON COLUMN "COMMENT"."COMM_CONTENT" IS '댓글내용';

COMMENT ON COLUMN "COMMENT"."GOOD_COMM" IS '댓글공감수';

COMMENT ON COLUMN "COMMENT"."COMM_WRITER" IS '댓글작성자';

CREATE TABLE "EXCART" (
	"EXCART_ID"	VARCHAR2(20)		NOT NULL,
	"EXPROD_ID"	VARCHAR2(10)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"EXCART_PRICE"	NUMBER		NULL
);

CREATE TABLE "EXPERT" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"EXPERT_APPROVAL"	NUMBER		NULL,
	"EXPERT_APPROVAL_DATE"	DATE		NULL,
	"EXPERT_INTRODUCTION"	VARCHAR2(200)		NULL,
	"EXPERT_JOINPATH"	VARCHAR2(30)		NULL,
	"EXPERT_FILED"	VARCHAR2(10)		NULL,
	"EXPERT_TAG"	VARCHAR2(40)		NULL,
	"EXPERT_ADDR"	VARCHAR2(200)		NULL,
	"EXPERT_TEL"	VARCHAR2(20)		NULL,
	"EXPERT_EMAIL"	VARCHAR2(30)		NULL,
	"EXLPROD_ID"	VARCHAR2(20)		NOT NULL,
	"EXPRET_MONEY"	NUMBER		NULL
);

CREATE TABLE "INTEREST" (
	"INTE_NO"	VARCHAR2(20)		NOT NULL,
	"INTE_DATE"	DATE		NOT NULL,
	"PR_NO"	VARCHAR2(10)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "INTEREST"."INTE_NO" IS '관심인재 번호';

COMMENT ON COLUMN "INTEREST"."INTE_DATE" IS '스크랩 날짜';

CREATE TABLE "TODAYSEE" (
	"TODAY_NO"	VARCHAR2(20)		NOT NULL,
	"PR_NO"	VARCHAR2(10)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "TODAYSEE"."TODAY_NO" IS '조회 번호';

CREATE TABLE "EXREVIEW" (
	"EXREVIEW_ID"	VARCHAR2(20)		NOT NULL,
	"EXREVIEW_NM"	VARCHAR2(100)		NULL,
	"EXREVIEW_WRITER"	VARCHAR2(50)		NULL,
	"EXREVIEW_PASS"	VARCHAR2(20)		NULL,
	"EXREVIEW_CONTENT"	VARCHAR2(2000)		NULL,
	"EXREVIEW_HIT"	NUMBER		NULL,
	"EXCART_ID"	VARCHAR2(10)		NOT NULL,
	"EXREVIEW_DATE"	DATE		NULL,
	"EXREVIEW_SCORE"	VARCHAR2(5)		NULL,
	"Field"	VARCHAR(255)		NULL
);

CREATE TABLE "EXEVENT" (
	"EXEVENT_ID"	VARCHAR2(20)		NOT NULL,
	"EXEVENT_NM"	VARCHAR2(50)		NULL,
	"EXEVENT_CONTENT"	VARCHAR2(2000)		NULL,
	"EXEVENT_START"	DATE		NULL,
	"EXEVENT_END"	DATE		NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "EXEVENT"."MEM_ID" IS '회원아이디';

CREATE TABLE "BOARD" (
	"BOARD_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"SUB_CATE"	VARCHAR2(50)	DEFAULT 전체	NOT NULL,
	"BOARD_VIEWS"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"JOB_CATE"	VARCHAR2(50)		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(50)		NOT NULL,
	"BOARD_CONTENT"	CLOB		NOT NULL,
	"BOARD_WRITER"	VARCHAR2(50)		NOT NULL,
	"BOARD_DATE"	DATE		NOT NULL,
	"TOTAL_GOOD"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"BOARD_GOOD"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"BOARD_FUN"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"BOARD_HELP"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"BOARD_CHEERUP"	NUMBER(5)	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_ID" IS '게시판ID';

COMMENT ON COLUMN "BOARD"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "BOARD"."SUB_CATE" IS '주제별분류';

COMMENT ON COLUMN "BOARD"."BOARD_VIEWS" IS '조회수';

COMMENT ON COLUMN "BOARD"."JOB_CATE" IS '직무별분류';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '내용';

COMMENT ON COLUMN "BOARD"."BOARD_WRITER" IS '작성자';

COMMENT ON COLUMN "BOARD"."BOARD_DATE" IS '작성일';

COMMENT ON COLUMN "BOARD"."TOTAL_GOOD" IS '전체공감수';

COMMENT ON COLUMN "BOARD"."BOARD_GOOD" IS '좋아요';

COMMENT ON COLUMN "BOARD"."BOARD_FUN" IS '재밌어요';

COMMENT ON COLUMN "BOARD"."BOARD_HELP" IS '도움돼요';

COMMENT ON COLUMN "BOARD"."BOARD_CHEERUP" IS '힘내요';

CREATE TABLE "INCUMBENT_INTERVIEW" (
	"INTERVIEW_ID"	VARCHAR2(20)		NOT NULL,
	"ANNO_ID"	VARCHAR2(20)		NOT NULL,
	"JOB_CATE"	VARCHAR2(50)		NOT NULL,
	"RECRU_STATUS"	NUMBER(5)		NULL,
	"INCUM_TITLE"	VARCHAR2(50)		NOT NULL,
	"COMPANY_NAME"	VARCHAR2(50)		NULL,
	"DEPARTMENT_NAME"	VARCHAR2(50)		NULL,
	"INCUM_NAME"	VARCHAR2(50)		NOT NULL,
	"INCUM_DATE"	DATE		NOT NULL,
	"INCUM_VIEWS"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"INCUM_CONTENT"	CLOB		NOT NULL
);

COMMENT ON COLUMN "INCUMBENT_INTERVIEW"."INTERVIEW_ID" IS '현직자인터뷰ID';

COMMENT ON COLUMN "INCUMBENT_INTERVIEW"."ANNO_ID" IS '현직자인터뷰ID';

COMMENT ON COLUMN "INCUMBENT_INTERVIEW"."JOB_CATE" IS '직무별분류';

COMMENT ON COLUMN "INCUMBENT_INTERVIEW"."RECRU_STATUS" IS '채용여부';

COMMENT ON COLUMN "INCUMBENT_INTERVIEW"."INCUM_TITLE" IS '제목';

COMMENT ON COLUMN "INCUMBENT_INTERVIEW"."COMPANY_NAME" IS '회사명';

COMMENT ON COLUMN "INCUMBENT_INTERVIEW"."DEPARTMENT_NAME" IS '부서명';

COMMENT ON COLUMN "INCUMBENT_INTERVIEW"."INCUM_NAME" IS '작성자';

COMMENT ON COLUMN "INCUMBENT_INTERVIEW"."INCUM_DATE" IS '작성일';

COMMENT ON COLUMN "INCUMBENT_INTERVIEW"."INCUM_VIEWS" IS '조회수';

COMMENT ON COLUMN "INCUMBENT_INTERVIEW"."INCUM_CONTENT" IS '내용';

CREATE TABLE "COUNSELING" (
	"COUN_NO"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"COUN_TITLE"	VARCHAR2(50)		NULL,
	"COUN_CONTENT"	CLOB		NULL,
	"COUN_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"COUN_STATE"	NUMBER	DEFAULT 1	NULL,
	"COUN_PARENT"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "COUNSELING"."COUN_NO" IS '게시판ID';

COMMENT ON COLUMN "COUNSELING"."MEM_ID" IS '회원아이디';

COMMENT ON COLUMN "COUNSELING"."COUN_TITLE" IS '제목';

COMMENT ON COLUMN "COUNSELING"."COUN_CONTENT" IS '내용';

COMMENT ON COLUMN "COUNSELING"."COUN_DATE" IS '작성일';

COMMENT ON COLUMN "COUNSELING"."COUN_STATE" IS '글상태
0: 삭제됨
1: 등록됨';

COMMENT ON COLUMN "COUNSELING"."COUN_PARENT" IS '부모글';

CREATE TABLE "RESUME_FORM" (
	"RESUME_FORM_ID"	VARCHAR2(20)		NOT NULL,
	"RESUME_FORM_CATE"	VARCHAR2(50)		NOT NULL,
	"FORM_TITLE"	VARCHAR2(100)		NOT NULL,
	"DOWNLOAD"	NUMBER(20)	DEFAULT 0	NOT NULL,
	"FORM_VIEWS"	NUMBER(20)	DEFAULT 0	NOT NULL,
	"FORM_CONTENT"	VARCHAR2		NOT NULL
);

COMMENT ON COLUMN "RESUME_FORM"."RESUME_FORM_ID" IS '이력서양식ID';

COMMENT ON COLUMN "RESUME_FORM"."RESUME_FORM_CATE" IS '이력서분류';

COMMENT ON COLUMN "RESUME_FORM"."FORM_TITLE" IS '제목';

COMMENT ON COLUMN "RESUME_FORM"."DOWNLOAD" IS '다운로드수';

COMMENT ON COLUMN "RESUME_FORM"."FORM_VIEWS" IS '조회수';

COMMENT ON COLUMN "RESUME_FORM"."FORM_CONTENT" IS '내용';

CREATE TABLE "CORPORATION_TRANSPARENCY" (
	"COMPANY_ID"	VARCHAR2(20)		NOT NULL,
	"RECRU_NO"	VARCHAR2(50)		NULL,
	"TYPE_OF_WORK"	VARCHAR2(50)		NULL,
	"YOUTH_BENEFIT"	VARCHAR2(50)		NULL,
	"INTER_EXTER"	VARCHAR2(50)		NULL,
	"NUM_OF_YEARS"	VARCHAR2(50)		NULL,
	"AGE"	VARCHAR2(50)		NULL,
	"OVERTIME"	VARCHAR2(50)		NULL,
	"COMPANY_HISTORY"	VARCHAR2(50)		NULL,
	"ENTER_TYPE"	VARCHAR2(50)		NULL,
	"NUM_OF_EMP"	VARCHAR2(50)		NULL,
	"BENEFIT"	VARCHAR2(50)		NULL,
	"DINING_TOGETHER"	VARCHAR2(50)		NULL,
	"TRANS_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "CORPORATION_TRANSPARENCY"."COMPANY_ID" IS '회사아이디';

COMMENT ON COLUMN "CORPORATION_TRANSPARENCY"."RECRU_NO" IS '채용횟수';

COMMENT ON COLUMN "CORPORATION_TRANSPARENCY"."TYPE_OF_WORK" IS '근무형태';

COMMENT ON COLUMN "CORPORATION_TRANSPARENCY"."YOUTH_BENEFIT" IS '청년혜택';

COMMENT ON COLUMN "CORPORATION_TRANSPARENCY"."INTER_EXTER" IS '내,외근';

COMMENT ON COLUMN "CORPORATION_TRANSPARENCY"."NUM_OF_YEARS" IS '근속연수';

COMMENT ON COLUMN "CORPORATION_TRANSPARENCY"."AGE" IS '연령구성';

COMMENT ON COLUMN "CORPORATION_TRANSPARENCY"."OVERTIME" IS '야근빈도';

COMMENT ON COLUMN "CORPORATION_TRANSPARENCY"."COMPANY_HISTORY" IS '업력';

COMMENT ON COLUMN "CORPORATION_TRANSPARENCY"."ENTER_TYPE" IS '기업형태';

COMMENT ON COLUMN "CORPORATION_TRANSPARENCY"."NUM_OF_EMP" IS '직원수';

COMMENT ON COLUMN "CORPORATION_TRANSPARENCY"."BENEFIT" IS '복리후생';

COMMENT ON COLUMN "CORPORATION_TRANSPARENCY"."DINING_TOGETHER" IS '회식빈도';

COMMENT ON COLUMN "CORPORATION_TRANSPARENCY"."TRANS_DATE" IS '등록일';

CREATE TABLE "TRANSPARENCY_CALCULATE" (
	"COMPANY_ID"	VARCHAR2(20)		NOT NULL,
	"FORM_WRITING"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"JOIN_RESIGN_RATIO"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"AVER_SALARY_RANK"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"SALES"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"BUSINESS_PROFITS"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"CURRENT_PROFIT"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"LOCATION_IN_INDUSTRY"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"INCREASE_EMPLOYEES"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"REVIEW_SCORE"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"RENEWAL"	DATE		NOT NULL,
	"TRAN_TOTAL"	NUMBER(5)	DEFAULT 0	NOT NULL,
	"TRAN_GRADE"	VARCHAR2(5)		NOT NULL
);

COMMENT ON COLUMN "TRANSPARENCY_CALCULATE"."COMPANY_ID" IS '회사아이디';

COMMENT ON COLUMN "TRANSPARENCY_CALCULATE"."FORM_WRITING" IS '양식작성개수';

COMMENT ON COLUMN "TRANSPARENCY_CALCULATE"."JOIN_RESIGN_RATIO" IS '입,퇴사율';

COMMENT ON COLUMN "TRANSPARENCY_CALCULATE"."AVER_SALARY_RANK" IS '평균연봉순위';

COMMENT ON COLUMN "TRANSPARENCY_CALCULATE"."SALES" IS '매출액';

COMMENT ON COLUMN "TRANSPARENCY_CALCULATE"."BUSINESS_PROFITS" IS '영업이익';

COMMENT ON COLUMN "TRANSPARENCY_CALCULATE"."CURRENT_PROFIT" IS '당기순이익';

COMMENT ON COLUMN "TRANSPARENCY_CALCULATE"."LOCATION_IN_INDUSTRY" IS '산업내위치';

COMMENT ON COLUMN "TRANSPARENCY_CALCULATE"."INCREASE_EMPLOYEES" IS '사원수증가';

COMMENT ON COLUMN "TRANSPARENCY_CALCULATE"."REVIEW_SCORE" IS '리뷰평점';

COMMENT ON COLUMN "TRANSPARENCY_CALCULATE"."RENEWAL" IS '갱신일';

COMMENT ON COLUMN "TRANSPARENCY_CALCULATE"."TRAN_TOTAL" IS '투명도총점';

COMMENT ON COLUMN "TRANSPARENCY_CALCULATE"."TRAN_GRADE" IS '투명도등급';

CREATE TABLE "SUPPORT" (
	"SUPPORT_ID"	VARCHAR2(20)		NOT NULL,
	"SUPPORT_TITLE"	VARCHAR2(50)		NULL,
	"SUPPORT_CONTENT"	CLOB		NULL,
	"SUPPORT_DATE"	DATE		NULL,
	"SUPPORT_STATE"	NUMBER		NULL,
	"SUPPORT_INSTITUTE"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "SUPPORT"."SUPPORT_ID" IS '게시판ID';

COMMENT ON COLUMN "SUPPORT"."SUPPORT_TITLE" IS '제목';

COMMENT ON COLUMN "SUPPORT"."SUPPORT_CONTENT" IS '내용';

COMMENT ON COLUMN "SUPPORT"."SUPPORT_DATE" IS '작성일';

COMMENT ON COLUMN "SUPPORT"."SUPPORT_STATE" IS '글상태';

COMMENT ON COLUMN "SUPPORT"."SUPPORT_INSTITUTE" IS '기관명';

CREATE TABLE "ATTACH" (
	"ATTACH_ID"	NUMBER		NOT NULL,
	"FILE_SN"	NUMBER(3)		NOT NULL,
	"FILE_STRE_COURS"	VARCHAR2(2000)		NOT NULL,
	"STRE_FILE_NM"	VARCHAR2(255)		NOT NULL,
	"ORIGNL_FILE_NM"	VARCHAR2(255)		NULL,
	"FILE_EXTSN"	VARCHAR2(20)		NOT NULL,
	"FILE_CN"	CLOB		NULL,
	"FILE_SIZE"	NUMBER(8)		NULL
);

CREATE TABLE "LIKE_COMPANY" (
	"LIKECO_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"COMPANY_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "LIKE_COMPANY"."COMPANY_ID" IS '회사아이디';

CREATE TABLE "LIKE_ANNOUNCEMENT" (
	"LIKEAN_ID"	VARCHAR2(20)		NOT NULL,
	"ANNO_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "LIKE_ANNOUNCEMENT"."ANNO_ID" IS '공고아이디';

CREATE TABLE "ADMIN" (
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "ADMIN"."MEM_ID" IS '회원아이디';

CREATE TABLE "PR" (
	"PR_NO"	VARCHAR2(20)		NOT NULL,
	"PR_NAME"	VARCHAR2(100)		NOT NULL,
	"PR_CONTENT"	VARCHAR2(500)		NOT NULL,
	"PR_DATE"	DATE		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "PR"."PR_NO" IS '홍보글 번호';

COMMENT ON COLUMN "PR"."PR_NAME" IS '홍보글 제목';

COMMENT ON COLUMN "PR"."PR_CONTENT" IS '홍보글 소개';

COMMENT ON COLUMN "PR"."PR_DATE" IS '작성일자';

CREATE TABLE "WALFARE" (
	"WALFARE_CODE"	VARCHAR2(20)		NOT NULL,
	"WALFARE_NAME"	VARCHAR2		NOT NULL,
	"WALFARE_REF"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "WALFARE"."WALFARE_CODE" IS '복지코드';

COMMENT ON COLUMN "WALFARE"."WALFARE_NAME" IS '항목명';

COMMENT ON COLUMN "WALFARE"."WALFARE_REF" IS '상위코드';

CREATE TABLE "ANNO_WALFARE" (
	"ANNOWAL_ID"	VARCHAR2(20)		NOT NULL,
	"WALFARE_CODE"	VARCHAR2(20)		NOT NULL,
	"DANNO_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "ANNO_WALFARE"."ANNOWAL_ID" IS '공고별복지ID';

COMMENT ON COLUMN "ANNO_WALFARE"."WALFARE_CODE" IS '복지코드';

COMMENT ON COLUMN "ANNO_WALFARE"."DANNO_ID" IS '세부공고아이디';

CREATE TABLE "ANNOUNCEMENT_DETAIL" (
	"DANNO_ID"	VARCHAR2(20)		NOT NULL,
	"ANNO_ID"	VARCHAR2(20)		NOT NULL,
	"DANNO_FD"	VARCHAR2(20)		NOT NULL,
	"DANNO_COUNT"	VARCHAR2(20)		NULL,
	"DANNO_CAREER"	VARCHAR2(20)		NOT NULL,
	"DANNO_CAREERYEAR"	VARCHAR2(20)		NULL,
	"DANNO_TASK"	VARCHAR2(200)		NULL,
	"DANNO_DEPARTMENT"	VARCHAR2(20)		NULL,
	"DANNO_PREFER"	VARCHAR2(200)		NULL,
	"DANNO_GENDER"	VARCHAR2(10)		NULL,
	"DANNO_AGE"	VARCHAR2(20)		NULL,
	"DANNO_SALARY"	VARCHAR2(20)		NULL,
	"DANNO_PROBATION"	VARCHAR2(20)		NULL,
	"DANNO_WORKDAY"	VARCHAR2(20)		NULL,
	"DANNO_WORKTIME"	VARCHAR2(20)		NULL,
	"ANNOEDU_CD"	VARCHAR2(20)		NULL,
	"EMPLTYPE_CD"	VARCHAR2(20)		NULL,
	"JOB_CD"	VARCHAR2(20)		NULL,
	"REGION_CD"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "ANNOUNCEMENT_DETAIL"."DANNO_ID" IS '세부공고아이디';

COMMENT ON COLUMN "ANNOUNCEMENT_DETAIL"."ANNO_ID" IS '공고아이디';

COMMENT ON COLUMN "ANNOUNCEMENT_DETAIL"."DANNO_FD" IS '모집분야';

COMMENT ON COLUMN "ANNOUNCEMENT_DETAIL"."DANNO_COUNT" IS '모집인원';

COMMENT ON COLUMN "ANNOUNCEMENT_DETAIL"."DANNO_CAREER" IS '경력';

COMMENT ON COLUMN "ANNOUNCEMENT_DETAIL"."DANNO_CAREERYEAR" IS '경력연차';

COMMENT ON COLUMN "ANNOUNCEMENT_DETAIL"."DANNO_TASK" IS '담당업무';

COMMENT ON COLUMN "ANNOUNCEMENT_DETAIL"."DANNO_DEPARTMENT" IS '근무부서';

COMMENT ON COLUMN "ANNOUNCEMENT_DETAIL"."DANNO_PREFER" IS '우대사항';

COMMENT ON COLUMN "ANNOUNCEMENT_DETAIL"."DANNO_GENDER" IS '성별
여/남';

COMMENT ON COLUMN "ANNOUNCEMENT_DETAIL"."DANNO_AGE" IS '연령';

COMMENT ON COLUMN "ANNOUNCEMENT_DETAIL"."DANNO_SALARY" IS '연봉급여';

COMMENT ON COLUMN "ANNOUNCEMENT_DETAIL"."DANNO_PROBATION" IS '수습기간';

COMMENT ON COLUMN "ANNOUNCEMENT_DETAIL"."DANNO_WORKDAY" IS '근무요일';

COMMENT ON COLUMN "ANNOUNCEMENT_DETAIL"."DANNO_WORKTIME" IS '근무시간';

CREATE TABLE "DEPOSIT" (
	"DEPOSIT_ID"	VARCHAR2(20)		NOT NULL,
	"BANKING_ACCOUNT"	VARCHAR2(50)		NOT NULL,
	"DEPOSIT_DIVISION"	VARCHAR2(10)		NULL,
	"DEPOSIT_SENDER"	VARCHAR2(20)		NULL,
	"DEPOSIT_RECIPIENT"	VARCHAR2(20)		NULL,
	"DEPOSIT_AMOUNT"	NUMBER		NULL,
	"DEPOSIT_DATE"	DATE		NULL
);

COMMENT ON COLUMN "DEPOSIT"."DEPOSIT_ID" IS '입출금내역아이디';

COMMENT ON COLUMN "DEPOSIT"."BANKING_ACCOUNT" IS '계좌번호';

COMMENT ON COLUMN "DEPOSIT"."DEPOSIT_DIVISION" IS '입출금구분';

CREATE TABLE "EXLPROD" (
	"EXLPROD_ID"	VARCHAR2(20)		NOT NULL,
	"EXLPROD_DIVISION"	VARCHAR2(30)		NULL,
	"EXLPROD_FIELD"	VARCHAR2(30)		NULL,
	"EXLPROD_JOB"	VARCHAR2(30)		NULL
);

COMMENT ON COLUMN "EXLPROD"."EXLPROD_ID" IS '분류코드';

CREATE TABLE "ANNO_EDUCATION" (
	"ANNOEDU_CODE"	VARCHAR2(20)		NOT NULL,
	"ANNOEDU_NAME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "ANNO_EDUCATION"."ANNOEDU_CODE" IS '학력코드';

CREATE TABLE "POSITION" (
	"POSITION_CODE"	VARCHAR2(20)		NOT NULL,
	"POSITION_NAME"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "POSITION"."POSITION_CODE" IS '직급직책코드';

COMMENT ON COLUMN "POSITION"."POSITION_NAME" IS '직급직책명';

CREATE TABLE "EMPLTYPE" (
	"EMPLTYPE_CODE"	VARCHAR2(20)		NOT NULL,
	"EMPLTYPE_NAME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "EMPLTYPE"."EMPLTYPE_CODE" IS '고용형태코드';

COMMENT ON COLUMN "EMPLTYPE"."EMPLTYPE_NAME" IS '고용형태';

CREATE TABLE "ANNO_POSITION" (
	"ANNOPOS_CODE"	VARCHAR2(20)		NOT NULL,
	"POSITION_CODE"	VARCHAR2(20)		NOT NULL,
	"DANNO_ID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "ANNO_POSITION"."POSITION_CODE" IS '직급직책코드';

COMMENT ON COLUMN "ANNO_POSITION"."DANNO_ID" IS '세부공고아이디';

CREATE TABLE "UPPER50" (
	"UPPER50_NO"	VARCHAR2(20)		NOT NULL,
	"COMPANY_ID"	VARCHAR2(20)		NOT NULL,
	"UPPER50_SCORE"	VARCHAR2(20)		NOT NULL,
	"JOB_CODE"	VARCHAR2(20)		NOT NULL,
	"UPPER50_SAMPLE"	VARCHAR2(10)		NULL
);

COMMENT ON COLUMN "UPPER50"."UPPER50_NO" IS '합격자 상위50%번호';

COMMENT ON COLUMN "UPPER50"."COMPANY_ID" IS '회사아이디';

COMMENT ON COLUMN "UPPER50"."UPPER50_SCORE" IS '상위 50% 점수';

COMMENT ON COLUMN "UPPER50"."JOB_CODE" IS '직무코드';

CREATE TABLE "UPPER70" (
	"UPPER70_NO"	VARCHAR2(20)		NOT NULL,
	"COMPANY_ID"	VARCHAR2(20)		NOT NULL,
	"UPPER70_SCORE"	VARCHAR2(20)		NOT NULL,
	"JOB_CODE"	VARCHAR2(20)		NOT NULL,
	"UPPER70_SAMPLE"	VARCHAR2(10)		NULL
);

COMMENT ON COLUMN "UPPER70"."UPPER70_NO" IS '합격자 상위 70% 번호';

COMMENT ON COLUMN "UPPER70"."COMPANY_ID" IS '회사아이디';

COMMENT ON COLUMN "UPPER70"."UPPER70_SCORE" IS '상위 70% 점수';

COMMENT ON COLUMN "UPPER70"."JOB_CODE" IS '직무코드';

CREATE TABLE "ITEM_CODE" (
	"ITEM_CODE_ID"	VARCHAR2(20)		NOT NULL,
	"PROCESS_CODE_ID"	VARCHAR2(20)		NOT NULL,
	"ITEM_CODE_NAME"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "ITEM_CODE"."ITEM_CODE_ID" IS '항목코드';

COMMENT ON COLUMN "ITEM_CODE"."PROCESS_CODE_ID" IS '분류코드';

COMMENT ON COLUMN "ITEM_CODE"."ITEM_CODE_NAME" IS '항목명';

CREATE TABLE "PROCESS" (
	"DANNO_ID"	VARCHAR2(20)		NOT NULL,
	"PROCESS_CODE_ID"	VARCHAR2(20)		NOT NULL,
	"PROCESS_STARTDATE"	DATE		NOT NULL,
	"PROCESS_ENDDATE"	DATE		NOT NULL,
	"PROCESS_PERFECT_SCORE"	NUMBER	DEFAULT 0	NOT NULL,
	"ATTACH_ID"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "PROCESS"."DANNO_ID" IS '세부공고아이디';

COMMENT ON COLUMN "PROCESS"."PROCESS_CODE_ID" IS '분류코드';

COMMENT ON COLUMN "PROCESS"."PROCESS_STARTDATE" IS '시작날짜';

COMMENT ON COLUMN "PROCESS"."PROCESS_ENDDATE" IS '종료날짜';

COMMENT ON COLUMN "PROCESS"."PROCESS_PERFECT_SCORE" IS '기준만점';

COMMENT ON COLUMN "PROCESS"."ATTACH_ID" IS '각 과정별 점수 입증 관련 문서 업로드하는 첨부파일 아이디';

CREATE TABLE "REGION" (
	"REGION_CODE"	NUMBER		NOT NULL,
	"REGION_NAME"	VARCHAR2(50)		NOT NULL,
	"REGION_REF"	NUMBER		NULL
);

COMMENT ON COLUMN "REGION"."REGION_CODE" IS '지역코드';

COMMENT ON COLUMN "REGION"."REGION_NAME" IS '지역명';

COMMENT ON COLUMN "REGION"."REGION_REF" IS '상위코드';

CREATE TABLE "ANNO_JOB" (
	"JOB_CODE"	VARCHAR2(20)		NOT NULL,
	"JOB_NAME"	VARCHAR2(50)		NOT NULL,
	"JOB_REF"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "ANNO_JOB"."JOB_CODE" IS '직무코드';

COMMENT ON COLUMN "ANNO_JOB"."JOB_NAME" IS '직무명';

COMMENT ON COLUMN "ANNO_JOB"."JOB_REF" IS '상위코드';

CREATE TABLE "INDUSTRY" (
	"INDUSTRY_CODE"	VARCHAR2(20)		NOT NULL,
	"INDUSTRY_NAME"	VARCHAR2(50)		NULL,
	"INDUSTRY_REF"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "INDUSTRY"."INDUSTRY_CODE" IS '업종코드';

COMMENT ON COLUMN "INDUSTRY"."INDUSTRY_NAME" IS '업종명';

COMMENT ON COLUMN "INDUSTRY"."INDUSTRY_REF" IS '상위코드';

CREATE TABLE "CAREERROAD" (
	"CAROAD_NO"	VARCHAR2(20)		NOT NULL,
	"COMPANY_ID"	VARCHAR2(20)		NOT NULL,
	"JOB_CODE"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "CAREERROAD"."CAROAD_NO" IS '커리어 로드맵 아이디';

COMMENT ON COLUMN "CAREERROAD"."COMPANY_ID" IS '회사아이디';

COMMENT ON COLUMN "CAREERROAD"."JOB_CODE" IS '직무코드';

CREATE TABLE "COMMON_CODE" (
	"CODE"	VARCHAR2(10)		NULL,
	"REF_CODE"	VARCHAR2(10)		NULL,
	"CODE_NAME"	VARCHAR2(20)		NULL,
	"CODE_DESC"	VARCHAR2(200)		NULL
);

CREATE TABLE "LOG_SEEKER" (
	"LOG_ID"	NUMBER		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"ANNO_ID"	VARCHAR2(20)		NOT NULL,
	"LOG_TIME"	DATE		NULL
);

COMMENT ON COLUMN "LOG_SEEKER"."LOG_ID" IS '로그ID';

COMMENT ON COLUMN "LOG_SEEKER"."ANNO_ID" IS '공고아이디';

COMMENT ON COLUMN "LOG_SEEKER"."LOG_TIME" IS '기록시간';

CREATE TABLE "REPLY" (
	"NOTICE_ID"	VARCHAR2(20)		NOT NULL,
	"REPLY_DATE"	DATE		NOT NULL,
	"REPLY_CONTENT"	VARCHAR2		NOT NULL
);

COMMENT ON COLUMN "REPLY"."NOTICE_ID" IS '공지사항ID';

COMMENT ON COLUMN "REPLY"."REPLY_DATE" IS '작성일';

COMMENT ON COLUMN "REPLY"."REPLY_CONTENT" IS '답글내용';

CREATE TABLE "MYRESUME" (
	"MYRESUME_ID"	VARCHAR2(20)		NOT NULL,
	"MEM_ID"	VARCHAR2(20)		NOT NULL,
	"RESUME_ITEM_CODE_ID"	VARCHAR2(20)		NOT NULL,
	"MYRESUME_ITEM_ID"	VARCHAR2(20)		NOT NULL,
	"MYRESUME_ITEM_NO"	NUMBER	DEFAULT 1	NULL,
	"MYRESUME_INSERT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MYRESUME_DELETE_DATE"	DATE	DEFAULT SYSDATE	NULL
);

COMMENT ON COLUMN "MYRESUME"."MYRESUME_ID" IS '이력서 아이디';

COMMENT ON COLUMN "MYRESUME"."RESUME_ITEM_CODE_ID" IS '이력서항목아이디';

COMMENT ON COLUMN "MYRESUME"."MYRESUME_ITEM_ID" IS '학력의 초,중,고,대 등이 들어가는 컬럼';

COMMENT ON COLUMN "MYRESUME"."MYRESUME_ITEM_NO" IS '하나의 이력서에 여러 항목 순번';

COMMENT ON COLUMN "MYRESUME"."MYRESUME_DELETE_DATE" IS '삭제날짜';

CREATE TABLE "RESUME_CODE" (
	"RESUME_ITEM_CODE_ID"	VARCHAR2(20)		NOT NULL,
	"RESUME_ITEM_NAME"	VARCHAR2(30)		NULL
);

COMMENT ON COLUMN "RESUME_CODE"."RESUME_ITEM_CODE_ID" IS '이력서항목아이디';

COMMENT ON COLUMN "RESUME_CODE"."RESUME_ITEM_NAME" IS '경력, 학력, 자격증, 기능, 주요활동, 사회경험, 수상내역, 교육이수, 병역사항, 추가항목1~3';

ALTER TABLE "SEEKER" ADD CONSTRAINT "PK_SEEKER" PRIMARY KEY (
	"MEM_ID"
);

ALTER TABLE "INCRUITER" ADD CONSTRAINT "PK_INCRUITER" PRIMARY KEY (
	"MEM_ID"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEM_ID"
);

ALTER TABLE "ANNOUNCEMENT" ADD CONSTRAINT "PK_ANNOUNCEMENT" PRIMARY KEY (
	"ANNO_ID"
);

ALTER TABLE "JOB_APPLY" ADD CONSTRAINT "PK_JOB_APPLY" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "RESUME_SCORE" ADD CONSTRAINT "PK_RESUME_SCORE" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "INTRODUCTION_SCORE" ADD CONSTRAINT "PK_INTRODUCTION_SCORE" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "TEST_SCORE" ADD CONSTRAINT "PK_TEST_SCORE" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "COMPETENCY_SCORE" ADD CONSTRAINT "PK_COMPETENCY_SCORE" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "PRACTICE_SCORE" ADD CONSTRAINT "PK_PRACTICE_SCORE" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "DISCUSS_SCORE" ADD CONSTRAINT "PK_DISCUSS_SCORE" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "INTERNSHIP_SCORE" ADD CONSTRAINT "PK_INTERNSHIP_SCORE" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "INDEPTH_INTERVIEW_SCORE" ADD CONSTRAINT "PK_INDEPTH_INTERVIEW_SCORE" PRIMARY KEY (
	"APPLY_ID"
);

ALTER TABLE "PROCESS_ITEM" ADD CONSTRAINT "PK_PROCESS_ITEM" PRIMARY KEY (
	"DANNO_ID",
	"ITEM_CODE_ID2"
);

ALTER TABLE "PROCESS_CODE" ADD CONSTRAINT "PK_PROCESS_CODE" PRIMARY KEY (
	"PROCESS_CODE_ID"
);

ALTER TABLE "CAREER" ADD CONSTRAINT "PK_CAREER" PRIMARY KEY (
	"CAREER_ID"
);

ALTER TABLE "EDUCATION" ADD CONSTRAINT "PK_EDUCATION" PRIMARY KEY (
	"EDU_ID"
);

ALTER TABLE "CERTIFICATION" ADD CONSTRAINT "PK_CERTIFICATION" PRIMARY KEY (
	"CERT_ID"
);

ALTER TABLE "MYINTRODUCTION" ADD CONSTRAINT "PK_MYINTRODUCTION" PRIMARY KEY (
	"MYINTRO_ID"
);

ALTER TABLE "FACILITY" ADD CONSTRAINT "PK_FACILITY" PRIMARY KEY (
	"FACILITY_ID"
);

ALTER TABLE "ACTIVITY" ADD CONSTRAINT "PK_ACTIVITY" PRIMARY KEY (
	"ACT_ID"
);

ALTER TABLE "AWARD" ADD CONSTRAINT "PK_AWARD" PRIMARY KEY (
	"AWARD_ID"
);

ALTER TABLE "COURSE" ADD CONSTRAINT "PK_COURSE" PRIMARY KEY (
	"COURSE_ID"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"REVIEW_ID"
);

ALTER TABLE "CUT" ADD CONSTRAINT "PK_CUT" PRIMARY KEY (
	"CUT_ID"
);

ALTER TABLE "BLACKLIST" ADD CONSTRAINT "PK_BLACKLIST" PRIMARY KEY (
	"BLACKLIST_ID"
);

ALTER TABLE "COMPANY" ADD CONSTRAINT "PK_COMPANY" PRIMARY KEY (
	"COMPANY_ID"
);

ALTER TABLE "BOARD_REPORT" ADD CONSTRAINT "PK_BOARD_REPORT" PRIMARY KEY (
	"BOARD_REPORT_ID"
);

ALTER TABLE "COMMENT_REPORT" ADD CONSTRAINT "PK_COMMENT_REPORT" PRIMARY KEY (
	"COMMENT_REPORT_ID"
);

ALTER TABLE "BANKING" ADD CONSTRAINT "PK_BANKING" PRIMARY KEY (
	"BANKING_ACCOUNT"
);

ALTER TABLE "ALRAM" ADD CONSTRAINT "PK_ALRAM" PRIMARY KEY (
	"ALRAM_ID"
);

ALTER TABLE "HELP" ADD CONSTRAINT "PK_HELP" PRIMARY KEY (
	"HELP_ID"
);

ALTER TABLE "NEWS" ADD CONSTRAINT "PK_NEWS" PRIMARY KEY (
	"NEWS_NO"
);

ALTER TABLE "CONTEST" ADD CONSTRAINT "PK_CONTEST" PRIMARY KEY (
	"CONT_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_ID"
);

ALTER TABLE "EXPROD" ADD CONSTRAINT "PK_EXPROD" PRIMARY KEY (
	"EXPROD_ID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMM_ID"
);

ALTER TABLE "EXCART" ADD CONSTRAINT "PK_EXCART" PRIMARY KEY (
	"EXCART_ID"
);

ALTER TABLE "EXPERT" ADD CONSTRAINT "PK_EXPERT" PRIMARY KEY (
	"MEM_ID"
);

ALTER TABLE "INTEREST" ADD CONSTRAINT "PK_INTEREST" PRIMARY KEY (
	"INTE_NO"
);

ALTER TABLE "TODAYSEE" ADD CONSTRAINT "PK_TODAYSEE" PRIMARY KEY (
	"TODAY_NO"
);

ALTER TABLE "EXREVIEW" ADD CONSTRAINT "PK_EXREVIEW" PRIMARY KEY (
	"EXREVIEW_ID"
);

ALTER TABLE "EXEVENT" ADD CONSTRAINT "PK_EXEVENT" PRIMARY KEY (
	"EXEVENT_ID"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_ID"
);

ALTER TABLE "INCUMBENT_INTERVIEW" ADD CONSTRAINT "PK_INCUMBENT_INTERVIEW" PRIMARY KEY (
	"INTERVIEW_ID"
);

ALTER TABLE "COUNSELING" ADD CONSTRAINT "PK_COUNSELING" PRIMARY KEY (
	"COUN_NO"
);

ALTER TABLE "RESUME_FORM" ADD CONSTRAINT "PK_RESUME_FORM" PRIMARY KEY (
	"RESUME_FORM_ID"
);

ALTER TABLE "CORPORATION_TRANSPARENCY" ADD CONSTRAINT "PK_CORPORATION_TRANSPARENCY" PRIMARY KEY (
	"COMPANY_ID"
);

ALTER TABLE "TRANSPARENCY_CALCULATE" ADD CONSTRAINT "PK_TRANSPARENCY_CALCULATE" PRIMARY KEY (
	"COMPANY_ID"
);

ALTER TABLE "SUPPORT" ADD CONSTRAINT "PK_SUPPORT" PRIMARY KEY (
	"SUPPORT_ID"
);

ALTER TABLE "ATTACH" ADD CONSTRAINT "PK_ATTACH" PRIMARY KEY (
	"ATTACH_ID"
);

ALTER TABLE "LIKE_COMPANY" ADD CONSTRAINT "PK_LIKE_COMPANY" PRIMARY KEY (
	"LIKECO_ID"
);

ALTER TABLE "LIKE_ANNOUNCEMENT" ADD CONSTRAINT "PK_LIKE_ANNOUNCEMENT" PRIMARY KEY (
	"LIKEAN_ID"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
	"MEM_ID"
);

ALTER TABLE "PR" ADD CONSTRAINT "PK_PR" PRIMARY KEY (
	"PR_NO"
);

ALTER TABLE "WALFARE" ADD CONSTRAINT "PK_WALFARE" PRIMARY KEY (
	"WALFARE_CODE"
);

ALTER TABLE "ANNO_WALFARE" ADD CONSTRAINT "PK_ANNO_WALFARE" PRIMARY KEY (
	"ANNOWAL_ID"
);

ALTER TABLE "ANNOUNCEMENT_DETAIL" ADD CONSTRAINT "PK_ANNOUNCEMENT_DETAIL" PRIMARY KEY (
	"DANNO_ID"
);

ALTER TABLE "DEPOSIT" ADD CONSTRAINT "PK_DEPOSIT" PRIMARY KEY (
	"DEPOSIT_ID"
);

ALTER TABLE "EXLPROD" ADD CONSTRAINT "PK_EXLPROD" PRIMARY KEY (
	"EXLPROD_ID"
);

ALTER TABLE "ANNO_EDUCATION" ADD CONSTRAINT "PK_ANNO_EDUCATION" PRIMARY KEY (
	"ANNOEDU_CODE"
);

ALTER TABLE "POSITION" ADD CONSTRAINT "PK_POSITION" PRIMARY KEY (
	"POSITION_CODE"
);

ALTER TABLE "EMPLTYPE" ADD CONSTRAINT "PK_EMPLTYPE" PRIMARY KEY (
	"EMPLTYPE_CODE"
);

ALTER TABLE "ANNO_POSITION" ADD CONSTRAINT "PK_ANNO_POSITION" PRIMARY KEY (
	"ANNOPOS_CODE"
);

ALTER TABLE "UPPER50" ADD CONSTRAINT "PK_UPPER50" PRIMARY KEY (
	"UPPER50_NO"
);

ALTER TABLE "UPPER70" ADD CONSTRAINT "PK_UPPER70" PRIMARY KEY (
	"UPPER70_NO"
);

ALTER TABLE "ITEM_CODE" ADD CONSTRAINT "PK_ITEM_CODE" PRIMARY KEY (
	"ITEM_CODE_ID"
);

ALTER TABLE "PROCESS" ADD CONSTRAINT "PK_PROCESS" PRIMARY KEY (
	"DANNO_ID",
	"PROCESS_CODE_ID"
);

ALTER TABLE "REGION" ADD CONSTRAINT "PK_REGION" PRIMARY KEY (
	"REGION_CODE"
);

ALTER TABLE "ANNO_JOB" ADD CONSTRAINT "PK_ANNO_JOB" PRIMARY KEY (
	"JOB_CODE"
);

ALTER TABLE "INDUSTRY" ADD CONSTRAINT "PK_INDUSTRY" PRIMARY KEY (
	"INDUSTRY_CODE"
);

ALTER TABLE "CAREERROAD" ADD CONSTRAINT "PK_CAREERROAD" PRIMARY KEY (
	"CAROAD_NO"
);

ALTER TABLE "COMMON_CODE" ADD CONSTRAINT "PK_COMMON_CODE" PRIMARY KEY (
	"CODE"
);

ALTER TABLE "LOG_SEEKER" ADD CONSTRAINT "PK_LOG_SEEKER" PRIMARY KEY (
	"LOG_ID"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
	"NOTICE_ID"
);

ALTER TABLE "MYRESUME" ADD CONSTRAINT "PK_MYRESUME" PRIMARY KEY (
	"MYRESUME_ID"
);

ALTER TABLE "RESUME_CODE" ADD CONSTRAINT "PK_RESUME_CODE" PRIMARY KEY (
	"RESUME_ITEM_CODE_ID"
);

ALTER TABLE "SEEKER" ADD CONSTRAINT "FK_MEMBER_TO_SEEKER_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "INCRUITER" ADD CONSTRAINT "FK_MEMBER_TO_INCRUITER_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "RESUME_SCORE" ADD CONSTRAINT "FK_JOB_APPLY_TO_RESUME_SCORE_1" FOREIGN KEY (
	"APPLY_ID"
)
REFERENCES "JOB_APPLY" (
	"APPLY_ID"
);

ALTER TABLE "INTRODUCTION_SCORE" ADD CONSTRAINT "FK_JOB_APPLY_TO_INTRODUCTION_SCORE_1" FOREIGN KEY (
	"APPLY_ID"
)
REFERENCES "JOB_APPLY" (
	"APPLY_ID"
);

ALTER TABLE "TEST_SCORE" ADD CONSTRAINT "FK_JOB_APPLY_TO_TEST_SCORE_1" FOREIGN KEY (
	"APPLY_ID"
)
REFERENCES "JOB_APPLY" (
	"APPLY_ID"
);

ALTER TABLE "COMPETENCY_SCORE" ADD CONSTRAINT "FK_JOB_APPLY_TO_COMPETENCY_SCORE_1" FOREIGN KEY (
	"APPLY_ID"
)
REFERENCES "JOB_APPLY" (
	"APPLY_ID"
);

ALTER TABLE "PRACTICE_SCORE" ADD CONSTRAINT "FK_JOB_APPLY_TO_PRACTICE_SCORE_1" FOREIGN KEY (
	"APPLY_ID"
)
REFERENCES "JOB_APPLY" (
	"APPLY_ID"
);

ALTER TABLE "DISCUSS_SCORE" ADD CONSTRAINT "FK_JOB_APPLY_TO_DISCUSS_SCORE_1" FOREIGN KEY (
	"APPLY_ID"
)
REFERENCES "JOB_APPLY" (
	"APPLY_ID"
);

ALTER TABLE "INTERNSHIP_SCORE" ADD CONSTRAINT "FK_JOB_APPLY_TO_INTERNSHIP_SCORE_1" FOREIGN KEY (
	"APPLY_ID"
)
REFERENCES "JOB_APPLY" (
	"APPLY_ID"
);

ALTER TABLE "INDEPTH_INTERVIEW_SCORE" ADD CONSTRAINT "FK_JOB_APPLY_TO_INDEPTH_INTERVIEW_SCORE_1" FOREIGN KEY (
	"APPLY_ID"
)
REFERENCES "JOB_APPLY" (
	"APPLY_ID"
);

ALTER TABLE "PROCESS_ITEM" ADD CONSTRAINT "FK_ANNOUNCEMENT_DETAIL_TO_PROCESS_ITEM_1" FOREIGN KEY (
	"DANNO_ID"
)
REFERENCES "ANNOUNCEMENT_DETAIL" (
	"DANNO_ID"
);

ALTER TABLE "PROCESS_ITEM" ADD CONSTRAINT "FK_ITEM_CODE_TO_PROCESS_ITEM_1" FOREIGN KEY (
	"ITEM_CODE_ID2"
)
REFERENCES "ITEM_CODE" (
	"ITEM_CODE_ID"
);

ALTER TABLE "EXPERT" ADD CONSTRAINT "FK_SEEKER_TO_EXPERT_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "SEEKER" (
	"MEM_ID"
);

ALTER TABLE "CORPORATION_TRANSPARENCY" ADD CONSTRAINT "FK_COMPANY_TO_CORPORATION_TRANSPARENCY_1" FOREIGN KEY (
	"COMPANY_ID"
)
REFERENCES "COMPANY" (
	"COMPANY_ID"
);

ALTER TABLE "TRANSPARENCY_CALCULATE" ADD CONSTRAINT "FK_COMPANY_TO_TRANSPARENCY_CALCULATE_1" FOREIGN KEY (
	"COMPANY_ID"
)
REFERENCES "COMPANY" (
	"COMPANY_ID"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "FK_MEMBER_TO_ADMIN_1" FOREIGN KEY (
	"MEM_ID"
)
REFERENCES "MEMBER" (
	"MEM_ID"
);

ALTER TABLE "PROCESS" ADD CONSTRAINT "FK_ANNOUNCEMENT_DETAIL_TO_PROCESS_1" FOREIGN KEY (
	"DANNO_ID"
)
REFERENCES "ANNOUNCEMENT_DETAIL" (
	"DANNO_ID"
);

ALTER TABLE "PROCESS" ADD CONSTRAINT "FK_PROCESS_CODE_TO_PROCESS_1" FOREIGN KEY (
	"PROCESS_CODE_ID"
)
REFERENCES "PROCESS_CODE" (
	"PROCESS_CODE_ID"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_NOTICE_TO_REPLY_1" FOREIGN KEY (
	"NOTICE_ID"
)
REFERENCES "NOTICE" (
	"NOTICE_ID"
);

